### ISSUE TITLE
JobGenerator argument 'no_job_checks'

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_base#103]
The `JobGenerator` class has an `__init__` argument `no_job_checks`, that somehow influences the child counter.  I'm using it now for the first time and intent to update the docs as I go, but here it's not clear to me what the idea is.

**Comment by jan-janssen** [comment]
It seems to be unused. I assume it is designed to speed up the loading process by not accessing the database, but as I do not find any use case. So I would try to remove it and check if the tests fail.

**Comment by pmrv** [comment]
No tests break and grepping pyiron{,_base} doesn't find any mention, so I'm throwing it out.  PR soon.
