### ISSUE TITLE
Danger with project pack 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron_base#1046]
The following example code: 
```
from pyiron import Project
pr = Project("/Users/janssen/pyiron/projects/2023/2023-02-23-transfer/Gd_PBE_DZP")
pr.pack(destination_path="Gd_PBE_DZP")
```
Deletes the folder `Gd_PBE_DZP` and all calculations inside, without raising a warning.

**Comment by jan-janssen** [comment]
@mgt16-LANL I assume that is the issue that you had, right?

**Comment by pmrv** [comment]
See also #775 .
