### ISSUE TITLE
Nested masters don't work because copy_to misses a dict

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_base#106]
A couple weeks ago I had a nested master subclass (inheriting from `ParallelMaster` and taking as a reference job an `InteractiveWrapper` which in turn has its own `ref_job`). Now this class fails.

I tracked the problem down that `copy_to` fails to copy the `_job_object_dict` attribute of the job. Then, when we try to access the child it needs to be able to reconstruct it from this dict, can't, and throws a `ValueError`.

It works back as of merging #91 but I haven't git bisected to find the trouble yet.

MWE:

```python
from pyiron_base import Project, GenericJob, GenericMaster
pr = Project('scratch')
pr.remove_jobs_silently(recursive=True)
child = pr.create_job(GenericJob, 'child')
master = pr.create_job(GenericMaster, 'master')
master.append(child)
copy_ = master.copy_to(project=pr, new_job_name='copy', new_database_entry=False)
print(master._job_object_dict)  # Looks great
>>> {'child': {'groups': [], 'nodes': []}}
print(copy_._job_object_dict)  # Empty!!!
>>> {}
print(master[0])  # Looks great
>>> {'groups': [], 'nodes': []}
print(copy_[0])  # Throws ValueError because it needs to be able to build it from _job_object_dict
```
<details><summary>Stack trace</summary>
<p>

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-8f29bd3da06f> in <module>
----> 1 print(copy_[0])

~/Liam/pyiron/pyiron_repos/pyiron_base/pyiron_base/master/generic.py in __getitem__(self, item)
    441             item = self._job_name_lst[item]
    442         return self._get_item_when_str(
--> 443             item=item, child_id_lst=child_id_lst, child_name_lst=child_name_lst
    444         )
    445 

~/Liam/pyiron/pyiron_repos/pyiron_base/pyiron_base/master/generic.py in _get_item_when_str(self, item, child_id_lst, child_name_lst)
    553                 return self.project.load(child_id, convert_to_object=True)
    554         elif item_obj in self._job_name_lst:
--> 555             child = self._load_job_from_cache(job_name=item_obj)
    556             if len(name_lst) == 1:
    557                 return child

~/Liam/pyiron/pyiron_repos/pyiron_base/pyiron_base/master/generic.py in _load_job_from_cache(self, job_name)
    493             return self._job_object_dict[job_name]
    494         else:
--> 495             ham_obj = self.project_hdf5[job_name].to_object(
    496                     project=self.project_hdf5,
    497                     job_name=job_name,

~/Liam/pyiron/pyiron_repos/pyiron_base/pyiron_base/generic/hdfio.py in __getitem__(self, item)
    827                         obj = hdf_item.copy()
    828                         return obj
--> 829                 raise ValueError("Unknown item: {}".format(item))
    830             else:
    831                 if item_lst[0] == "":  # absoute HDF5 path

ValueError: Unknown item: child
```

</p>
</details>

**Comment by liamhuber** [comment]
Git bisect identifies 4a61cf4d3be7fdf5eccc22e4701d383f83e7ac61 as the problem. Unfortunately this commit is quite large.

**Comment by jan-janssen** [comment]
But then that seems to be related to an issue with the `to_hdf()` and `from_hdf()` because that is basically what we do in the background https://github.com/pyiron/pyiron_base/blob/master/pyiron_base/job/util.py#L382 and https://github.com/pyiron/pyiron_base/blob/master/pyiron_base/job/util.py#L400

**Comment by liamhuber** [comment]
@jan-janssen indeed, at commit [543e633](https://github.com/pyiron/pyiron_base/commit/543e633be377990c0e364faa78ef845ce1c53ed9) `copy.h5` is created and later read from in the MWE, but as of [4a61cf4](https://github.com/pyiron/pyiron_base/commit/4a61cf4d3be7fdf5eccc22e4701d383f83e7ac61) this h5 file is never created. 

This is a good hint, I'll try to find where that's not happening.

**Comment by jan-janssen** [comment]
It is not written or it is deleted after it is written?

**Comment by liamhuber** [comment]
It might well be deleted after it's written, but the copied job doesn't get it's `_job_object_dict` set in the meantime. 

I think it might be because `_job_reload_after_copy` is trying to work in place but actually needs to return the job. My first naive attempt at this didn't fix things, but I might not yet be catching the returned job at the right spot.

**Comment by liamhuber** [comment]
Indeed, even with returning a job, `_job_reload_after_copy` is not population the copied job's `_job_object_dict`. I'll look into `from_hdf`...

**Comment by liamhuber** [comment]
My hypothesis is that we used to not delete the HDF file created during copy, and that `GenericMaster` relied on this HDF file, but now we delete it and it is suddenly exposed that `GenericMaster._job_object_dict` is not properly re-populated.

**Comment by liamhuber** [comment]
> I think it might be because `_job_reload_after_copy` is trying to work in place but actually needs to return the job. My first naive attempt at this didn't fix things, but I might not yet be catching the returned job at the right spot.

I was conclusively wrong, `_job_reload_after_copy` is fine in-place. It just seems to not be loading everything we need.

**Comment by liamhuber** [comment]
@jan-janssen ok, the solution exists but it's not very friendly atm.

What I would *like* to do is add the following to the end of `pyiron_base.job.master.generic.GenericMaster.from_hdf`:

```python        
for job_name in self._job_name_lst:
    self._job_object_dict[job_name] = self.project_hdf5.load(job_name)
```

This ought to be fine, as the child HDF5 does exist (transiently) during the `copy_to` process. By adding print statements to the code I can see it there and verify that it's contents are what I want. The catch is that the `load` method ultimately works its way back to `pyiron_base.project.generic.Project.load`, which has the content

```python
        if self.sql_query is not None:
            s.logger.warning(
                "SQL filter '%s' is active (may exclude job) ", self.sql_query
            )
        job_id = self.get_job_id(job_specifier=job_specifier)
        if job_id is None:
            s.logger.warning("Job '%s' does not exist and cannot be loaded", job_specifier)
            return None
        return self.load_from_jobpath(
            job_id=job_id, convert_to_object=convert_to_object
        )
```

Since the HDF exists only transiently and we never create a database id, `job_id is None` and the loaded job is simply `None`.

I can immediately imagine a workaround where we re-instantiate a new job of the right class and copy all the HDF5 data over...but I sort of hoped that this is what `load` would be doing. It seems extremely unpleasant that we have everything set up to use these transient HDF5 files, but are unable to load them. Do we have an existing workaround for this? I'll start looking for it now, but you might already know.

**Comment by jan-janssen** [comment]
I guess the reason why we do not have it at the moment, is that it can take a lot of time to load all child jobs and usually the get item function can reload a specific job when it is needed based on the job name https://github.com/pyiron/pyiron_base/blob/master/pyiron_base/master/generic.py#L534

**Comment by liamhuber** [comment]
> I guess the reason why we do not have it at the moment, is that it can take a lot of time to load all child jobs and usually the get item function can reload a specific job when it is needed based on the job name https://github.com/pyiron/pyiron_base/blob/master/pyiron_base/master/generic.py#L534

Ok, but this is not a solution to the very real and legitimate problem of copying master jobs. The `_get_item_when_str` method you linked explicitly takes the child job ids as an argument, but these don't exist if we're copying an unexecuted master job -- which is *exactly* the situation that comes up if we have nested masters.

I like the changes over the last two weeks, but two weeks ago this functionality was there and now it's gone. I don't have a good solution now, but I do consider this to be core functionality and we should get it addressed reasonably quickly.

**Comment by liamhuber** [comment]
Resloved in #107
