### ISSUE TITLE
FileTable not updating its path

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_base#1073]
More fundamentally, the `Singleton` class is not updating its attributes like I expect on re-instantiation. This is the source of the current failures on #951.

MWE:
```python
from pyiron_base import Project
from pyiron_base.database.filetable import FileTable

pr = Project('tmp')
f = FileTable(pr.path)
print(f._project)
>>> ".../tmp"

pr2 = Project('tmp2')
f2 = FileTable(pr2.path)
print(f._project)
>>> ".../tmp"
print(f2._project)
>>> ".../tmp" 
# This last one needs to be ".../tmp2"!!!!
```

With the database turned off, projects are re-instantiating a `FilePath` with their own path [here](https://github.com/pyiron/pyiron_base/blob/c1a02fe54b64080215e971c3d8ab0cba2b8d7cf0/pyiron_base/project/generic.py#L139). But if _any other project_ has already done this, then the path is ignored.

I'll fix this tomorrow. Right now I'm of the opinion that `Singleton` needs to handle re-instantiation better, but that opinion is subject to change once I start working on it.

**Comment by liamhuber** [comment]
Comment from @jan-janssen on the PR:

>> I'll fix that separately and merge the fix from main into here later.
>
>Somehow this issue sounds familiar. @niklassiemer did not we have something similar with file tables on different project levels? The issue is that the project object is reinitialized several times - for example for every job - but we do not want the file system to be reindexed. So the naive idea was storing the filetable as a singleton. But obviously this only works if the path remains the same. A more clean solution would be to store multiple file tables when working on multiple directories.

**Comment by liamhuber** [comment]
@jan-janssen it sounds also like maybe the `FileTable` only needs to re-index on changes of the path? Then the same project can instantiate as many as it wants without costing anything. Might get a bit computationally pricey if you're going back and forth looking at the `.db` of two different non-database projects, but that's a niche enough occurrence that I'm willing to sacrifice speed.

If we do it only on path changes, then the singleton just needs to update its properties when it's re-instantiated with different ones. This is what I expected the behaviour to be anyhow tbh.

**Comment by liamhuber** [comment]
@niklassiemer and @jan-janssen, I've made two competing PRs for making sure that file tables actually have an up-to-date index:
- #1074 which introduces a new updatable-singleton and re-indexes whenever it gets instantiated with a new path
- #1075 which just makes it not a singleton any more

#1074 has the chance of weird side-effects depending on what order you instantiate things, as the file table _is still a singleton_, so when its path gets updated in one place, it gets updated everywhere.

#1075 is not totally naive and avoids re-instantiating a new `FileTable` on a project that already has one, but otherwise completely undoes whatever efficiency gains were being sought by making this thing a singleton to start with. I'm more comfortable with this because it seems like it is more stable.

What bothers me is that the OG example above was not caught by tests (it absolutely cannot be intended behaviour that the first-instantiator gets the privilege of setting the path forever),  _both_ the PRs pass all the tests, and there is no spec I could see for what the heck the expectations of the file table are to begin with. I checked the blame, but [the commit that added the `Singleton` metaclass](https://github.com/pyiron/pyiron_base/commit/efd3451a4c293ff679ec3373fab75c9e579b72e9) is giant and I don't gain any insight into why this was done.

IMO, `FileTable` is extremely broken on HEAD right now and we need to get this fixed. Feedback on what the actual expectations are for this class from someone who's used it/designed it would be very helpful.

**Comment by niklassiemer** [comment]
I would favor the normal, re-inited classes. However, I am not sure what problems/performance issues arise by this. Two `Project` instances pointing to the same path could have different `FileTables`. 
There could be a third option: path Singletons... 
```
class FileTableSingleton(ABCMeta):
    _instances = {}

    def __call__(cls, path):
        _path = os.path.abspath(path)
        if _path not in cls._instances:
            cls._instances[_path ] = super(FileTableSingleton, cls).__call__(
                path
            )
        return cls._instances[_path]
```
This way each Project at a known location would get the same FileTable and not need to init anew. Howver, there may be a lot more problems to come for such a design?!


EDIT: fixed typo in python snippet

**Comment by liamhuber** [comment]
> I would favor the normal, re-inited classes. However, I am not sure what problems/performance issues arise by this. 

Good. Frankly, I'd be much more comfortable receiving a complaint that something is suddenly much slower than a user wants, than that a user stumble upon this bug and realize the functionality is just fundamentally broken.

> There could be a third option: path Singletons... ...This way each Project at a known location would get the same FileTable and not need to init anew. Howver, there may be a lot more problems to come for such a design?!

This pattern looks ok to me. I would first roll back `FileTable` being a singleton at all, and then proceed with this (or something like it) as a performance improvement.

One thing to note is that this is not exclusively used for projects -- `GenericJob.transfer_from_remote` also instantiates it. So it seems to me like the most likely use case suffering a performance hit is transferring a large project from remote to local. In this way, I could see the optimal version of `FileTable` being an updating singleton that compares the new path to the existing path, and re-indexes from the shared root? This could get very pricey if you have two small sibling paths whose shared parent has _lots_ to index, but it would be efficient in terms of minimizing re-index calls..... Ultimately I'm just not super familiar with the use cases so I'm not sure what tradeoffs are most worthwhile.

**Comment by jan-janssen** [comment]
> Good. Frankly, I'd be much more comfortable receiving a complaint that something is suddenly much slower than a user wants, than that a user stumble upon this bug and realize the functionality is just fundamentally broken.

I disagree - the setup without database is working at LANL and the performance is really essential for us. Unfortunately this week as well as the next week are rather busy, still I try to take a look at the pull requests during the weekend.

**Comment by liamhuber** [comment]
> the setup without database is working at LANL and the performance is really essential for us. 

I'm going to be pedantic here: "The setup without database" **DOES NOT WORK**; _your_ particular workflow without the database _happens_ to work.

I am not even sure of all the side effects possible that may happen as a result of this bug, but here's another example of incorrect behaviour:

```python
from pyiron_base import state
from pyiron_atomistics import Project

# Turn off the database
state.update({'disable_database': True})


# Make a couple of projects and ensure they're empty
pr0 = Project('pr0')
pr0.remove_jobs(silently=True, recursive=True)

pr1 = Project('pr1')
pr1.remove_jobs(silently=True, recursive=True)

# Do "high throughput" calculations that vary slightly per project
job_instances = {0: {}, 1: {}}
for i, pr in enumerate([pr0, pr1]):
    for el in ["Al", "Fe", "Ni"]:
        struct = pr.create.structure.bulk(el)
        if i == 1:
            struct = struct.repeat(5)

        job = pr.create.job.Lammps(f"{el}")
        job.structure = struct
        job.run()
        job_instances[i][el] = job

# Instances get the right project
for i in [0, 1]:
    print(job_instances[i]["Al"].project.name)
# >>> pr0
# >>> pr1

# But pr1 does not have a job table!
print(len(pr0.job_table()))
# >>> 3
print(len(pr1.job_table()))
# >>> 0

# pr1 is empty
pr1
# >>> {'groups': [], 'nodes': []}
# BUT THE FILES EXIST
import os
os.listdir(pr1.path)
# >>> ['Al.h5',
# ...  'Al_hdf5',
# ...  'Fe_hdf5'
# ...  'Fe.h5',
# ...  'Ni.h5',
# ...  'Ni_hdf5']

# And thus we can't load the jobs from pr1, even though they're there
pr0.load("Al")
# Loads fine
pr1.load("Al")
# >>> 2023-04-27 10:46:07,420 - pyiron_log - WARNING - Job 'Al' does not exist and cannot be loaded
```

Now suppose you come back later to look at the data, but just happen to instantiate the projects in the opposite order, then the trouble gets reversed!

```python
from pyiron_base import state
from pyiron_atomistics import Project

# Turn off the database
state.update({'disable_database': True})


# Now instantiate the projects in opposite order
pr1 = Project('pr1')
pr0 = Project('pr0')

# Now pr0 does not have a job table!
print(len(pr0.job_table()))
# >>> 0
print(len(pr1.job_table()))
# >>> 3

# And now it is pr0 that cannot load jobs
pr0.load("Al")
# >>> 2023-04-27 10:46:07,420 - pyiron_log - WARNING - Job 'Al' does not exist and cannot be loaded
pr1.load("Al")
# loads fine
```

I don't know what your setup looks like that it is working for you guys, but you may wish to do some spot-check sanity checks to make sure it is actually working the way you think it is, because this feature really is broken.

> I disagree... Unfortunately this week as well as the next week are rather busy, still I try to take a look at the pull requests during the weekend.

For the record I'm uncomfortable delaying the fix to an obvious bug for multiple weeks. However, since problem was causing the bug in #951 weeks ago already and no one has complained, I can be practical about it -- you guys are apparently the only ones using this feature, and it apparently works for you, so then it's fair to fix it on your timeframe.

**Comment by jan-janssen** [comment]
> I'm going to be pedantic here: "The setup without database" **DOES NOT WORK**; _your_ particular workflow without the database _happens_ to work.

All I want is that we do not have any issues with the high throughput projects that current use pyiron at LANL. To get more local users motivated to use pyiron and continue to build a user base it is essential to maintain stability.

**Comment by liamhuber** [comment]
> To get more local users motivated to use pyiron and continue to build a user base it is essential to maintain stability.

I am not against stability. I am opposed to leaving the code in a clearly broken state. You can't even instantiate a second project with the database turned off. Clearly this should be unacceptable. 

But, as I said before, I can handle a two-week delay before this gets addressed in-depth -- not very many users seem to call on this functionality outside LANL, so the odds of causing a headache with the current broken state are minimal.

**Comment by jan-janssen** [comment]
@mgt16-LANL The issue you had with the two projects and different paths is also related to this one.

**Comment by mgt16-LANL** [comment]
@jan-janssen - That's right. Having it be a "super project" project with projects below is an okay workaround for now - but what @liamhuber says is accurate. It would be much nicer to be able to instantiate/connect to multiple projects under a single notebook for merging across my datasets.
