### ISSUE TITLE
OSError: Read-only file system :`~/pyiron.log`; Queued job fails!

### ISSUE THREAD

**Issue by hari-ushankar** [pyiron/pyiron_base#1096]
Hello!

I seem to have run into an issue while submitting jobs using a queue on my compute cluster. When I installed pyiron using mamba, I have put my install files onto my home dir. 

I'm trying to run the following job:
```
from pyiron_base import state
config = state.settings.configuration.copy()
state.update({
        'sql_file': '/scratch/account-holder/username/database.db',
        'sql_type': 'SQLite',
})
state.update(config)
print(state.settings.configuration)
from pyiron_atomistics import Project
import os

pr = Project("test_vasp")
basis = pr.create.structure.bulk('Al', cubic=True)
supercell_3x3x3 = basis.repeat([2, 2, 2])
job = pr.create_job(job_type=pr.job_type.Vasp, job_name='vasp_job')
job.structure = supercell_3x3x3
job.set_exchange_correlation_functional("PBE")
job.plane_wave_cutoff = 200
job.set_kpoints([2]*3)
job.set_occupancy_smearing("fermi", width=0.2)
job.calc_static()
job.run(run_mode="queue", delete_existing_job=True)
os.system("qstat -u username")
```

I looked into some of the previous issues and added a small snippet of code to change where the .db file is written. But this doesn't change while the job is run.

Output from my `pi_2.e.....` file:
```
 Traceback (most recent call last):
 15   File "<frozen runpy>", line 189, in _run_module_as_main
 16   File "<frozen runpy>", line 112, in _get_module_details
 17   File "/home/username/mambaforge/envs/pyiron/lib/python3.11/site-packages/pyiron_base/__init__.py", line 5, in <module>
 18     from pyiron_base.state import state
 19   File "/home/username/mambaforge/envs/pyiron/lib/python3.11/site-packages/pyiron_base/state/__init__.py", line 17, in <module>
 20     from pyiron_base.state.logger import logger as _logger
 21   File "/home/username/mambaforge/envs/pyiron/lib/python3.11/site-packages/pyiron_base/state/logger.py", line 72, in <module>
 22     logger = setup_logger()
 23              ^^^^^^^^^^^^^^
 24   File "/home/username/mambaforge/envs/pyiron/lib/python3.11/site-packages/pyiron_base/state/logger.py", line 61, in setup_logger
 25     fh = logging.FileHandler("pyiron.log")
 26          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 27   File "/home/username/mambaforge/envs/pyiron/lib/python3.11/logging/__init__.py", line 1181, in __init__
 28     StreamHandler.__init__(self, self._open())
 29                                  ^^^^^^^^^^^^
 30   File "/home/username/mambaforge/envs/pyiron/lib/python3.11/logging/__init__.py", line 1213, in _open
 31     return open_func(self.baseFilename, self.mode,
 32            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 33 OSError: [Errno 30] Read-only file system: '/arc/home/username/pyiron.log'

```

This seems odd to me, shouldn't the .db file location be updated? 

Also, I have tried to change the .db FILE location by manually editing the `~/.pyiron` file:

```
[DEFAULT]
RESOURCE_PATHS = /arc/home/username/pyiron_resources, /arc/home/username/mambaforge/envs/pyiron/share/pyiron
PROJECT_CHECK_ENABLED = False
#DISABLE_DATABASE = True
FILE = /scratch/account-holder/username/pyiron.db
```

Nothing seems to solve this. Any suggestions from @pmrv , @jan-janssen  @liamhuber ?

**Comment by jan-janssen** [comment]
Hi @hari-ushankar, 

Where is the python script located? By default pyiron creates the Project relative to your current working directory and stores the log `pyiron.log` in the root of your working directory. So in your case you should be able to solve this issue, by copying your script to scratch and then execute it there.

**Comment by hari-ushankar** [comment]
Actually I meant to say pyiron.db and not pyiron.log, my bad, sorry!

Yes, my python script was already in the scratch folder when I executed it.
Somehow the change in pyiron.db file location isn't changed when I specify
I the script or when I manually change .pyiron file.

**Comment by jan-janssen** [comment]
Do you submit to a queuing system? Some queuing systems like SLURM provide the option to forward the user environment: 
https://slurm.schedmd.com/sbatch.html - `--get-user-env` This is used in https://pysqa.readthedocs.io/en/latest/queue.html#slurm which is used inside pyiron to submit jobs to the queue. If this option is not set it is possible that the execution of your calculation starts in the home directory rather than the directory where the job was submitted. The other important option is to specify the working directory for SLURM this is `--chdir`.

**Comment by hari-ushankar** [comment]
Actually, this could be the issue. My queue system is TORQUE. There is no tag specified for changing dir in here: https://pysqa.readthedocs.io/en/latest/queue.html#torque

My `run_queue.sh` now contains:
```
#!/bin/bash
#PBS -A account-holder
#PBS -N pi_2
#PBS -l walltime=00:04:00,select=1:ncpus=8:mpiprocs=8:ompthreads=1:mem=25gb:cpu_arch=skylake
module load Software_Collection/2021
module load openpbs/20.0.1 gmp/6.2.1 openmpi/4.1.1-cuda11-3 gcc/5.5.0
module load numactl/2.0.14 intel-mkl


source /arc/home/username/mambaforge/bin/activate pyiron
python -m pyiron_base.cli wrapper -p /scratch/account-holder/username/test_vasp/vasp_job_hdf5/vasp_job -j 2
```

**Comment by hari-ushankar** [comment]
@jan-janssen , I have solved this issue. Sorry for the trouble!
