### ISSUE TITLE
Job_id at server is none for any job_name other than 'Al_T800K_remote'

### ISSUE THREAD

**Issue by adyant-agrawal** [pyiron/pyiron_base#1100]
I tried to write a simple script to test the submission of jobs on a remote server.  I followed the steps in the tutorial.

```py
from pyiron_atomistics import Project
import os
pr = Project("test_lammps")
job = pr.create_job(job_type=pr.job_type.Lammps, job_name='Al_T800K_remote', delete_existing_job=True)
basis = pr.create.structure.bulk('Al', cubic=True)
supercell_3x3x3 = basis.repeat([3, 3, 3])
job.structure = supercell_3x3pot = job.list_potentials()[0]
print ('Selected potential: ', pot)
job.potential = pot
job.calc_md(temperature=800, pressure=0, n_ionic_steps=10000)
job.server.queue = "queue_one"
job.server.cores = 1
job.run(run_mode="queue", delete_existing_job=True)
```

This works flawlessly. However, if I change the job_name to say 'Al_T801K_remote', the id is none (the hpc job name is pi_None) and the job crashes with the error:
```
...python3.11/site-packages/pyiron_base/jobs/job/wrapper.py", line 61, in __init__
    self.job = pr.load(int(job_id))
                       ^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'None'
```
I am using the  versions:
pyiron                        0.4.7
pyiron-atomistics             0.2.66
pyiron-base                   0.5.37

**Comment by liamhuber** [comment]
That is quite strange. Normally after hitting 'run' in a notebook, I get debug print warnings beneath the cell "job blah blah was created and assigned ID blah blah". Do you get such output with the original name? Does such output persist with the new name?

It looks like the job is not getting created and assigned to the database at run time, so I'm not shocked that it has trouble reading the (non existent) ID later, but I don't know why changing the name would have any impact here.

Is there any more to the stack trace than that?

**Comment by jan-janssen** [comment]
@adyant2 Can you share your `~/.pyiron` config? If you use any password in this configuration just change it to `****`.

**Comment by adyant-agrawal** [comment]
Thank you for the quick response.
@liamhuber Yes, I get the following output below the cell:
```Selected potential:  1995--Angelo-J-E--Ni-Al-H--LAMMPS--ipr1
The job Al_T801K_remote was saved and received the ID: 1
[/tikhome/aagrawal/mambaforge/envs/pyironenv/lib/python3.11/site-packages/pysqa/utils/remote.py:240](https://file+.vscode-resource.vscode-cdn.net/tikhome/aagrawal/mambaforge/envs/pyironenv/lib/python3.11/site-packages/pysqa/utils/remote.py:240): UserWarning: 
  warnings.warn(stderr.read().decode())
100%|██████████| 1[/1](https://file+.vscode-resource.vscode-cdn.net/1) [00:00<00:00, 90.64it[/s](https://file+.vscode-resource.vscode-cdn.net/s)]
100%|██████████| 4[/4](https://file+.vscode-resource.vscode-cdn.net/4) [00:00<00:00, 246.26it[/s](https://file+.vscode-resource.vscode-cdn.net/s)]
Queue system id:  233274
[/tikhome/aagrawal/mambaforge/envs/pyironenv/lib/python3.11/site-packages/pysqa/utils/remote.py:240](https://file+.vscode-resource.vscode-cdn.net/tikhome/aagrawal/mambaforge/envs/pyironenv/lib/python3.11/site-packages/pysqa/utils/remote.py:240): UserWarning: 2023-05-15 17:00:08,683 - pyiron_log - INFO - job: Al_T801K_remote id: None, status: initialized, submitted: queue id 233274

  warnings.warn(stderr.read().decode())
```

In the case of jobname `'job: Al_T800K_remote'`, I get the same output except for the part `job: Al_T800K_remote id: 2` . I also do not understand why changing the name would have an impact. Also, the `id` is always 2 which is weird.


The complete stack trace is as follows:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/aagrawal/mambaforge/envs/pyironenv/lib/python3.11/site-packages/pyiron_base/cli/__main__.py", line 3, in <module>
    main()
  File "/home/aagrawal/mambaforge/envs/pyironenv/lib/python3.11/site-packages/pyiron_base/cli/control.py", line 59, in main
    args.cli(args)
  File "/home/aagrawal/mambaforge/envs/pyironenv/lib/python3.11/site-packages/pyiron_base/cli/wrapper.py", line 31, in main
    job_wrapper_function(
  File "/home/aagrawal/mambaforge/envs/pyironenv/lib/python3.11/site-packages/pyiron_base/jobs/job/wrapper.py", line 148, in job_wrapper_function
    job = JobWrapper(
          ^^^^^^^^^^^
  File "/home/aagrawal/mambaforge/envs/pyironenv/lib/python3.11/site-packages/pyiron_base/jobs/job/wrapper.py", line 61, in __init__
    self.job = pr.load(int(job_id))
                       ^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'None'
```


@jan-janssen please find below the contents of `.pyiron`:
```
[DEFAULT]
PROJECT_PATHS = ~/pyiron/projects
RESOURCE_PATHS = ~/pyiron/resources, ~/mambaforge/envs/pyironenv/share/pyiron
```
I keep the same config on local and remote.

**Comment by adyant-agrawal** [comment]
Adding `DISABLE_DATABASE = True` in the `.pyiron` on HPC and removing `PROJECT_PATHS = ~/pyiron/projects` solved the issue for me. Now it doesn't pass the job_id to the cli. :)

**Comment by liamhuber** [comment]
@adyant2 glad you could solve! Sorry to not be more help directly, I've never used the remote queues myself.

Tangential note:

> Also, the `id` is always 2 which is weird.

So if it's always *always* 2, that is indeed weird. But your code snippet has `delete_existing_job=True`, so if it's just the case that the ID stays 2 on repeated calls of that code, this is expected as it's just deleting and replacing the old "2".
