### ISSUE TITLE
:bug: `FileTable` does not play well with non-`None` project paths

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_base#1103]
This has caused me an embarassing amount of trouble over on #951. The crux of the problem is that the `project` column in the `FileTable` database-like object is using abspaths, while the `FileTable` logic itself is looking at the `Project.project_path` which is only relative to the `project_paths` from the settings.

# Demonstration

This works great:

```python
from pyiron_base import Project, state

pr = Project("test")
print(pr.root_path, pr.project_path)
>>> None /Users/huber/work/pyiron/notebooks/test/
# Note that I don't have TOP_LEVEL_DIRS specified in my config

job = pr.create.job.ScriptJob(job_name="foo")
job.save()

state.update({"disable_database": True})

print(len(pr.job_table(recursive=False)))
>>> 1
      
pr.remove_jobs(recursive=True, silently=True)
pr.remove(enable=True)
```

While this fails to find the job:

```python
from pyiron_base import Project, state

from pathlib import Path
state.update({"project_paths": str(Path(".").absolute())})

pr = Project("test")
print(pr.root_path, pr.project_path)
>>> /Users/huber/work/pyiron/notebooks/ test/

job = pr.create.job.ScriptJob(job_name="foo")
job.save()

state.update({"disable_database": True})

print(len(pr.job_table(recursive=False)))
>>> 0

print(pr.job_table().project[0])
>>> /Users/huber/work/pyiron/notebooks/test/

pr.remove_jobs(recursive=True, silently=True)
pr.remove(enable=True)
```

# Why

The offending code is [here in `FileTable`](https://github.com/pyiron/pyiron_base/blob/0fe1191f8c8a655a5ffc2a19dad33a54089b7bf1/pyiron_base/database/filetable.py#L602), where our `if recursive` clause uses `else: return self._job_table[self._job_table.project == project_path]`. `project_path` comes from `Project.project_path`, which is relative to the `Project.root_path`, but the jobs use the absolute path (I can't find the code responsible for this, but you see it in the snippet above).

# What to do?

IMO, the quickest and easiest solution is to change `self._job_table.project == project_path` to `self._job_table.project.str.endswith(project_path)`. I'll go make a PR that does that right after I post this. But, this isn't a corner I really play with -- I don't think I've ever specified `TOP_LEVEL_DIRS` -- so I wanted to get some feedback to see if anyone else sees a danger of side effects.

**Comment by jan-janssen** [comment]
Can you post your `.pyiron` config? Do you have the two following lines? 
```
PROJECT_CHECK_ENABLED = False
DISABLE_DATABASE = True
```

**Comment by liamhuber** [comment]
Not now I can't, I'm on mobile and will post it tomorrow.

I don't see how it's relevant. There should be no available config configuration that allows it to fail this way. The CI config fails this way, so it's not like it's some totally bizarre edge case.

**Comment by jan-janssen** [comment]
Looking at it again - I want to remove the `root_path` - so that the `project_path` is always the absolute path. 
```
pr = Project("test")
print(pr.root_path, pr.project_path)
>>> /Users/huber/work/pyiron/notebooks/ test/
```
In the file table we already work with the absolute path, while in the database based variant we still use the split between `pr.root_path` and `pr.project_path`. In addition the challenge that you give pyiron to dynamically switch from one kind of database interface to another is something I at least never indented as a feature. I always thought people would instantiate the class again after changing their configuration. This been said I am currently not so happy with the pull request, as I feel it is changing the wrong part of the code. Just dropping the distinction between `root_path` and `project_path` should help.

**Comment by liamhuber** [comment]
> Looking at it again - I want to remove the `root_path` - so that the `project_path` is always the absolute path. ... This been said I am currently not so happy with the pull request, as I feel it is changing the wrong part of the code. Just dropping the distinction between `root_path` and `project_path` should help.

I agree. That is a change I would also like to see. However, I currently have no sense of how involved that change is or what other side effects might crop up. What I like about #1104 is that it (a) fixes what is broken and fixes it _now_, (b) is a zero-line change, and (c) will remain functional (although no longer strictly necessary) after we make the "wouldn't it be nice" change of purging `root_path` and `TOP_LEVEL_DIRS`.

As it stands, database-free pyiron is still broken -- previously you couldn't instantiate a second project, now you can't load jobs if your config file is "wrong". #951 has been stuck with broken unit tests _since December 2022_ -- not because there's anything wrong with that PR, but merely because it has the audacity to test database free usage and thus has been uncovering various problems in `FileTable`. In principle that's fine, and I'm glad these issues are getting uncovered so they can be resolve, but I am also starting to get really frustrated that #951 can't be merged because some totally different class has all these problems.

If you think that purging `root_path` will be quick and easy (like, doable this week), then let's go for it. Otherwise, I feel strongly that #1104 (or something very similar) should be merged promptly to move the code from its current, broken state, to a working state. Then we can proceed, from that working state, to make deeper changes like getting rid of `root_path`. At the end, (if we want, since it should not be necessary for function but perhaps slightly clearer for intent) we can even go back and revert #1104 by replacing `.str.endswith(` with `==` again.

"A good plan violently executed now is better than a perfect plan executed at some indefinite time in the future."

**Comment by liamhuber** [comment]
> Can you post your `.pyiron` config? Do you have the two following lines?
> 
> ```
> PROJECT_CHECK_ENABLED = False
> DISABLE_DATABASE = True
> ```

BTW, I don't have one. Nor do I have any env settings. I just run the default behaviour from the state module, which includes 

```python
'project_check_enabled': False,
'disable_database': False,
```

Of course, [on the CI](https://github.com/pyiron/pyiron_base/blob/main/.ci_support/pyironconfig.py) we specify `project_paths` in the form of a `TOP_LEVEL_DIRS` flag in the config. This is why tests in #951 were passing on my local machine (where `root_path` is `None`) but failing remotely.

**Comment by jan-janssen** [comment]
> What I like about #1104 is that it (a) fixes what is broken and fixes it _now_, (b) is a zero-line change, and (c) will remain functional (although no longer strictly necessary) after we make the "wouldn't it be nice" change of purging `root_path` and `TOP_LEVEL_DIRS`.

To me your change is internally forcing the `job_table()` to be always recursive. But at LANL we use the `job_table()` on large projects, where I would have pyiron table objects at the root level and thousands of DFT calculation in multiple sub projects. Forcing the `job_table()` to be always recursive slows down the process quite drastically. So this change is not acceptable. 

> As it stands, database-free pyiron is still broken -- previously you couldn't instantiate a second project, now you can't load jobs if your config file is "wrong".

Switching from a configuration with database to a configuration without a database is a functionality we never promised. It is used in our tests, but rarely used in practice. I am fine with failing hard in this case and just disable the ability to switch the database backend in an active project. But this would break our current test environment, so it is also no solution. 

>  #951 has been stuck with broken unit tests _since December 2022_ -- not because there's anything wrong with that PR, but merely because it has the audacity to test database free usage and thus has been uncovering various problems in `FileTable`. In principle that's fine, and I'm glad these issues are getting uncovered so they can be resolve, but I am also starting to get really frustrated that #951 can't be merged because some totally different class has all these problems.

I can feel your frustration. The code does not fix itself. I do not have the time to fix the code and the file table is not tested in the way it should be. Still I spend more time commenting on these issues, to make sure the code does not get more broken and we have more issues, but unless we have more core developers who look into these issues I do not see us making progress on this any faster. I suggested the correct solution to solve this issue, rather than adding yet another workaround which breaks other parts of the code or makes the code even harder to maintain and I am going to implement this solution at some point, but I can not do it in the up-coming weeks as I am busy with other projects.

**Comment by liamhuber** [comment]
> To me your change is internally forcing the `job_table()` to be always recursive. 

This is incorrect. `.endswith` catches all jobs at that level who belong to that sub-project, but not those who belong to sub-projects. `.contains` in the other clause where `recursive=True` catches the recursive case. This objection is not relevant.

> Switching from a configuration with database to a configuration without a database is a functionality we never promised. It is used in our tests, but rarely used in practice. I am fine with failing hard in this case and just disable the ability to switch the database backend in an active project. But this would break our current test environment, so it is also no solution.

I agree, simply forbidding the switch breaks tests and thus is not desirable. So we will continue to allow it. We also show how it works in our unit tests, which is only one step removed from showing it in documentation. If we will not disallow `project_paths` + `disable_database`, then we should support it. #1104 accomplishes this.

> The code does not fix itself.

Indeed, #1104 fixes it.

> I suggested the correct solution to solve this issue, rather than adding yet another workaround which breaks other parts of the code or makes the code even harder to maintain

What you suggested was _new behaviour_. I like it, and am in favour of that new behaviour, but it is a different animal from _fixing existing behaviour_. The current broken behaviour prevents me from adding tests in #951, so I think there is a very strong case that this current, broken behaviour is making the code hard to maintain.

For the record, the entire "workaround" is this: `.project.str.endswith(project_path)` --> `project == project_path`. And what's more, this change will continue to work even after your suggested new behaviour removing `root_path` is implemented.

> I am going to implement this solution at some point, but I can not do it in the up-coming weeks as I am busy with other projects.

And until then, the code remains with a dangling bad fail state, and I can't write database-free tests for #951. My whole point is that we should fix known failures instead of knowingly leaving them in the code until we get to "at some point".
