### ISSUE TITLE
Pypi package broken 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron_base#1122]
For `0.5.40` only a `*.whl` file was published on pypi https://pypi.org/project/pyiron-base/#files while for all previous versions we published both the source files and the `*.whl` files https://pypi.org/project/pyiron-base/0.5.39/#files . Conda requires the source files: https://github.com/conda-forge/pyiron_base-feedstock/pull/156 So we should check how the deploy action changed and how we can adapt it to publish the source files as well.

**Comment by niklassiemer** [comment]
The PyPI API was broken while processing the new release and only the wheel was uploaded... How can we handle this issue? Create a new release which also uploads the source? Or is there any way to get the source in without changing the version number?

_Originally posted by @niklassiemer in https://github.com/conda-forge/pyiron_base-feedstock/pull/156#issuecomment-1578967899_

**Comment by jan-janssen** [comment]
Yes, I would suggest to remove the old release and make a new one for the next version `0.5.41`.

**Comment by jan-janssen** [comment]
It seems to be fixed now! In addition I might do one or two more releases this week as we plan to run a pyiron Exascale tutorial next Monday.
