### ISSUE TITLE
How to handle tables requirement?

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_base#113]
Whenever I create a new conda environment and use it in PyCharm, I inevitably get the complaint that `tables>=3.6.1` can't be found in my channels (conda-forge). When I google I'm pretty sure what we're looking for is [pytables](https://anaconda.org/anaconda/pytables), whose source code also correctly satisfies our usage: `from tables.exceptions import NoSuchNodeError, HDF5ExtError`.

Am I doing something wrong in my setup/misunderstanding something, or should we change the setup.py requirement `'tables>=3.6.1'` to `pytables>=3.6.1`?

**Comment by jan-janssen** [comment]
The pip packages is named `tables`: https://pypi.org/project/tables/ and the conda package is named `pytables` https://anaconda.org/conda-forge/pytables - when you use the conda environment file you should be fine https://github.com/pyiron/pyiron_base/blob/master/.ci_support/environment.yml

**Comment by liamhuber** [comment]
> The pip packages is named `tables`: https://pypi.org/project/tables/ and the conda package is named `pytables` https://anaconda.org/conda-forge/pytables 

🤦 Ok, no change on our end then. Ugh. I'll close.

> when you use the conda environment file you should be fine https://github.com/pyiron/pyiron_base/blob/master/.ci_support/environment.yml

Yeah, that's totally reasonable. In my workflow I use PyCharm to create a new conda env and could, in principle, point it at the environment.yml file at that point. After this I add content roots, and there it seems to be directly scraping the `setup.py` and I don't see an easy way to correct this behaviour. 

It's not a big deal, I just vainly hoped we could get away with renaming tables to pytables.
