### ISSUE TITLE
Instructions to install flux via conda are wrong

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_base#1135]
The [run function](https://github.com/pyiron/pyiron_base/blob/b6bf32078f06b0b316c5ecc421ea8aa46d99f466/pyiron_base/jobs/job/runfunction.py#L454) instructs me to do the following:

```python
def run_job_with_runmode_flux(job, executor, gpus_per_slot=None):
    if not flux_available:
        raise ModuleNotFoundError(
            "No module named 'flux'. No linux you can install flux via conda."
            + "'conda install -c conda-forge flux'"
        )
```

But when I tried this I discovered the package does not exist. Error message below, but I also confirmed it by going to the conda-forge page and searching for the package. I guess `flux-core` or `flux-sched` may be intended here, and will update if I make any progress.

from `conda install -c conda-forge flux`:

```
PackagesNotFoundError: The following packages are not available from current channels:

  - flux

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by liamhuber** [comment]
> I guess `flux-core` or `flux-sched` may be intended here, and will update if I make any progress.

Well, both of these are _exclusively_ for linux, so I hope that is not the intended message.

@jan-janssen please clarify.

**Comment by jan-janssen** [comment]
`flux-core` is sufficient for CPU based machines, for GPU support we need `flux-sched` still it is correct that both packages are only available on Linux.

**Comment by liamhuber** [comment]
> `flux-core` is sufficient for CPU based machines, for GPU support we need `flux-sched` still it is correct that both packages are only available on Linux.

(1) it is frustrating that the closest thing to documentation that exists for the flux executor is flat out wrong. I will patch the error message in a few minutes.

(2) If support is _only_ for linux, maybe we should not be so fast to dismiss dask over in [pyiron_contrib 718](https://github.com/pyiron/pyiron_contrib/pull/718#issuecomment-1594997452), eh? Because at least I have dask on my local machine.

> the missing pieces are now the storage interface and the integration with the graph based workflows.

E.g. it would to be awfully difficult for me to develop this part if the only supported non-local executor is one that won't run on my development machine

**Comment by jan-janssen** [comment]
> (2) If support is _only_ for linux, maybe we should not be so fast to dismiss dask over in [pyiron_contrib 718](https://github.com/pyiron/pyiron_contrib/pull/718#issuecomment-1594997452), eh? Because at least I have dask on my local machine.

In principle as long as it returns a python `concurrent.futures.Future` object like dask, flux, pympipool and many more, everything is fine from the task management perspective. We have been experimenting with dask for the last 3 years for example in https://github.com/pyiron/pylammpsmpi/issues/41 the fundamental limitation remains, dask is designed for serial python functions like they are typically used in machine learning and data science. There is no interest from the dask side to support the submission of MPI parallel tasks, the only MPI support they have is for spawning workers which then execute serial python tasks again. But for that use case we can also directly use `pympipool` which is based on `mpi4py` and again implements the same `concurrent.futures.Executor` interface.
