### ISSUE TITLE
table job of packed Project fails to load data

### ISSUE THREAD

**Issue by niklassiemer** [pyiron/pyiron_base#1137]
I just stubbled across an unintended behavior for table jobs which have been `pack`ed and are now tried to be loaded in completely different environment (e.g. binder) without access to the original analysis project (not even the path can be build..., which causes the error in my case). I suggest to check if the project paths exists before trying to make a `Project` there...

https://github.com/pyiron/pyiron_base/blob/0b6399ddad6ab4a734282b08ac8e024bebd973f4/pyiron_base/jobs/datamining.py#L684-L693

**Comment by pmrv** [comment]
Good catch!  Proposed solution a-ok with me, but see the PR about adding a warning or something similar.
