### ISSUE TITLE
Numpy update fails tests...what was intended?

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_base#1143]
There's a number of failures in #1140, but this one caught my eye:

```
======================================================================
ERROR: test_array_type_conversion (generic.test_fileHDFio.TestFileHDFio) [object_array_with_lists]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/pyiron_base/pyiron_base/tests/generic/test_fileHDFio.py", line 185, in test_array_type_conversion
TestWithProject: Setting up test project
TestWithProject: Setting up test project
    np.array_equal(array, object_array_with_lists)
  File "/usr/share/miniconda3/envs/my-env/lib/python3.10/site-packages/numpy/core/numeric.py", line 2439, in array_equal
    return bool(asarray(a1 == a2).all())
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

The relevant portion of the tests looks like this:

```python
    def test_array_type_conversion(self):
        object_array_with_lists = np.array(
            [[[1, 2, 3], [2, 3, 4]], [[4, 5, 6]]], dtype=object
        )
        int_array_as_objects_array = np.array([[1, 2, 3], [3, 4, 5]], dtype=object)
        float_array_as_objects_array = np.array(
            [[1.1, 1.3, 1.5], [2, 2.1, 2.2]], dtype=object
        )

        hdf = self.i_o_hdf5.open("arrays")

        hdf["object_array_with_lists"] = object_array_with_lists
        hdf["int_array_as_objects_array"] = int_array_as_objects_array
        hdf["float_array_as_objects_array"] = float_array_as_objects_array

        warn_msg_start = "WARNING:pyiron_log:Deprecated data structure! Returned array was converted "

        with self.subTest("object_array_with_lists"):
            array = hdf["object_array_with_lists"]
            np.array_equal(array, object_array_with_lists)
            self.assertIsInstance(array, np.ndarray)
            self.assertEqual(
                array.dtype,
                np.dtype(object),
                msg="dtype=object array falsely converted.",
            )
```

First, I am totally confused why this is only an issue on 1.25 and not 1.24.x. I dug into the numpy source and `array_equal` looks the same in [1.25](https://github.com/numpy/numpy/blob/c6e1fd039da2e6127ba0798f327e9e1b122d7534/numpy/core/numeric.py#L2377) and [1.24.3](https://github.com/numpy/numpy/blob/14bb214bca49b167abc375fa873466a811e62102/numpy/core/numeric.py#L2408), so I guess the change in behaviour upstream in `np.array(` or `==`...

Second, I'm not sure what is actually being tested for here? This is just a random bool, not a `self.assertTrue` or anything, what was the intent?

Digging in a bit, I find that both the in-process-defined `object_array_with_lists ` and the loaded-from-hdf `array` are of type `numpy.ndarray`. However, their content differs as the hdf-loaded one doesn't get its internal lists converted to numpy arrays. They are respectively:

```python
[
    array([[1, 2, 3], [2, 3, 4]]) 
    array([[4, 5, 6]])
]
```

and 

```python
[
    list([[1, 2, 3], [2, 3, 4]]) 
    list([[4, 5, 6]])
]
```

`np.array_equal` can handle raggedness as `np.array_equal(,)` passes ok, it only breaks when one (or both) of the tested "arrays" have `list` elements.

**Summary:**
- Is it intended that `array = hdf["object_array_with_lists"]` be recursively converting inner lists to arrays?
- Why did this work on 1.24.x?
- Should the `np.array_equal` not be inside a `self.assertTrue`?

The other failures are also related to hdf5 and datacontainers. I'll see if I can get any extra insight there.

**Comment by liamhuber** [comment]
Ah, I just remembered @niklassiemer's comments to the effect that he may not be able to get to this promptly.  @pmrv do you have any insight here?

**Comment by pmrv** [comment]
I'll have a look tomorrow.  I remember seeing the floating bool in #1133 and then not looking deeper into it.  Maybe the intent was to trigger a warning?

**Comment by liamhuber** [comment]
> I remember seeing the floating bool in https://github.com/pyiron/pyiron_base/pull/1133 and then not looking deeper into it. Maybe the intent was to trigger a warning?

[Here's the commit](https://github.com/pyiron/pyiron_base/commit/496bbe63757132edd8f79b976047da8cbca31d4e) and [here's the PR](https://github.com/pyiron/pyiron_base/pull/518). No discussion of the intent there. The PR was approved by me though, so I absolutely share the blame for a dangling bool being left around 😆 We'll just have to wait and see if @niklassiemer has any insight into what it's supposed to be doing.

**Comment by liamhuber** [comment]
> I'll have a look tomorrow.

Super. I'll try and dig into the remaining failures (warning counts are wrong) (#1144) tomorrow after updating my env tonight (I can't currently reproduce the failures...) but since your "tomorrow" comes before my "tomorrow", if you make any progress on that front please lmk!

**Comment by niklassiemer** [comment]
Just to the intent of the test, I added those upon discovery of the dtype=object error we had where all our arrays had been dtype=object... And I am quite sure, I simply forgot the actual test (assertTrue).
In these tests I tried to have different arrays with different, sometimes not-matching dtype and store and receive them from hdf.

**Comment by pmrv** [comment]
So the conversion of the sub lists doesn't happen in plain h5io, it's something that we add [here](https://github.com/pyiron/pyiron_base/blob/3e34d39353162a1403b379ff2f4e4e4990a82e11/pyiron_base/storage/hdfio.py#L261).  I suppose we could check there if the nested values are lists and then don't do the `asarray` conversion.   As to why this worked previously, I would guess that numpy does something like 

```python
all(i1 == i2 for i1, i2 in zip(array1, array2))
```

for `np.array_equal` and `dtype=object`. This would have issued a warning in 1.24, but now fails.

EDIT: In fact it does issue this warning: `/home/poul/micromamba/envs/pyiron_base/lib/python3.11/site-packages/numpy/core/numeric.py:2468: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.`

**Comment by jan-janssen** [comment]
Based on the fixes in https://github.com/pyiron/pyiron_base/pull/1147 I am going to close this issue.
