### ISSUE TITLE
Backwards compatibility test broken by development release on `pyiron_atomistics`

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron_base#1158]
Currently we get the following error message:
```
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [59 lines of output]
      /usr/share/miniconda3/envs/my-env/lib/python3.10/site-packages/setuptools/dist.py:510: SetuptoolsDeprecationWarning: Invalid version: '0.3.0.dev.0.post.dev11'.
      !!
      
              ********************************************************************************
              The version specified is not a valid version according to PEP 440.
              This may not work as expected with newer versions of
              setuptools, pip, and PyPI.
      
              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
      
              See https://peps.python.org/pep-0440/ for details.
              ********************************************************************************
      
      !!
```

To me this sounds like the version number generated by `versioneer` is confused by the development release. @srmnitc Can you take a look at this?

**Comment by srmnitc** [comment]
This seems to originate because versioneer creates the versions from the last tag. However, we need a tag with dev in it for the pre-release builds to work, this seems to me to be a bit of a loop. @jan-janssen if you have ideas it is most welcome.

**Comment by jan-janssen** [comment]
@srmnitc Can we use other tags? versioneer filters for `pyiron_atomistics-*` so maybe something like `dev_pyiron_atomistics-*` would work.

**Comment by niklassiemer** [comment]
I am not so sure, can we use a regex as prefix? If yes and conda-forge allows this this could solve the issue. I also asked at versioneer if it is in scope to support also a suffix...

**Comment by jan-janssen** [comment]
The integration tests are now fixed with https://github.com/pyiron/pyiron_base/pull/1637
