### ISSUE TITLE
Pyiron tables: Backwards compatibility broken again by #796

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_base#1163]
By moving the modules around without providing backwards compatibility #796 broke the loading of pyiron tables created before that change.  That PR contained a [stop gap](https://github.com/pyiron/pyiron_base/blob/d2d9b1b49e1b2dde1305ce8b3a982e5244eb4ba5/pyiron_base/storage/hdfio.py#L1378) which remaps a few class paths, but the issue runs deeper for functions that are `dill`ed or `pickle`ed, because those libraries also write the import paths and we have no way of intercepting them.

The workaround is a finger of scotch and putting this bespoke line in your notebooks before you start loading the old tables.

```python
sys.modules['pyiron_base.table.datamining'] = sys.modules['pyiron_base.jobs.datamining']
```

**Comment by jan-janssen** [comment]
@pmrv As far as I understand this was fixed with https://github.com/pyiron/pyiron_base/pull/1243 correct? If that is the case I guess we can close this pull request.
