### ISSUE TITLE
Pulling out super small modules?

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_base#1208]
So for `pyiron_workflow` I was looking at what my `pyiron_base` dependencies actually are, and it's really just `Singleton` and `logger`.

When it comes to extracting re-usable packages, how small should we go? For instance, singleton's are actually pretty useful, but when I looked on conda-forge for "singleton" there is really [not](https://anaconda.org/conda-forge/singleton-decorator) a [lot](https://anaconda.org/conda-forge/celery-singleton) there. The implementation as a decorator is alright, but (a) I like our metaclass paradigm better, and (b) the code hasn't been touched forever so there's minor things like the CI [stopping at py3.6](https://github.com/Kemaweyan/singleton_decorator/blob/master/.travis.yml).

Does anyone have opinions on pulling `Singleton` (and maybe other stuff?) out as ultra-tiny package(s)?

**Comment by jan-janssen** [comment]
An alternative would be to create one package for commonly used utilities like the https://github.com/materialsvirtuallab/monty package from the materials project.

**Comment by liamhuber** [comment]
Yes, that might be really nice. It might be nice to collect all the tools and tidbits that, eg, depend exclusively on the standard library. Then they could be added to literally any project with almost zero overhead.

**Comment by liamhuber** [comment]
As of the meeting today we decided that this is a fine idea. Any bits of pieces of pyiron that
- Depend _only_ on the standard library
- Get used (or want to get used right now!) in at least two other pyiron repos

Can get pulled out into a special pyiron utils repo. I'll take care of this eventually, starting with the base logger and singleton code.

**Comment by jan-janssen** [comment]
These parts are now available in https://github.com/pyiron/pyiron_snippets so I am going to close this issue.
