### ISSUE TITLE
Relying on pyiron in GenericJob create_job

### ISSUE THREAD

**Issue by niklassiemer** [pyiron/pyiron_base#128]
In the `create_job` method of `GenericJob` in pyiron_base we use a reference to pyiron:
https://github.com/pyiron/pyiron_base/blob/9fce7ef80c9e58a2a4e109ced403c3c371d7c292/pyiron_base/job/generic.py#L1050

**Comment by jan-janssen** [comment]
I guess we should have a `InteractiveWrapper` in `pyiron_base` and then derive the class in `pyiron_atomistics` from the one in `pyiron_base`.
