### ISSUE TITLE
Unsightly polymorphism in job.create_job()

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_base#131]
When creating jobs from other jobs, some job types require special treatment as shown here

https://github.com/pyiron/pyiron_base/blob/6b78c6fc3899b397f0a1735e4fe272ca9bf7e4cf/pyiron_base/job/generic.py#L1032

It's a bit weird, because `pyiron_base` needs to know about job types not defined there.  This could be done more cleanly by adding an method to `GenericJob` that is called only after is created as a child job and then overriding this method in the classes currently special cased.

If there's no objections, I'll make PR for that, but I might have missed something.

**Comment by jan-janssen** [comment]
I guess you should be able to handle both cases inside pyironbase now that we have the interactive wrapper migrated.

**Comment by pmrv** [comment]
True, that makes it a bit easier.
