### ISSUE TITLE
New release -- patch or minor

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_base#1339]
@pmrv and @jan-janssen, you made all the PRs since the last release, should we be getting patch or minor? The next release holds up my downstream CI, so it is not an emergency but I would appreciate the release.

**Comment by pmrv** [comment]
I guess the new `files` feature and some new deprecations would make it minor.

**Comment by liamhuber** [comment]
Wait, @pmrv, I think the `files` stuff was already released? I should have done this in the original post, but here's the new PRs:


* Test old monty version by @jan-janssen in https://github.com/pyiron/pyiron_base/pull/1330
* get_jobs() filter for columns directly by @jan-janssen in https://github.com/pyiron/pyiron_base/pull/1325
* Refactor database interface by @jan-janssen in https://github.com/pyiron/pyiron_base/pull/1331
* Refactor database interface by @jan-janssen in https://github.com/pyiron/pyiron_base/pull/1332
* remove unnecessary database queries by @XzzX in https://github.com/pyiron/pyiron_base/pull/1324
* Fix regression on #1188 by @pmrv in https://github.com/pyiron/pyiron_base/pull/1336
* Clean traceback when trying to import a moved module by @pmrv in https://github.com/pyiron/pyiron_base/pull/1333
* Do not fail hdf type update if project data missing by @pmrv in https://github.com/pyiron/pyiron_base/pull/1337
* Update h5io_browser to 0.0.9 by @jan-janssen in https://github.com/pyiron/pyiron_base/pull/1338

**Comment by pmrv** [comment]
Ah, seems I've scrolled too far.  patch is fine then.

**Comment by liamhuber** [comment]
Ok, thanks for the quick reply. Unfortunately it's the less helpful one `minor_bump := jan_needs_minor || marvin_needs_minor` 😜

**Comment by jan-janssen** [comment]
Done in https://github.com/pyiron/pyiron_base/releases/tag/pyiron_base-0.7.8
