### ISSUE TITLE
ProjectHDFio fails to open other Projects than it's direct parent

### ISSUE THREAD

**Issue by niklassiemer** [pyiron/pyiron_base#134]
The `ProjectHDFio` is not able to open a standard pyiron Project other than it's parent project. Code to reproduce:
```
from pyiron_base import Project
pr=Project('test')
hdf=pr.create_hdf(pr.path,'test')
pr2=hdf['../..']
pr2.path == pr.path
```

I traced this down to the `__getitem__` of  the `FileHDFio`:
https://github.com/pyiron/pyiron_base/blob/74fc5115d6cbd1554f1cd4401ac9976921a487a9/pyiron_base/generic/hdfio.py#L834-L846

The `os.path.normpath('/hdf_root/../../')` returns '/'  since there is no directory super to root, thus `item_abs_list` will never be longer than 2.

**Comment by jan-janssen** [comment]
> The `os.path.normpath('/hdf_root/../../')` returns '/' since there is no directory super to root, thus `item_abs_list` will never be longer than 2.

I missed this part, can you fix it? In addition it would be good to have a unit test to continue checking this in future.

**Comment by niklassiemer** [comment]
Sure, I will start a PR soon.
