### ISSUE TITLE
How to use DataContainer in inspect mode? 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron_base#1354]
When a job is loaded using `pr.inspect()` then the corresponding `DataContainer` objects are not loaded. In particular, in the case of pyiron tables which by default use the inspect mode, this becomes an issue.

**Comment by pmrv** [comment]
See #364 and in particular https://github.com/pyiron/pyiron_base/issues/364#issuecomment-1403760357

**Comment by pmrv** [comment]
A quick workaround is to use something like this in a table function
```python
dc = job['location/of/datacontainer'].to_object()
dc['my/fancy/values']
```

The containers are lazy loaded by default, so the overhead should be small.

**Comment by pmrv** [comment]
By now it's also possible to do

```python
dc = job.content['location/of/datacontainer']
dc['my/fancy/values']
```
