### ISSUE TITLE
Tables broken with default executor

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_base#1362]
```python
tab = pr.create.table(...)
tab.add[...] = ...
tab.server.cores = 4
tab.run()
```

currently breaks, because by default the plain process pool is used.

https://github.com/pyiron/pyiron_base/blob/dec8f0931be9b289ba87ed1bf34f1caaa9b6a9c4/pyiron_base/jobs/datamining.py#L787

Since all pyiron tables use lambdas to wrap the user defined functions, this gives a pickle error.

I suppose using an executor from `pympipool` would fix this, but I couldn't check yet.

**Comment by jan-janssen** [comment]
> I suppose using an executor from `pympipool` would fix this, but I couldn't check yet.

Yes, the `pympipool` executor works fine - this is already covered in the unit tests: 
https://github.com/pyiron/pyiron_base/blob/main/tests/table/test_datamining.py#L80
