### ISSUE TITLE
For MPIE-CM users: Having a default version of pyiron_base on cmmc

### ISSUE THREAD

**Issue by sudarsan-surendralal** [pyiron/pyiron_base#14]
I just realized that we can't run the master version of pyiron unless we have checked out our own `pyiron_base` version. Can we create a default one like the other repos that get loaded when one types `module load pyiron/dev`?

**Comment by jan-janssen** [comment]
Done - Can you confirm it is working now?

**Comment by sudarsan-surendralal** [comment]
Yes it works. To check, I typed the following lines

```
import pyiron_base

print(pyiron_base.__file__)
```
