### ISSUE TITLE
Why does create_job live on `GenericJob` and not `GenericMaster`?

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_base#140]
As far as I can grep `job.create_job` is only ever called on instances of `GenericMaster`.  Is there a reason why you would want to do that in a notebook that I'm missing?  If not I'll move the method to `GenericMaster`.

**Comment by jan-janssen** [comment]
The restart of a calculation for example to calculate the band structure would be an example of two jobs which are directly linked without any master.

**Comment by pmrv** [comment]
Ah, fair, completely missed `job.restart()`.
