### ISSUE TITLE
Flattened storage extend cutting off str

### ISSUE THREAD

**Issue by Leimeroth** [pyiron/pyiron_base#1407]
When using the extend method of a FlattenedStorage identifier str values in the extend array are cut of after a len of 20 due to the way the FlattenedStorage initializes it with len 20 .
```
"identifier": np.empty(self._num_chunks_alloc, dtype=np.dtype("U20")),
```
 @pmrv do you have an idea how to check for this?

**Comment by pmrv** [comment]
There should be some logic already in the setters that widens string arrays. Maybe we can just pull that out and use in the extend as well.

EDIT: Ah, it's already it's own [method](https://github.com/pyiron/pyiron_base/blob/25ca798bdd3c906a6f27a10c6e767372ccde36b6/pyiron_base/storage/flattenedstorage.py#L32).
