### ISSUE TITLE
binder environments cannot be built with jupyterlab>4.1.6

### ISSUE THREAD

**Issue by srmnitc** [pyiron/pyiron_base#1427]
If jupyterlab>4.1.6 and pyiron-base are present in the environment file, mybinder instances do not wrong. The build happens without issues, but the container notebook is not started. For an example, see [this repo](https://github.com/srmnitc/binder-pyiron-jupyeterlab). Fixing jupyterlab to 4.1.6 fixes the issue.

**Comment by srmnitc** [comment]
Log from binder run: 
[binderrun.log](https://github.com/pyiron/pyiron_base/files/15240839/binderrun.log)

**Comment by jan-janssen** [comment]
When I look at your logs, then you first install:
```
jupyterlab                3.6.6              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.25.0             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.9              pyhd8ed1ab_0    conda-forge
```
and afterwards: 
```
jupyterlab                4.2.0              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.25.0             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.9              pyhd8ed1ab_0    conda-forge
```
Does the same happen when you remove `jupyterlab` from the `environment.yml` file? Or is there a specific reason to change it? I think when `3.6.6` is installed by default then it makes sense that it breaks at a certain point. I did not know that it's `4.1.6` but that sounds reasonable.

**Comment by jan-janssen** [comment]
I just tested `pyiron_base` and everything seems to be fine [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/pyiron/pyiron_base/HEAD) . In the same way `pyiron_atomistics` seems to work now [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/pyiron/pyiron_atomistics/HEAD) .  So I am going to close this issue. If it comes up again in the future, feel free to open it again.
