### ISSUE TITLE
Demo notebooks are execution order dependent

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_base#1431]
You need to execute `export_example.ipynb` before executing `import_example.ipynb`, or the latter will look for a file that does not exist. IMO each demo notebook should be fully independent.

https://github.com/pyiron/pyiron_base/pull/1429#issuecomment-2110657069

**Comment by samwaseda** [comment]
It's actually not only order dependent, but also there's absolutely no context in both notebooks, especially no explanation whatsoever. I did a small quite minimalistic change [here](https://github.com/pyiron/pyiron_base/pull/1443)

**Comment by liamhuber** [comment]
Super, thanks @samwaseda!
