### ISSUE TITLE
`test_import.py` cannot run twice

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_base#1444]
[test_import.py](https://github.com/pyiron/pyiron_base/blob/main/tests/archiving/test_import.py) cannot run twice because somehow pyiron fails to delete jobs in the first run when the tests finish. In the second run these remaining jobs from the first run apparently make a problem.

**Comment by samwaseda** [comment]
It looks like there are multiple entries created when the jobs are imported with the same job name. ~~On top of this, it looks like the job has itself as a child job, so that when it tries to delete the child job, it cannot identify the job.~~

**Comment by samwaseda** [comment]
So I'm not getting any comment here but I'm gonna keep posting my findings to use it as my log book.

- The problem does not occur with the newly updated [import and export example](https://github.com/pyiron/pyiron_base/blob/main/notebooks/import_export_example.ipynb). That's a good sign.
- Also, when each test is executed individually, there's no error/problem
- Based on this, I thought moving everything from setUpClass to setUp (same for tearDownClass) could solve the problem, but this created other problems.

**Comment by pmrv** [comment]
Ah, I remember this issue when running tests locally.  It might have been that the project that the test imports into is not the same as the one that gets cleared after the test, but I'm not sure anymore and I never quite fixed it.

**Comment by liamhuber** [comment]
> Ah, I remember this issue when running tests locally. It might have been that the project that the test imports into is not the same as the one that gets cleared after the test, but I'm not sure anymore and I never quite fixed it.

Ditto. I even still have a `fix_archive_tests` branch on my local repo that I'm pretty sure was trying to address exactly this, but I got frustrated and quit before I got it solved.

**Comment by samwaseda** [comment]
Yeah it's super frustrating, especially the errors are really not helpful.

I kept digging down, and now I got the feeling that there's a problem with nested projects. It occurs namely even when there are only these two tests: `test_unpack_to_nested_project` and `test_unpack_from_other_dir_uncompress`, but somehow if each of them is run individually the problem does not occur.

**Comment by samwaseda** [comment]
It looks like the opposite is also the case: if I run all tests except for these two, they pass as well.

**Comment by samwaseda** [comment]
Interestingly, there’s also no problem if only one of them is disabled. So probably something in `tearDownClass` prevents the problem.
