### ISSUE TITLE
Removing jobs takes absurd amount of time

### ISSUE THREAD

**Issue by caglayanoaras** [pyiron/pyiron_base#152]
**Summary**
remove_jobs_silently(recursive=True) method takes too much time. I am not an expert in the field but I believe deleting jobs recursively one by one is not the best algorithm.
**Detailed Description**
I did some dummy tests to see the pattern. Figures below show the number of phonopy jobs and calc_minimize jobs in a project and the time it took to delete the project.
![1](https://user-images.githubusercontent.com/56139345/100401007-844fa700-3058-11eb-9a3b-8103980b888f.PNG)
![2](https://user-images.githubusercontent.com/56139345/100401089-c973d900-3058-11eb-9f07-165d9df040fc.PNG)

I do not think that this is super critical but I wanted to open an issue because as the number of dimensions increase, job numbers might increase a lot. For instance, in my case I have around 6000 jobs an it takes around 75 minutes to delete the project.

I also have a question. Since there is some sql db working in the background, I do not delete the files directly. But I do not know if it will make a problem. What will happen if I directly delete the project folder?

**Comment by pmrv** [comment]
This came up again for me, so I've collected a profile, but I don't have time right now to dig into it.

Looking superficially at it, it seems were spending
- ~20% opening HDF5 files
- ~50% talking to the database
- only ~10% actually removing files

[remove_profiles.zip](https://github.com/pyiron/pyiron_base/files/6961418/remove_profiles.zip)

**Comment by jan-janssen** [comment]
One thing I typically do is: 
```
df = pr.job_table()
for job_id in df[np.isnan(df.masterid)].id.values[::-1]:
    pr.remove_job(job_id)
```
This is already faster than `pr.remove_jobs(recursive=True, silently=True)`

**Comment by jan-janssen** [comment]
The ugly direct deletion code:
```
df = pr.job_table()
for job_id, project_path, project, job in zip(df.id, df.projectpath, df.project, df.job):
    pr.db.delete_item(item_id=job_id)
    shutil.rmtree(os.path.join(project_path, project, job + "_hdf5"))
    # shutil.rmtree(os.path.dirname(pr.inspect(job_id).working_directory))
```

**Comment by samwaseda** [comment]
Discussed in #844
