### ISSUE TITLE
How to use `move_to`

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_base#154]
So in short, [this solution](https://stackoverflow.com/questions/65897074/in-pyiron-how-to-move-some-jobs-to-a-different-project) for `move_to` is not working for me. I tried a few possibilities:

```
pr = Project('PROJECT')
pr_test = pr.create_group('TEST')

job = pr.load(job_name)

# None of the possibilities below worked
job.move_to('TEST')
job.move_to('PROJECT/TEST')
job.move_to(pr_test.path)
job.move_to(pr_test)
```

But then I realized that the comparison in the following line might have a problem, since now the project itself is from `pyiron_base` and `job.project` is `pyiron_atomistics`?

https://github.com/pyiron/pyiron_base/blob/c290751742bb03f2503121f4464357249cda2fe3/pyiron_base/job/util.py#L94

**Comment by jan-janssen** [comment]
How do you import the project?

**Comment by samwaseda** [comment]
`from pyiron_atomistics import Project`

**Comment by niklassiemer** [comment]
Then you should actually have an atomistic project. If you load a job into an atomistic project, then the `job.project` should be this atomistic project.

**Comment by jan-janssen** [comment]
This should not be an issue: 

```
from pyiron_base import Project as ProjectBase
from pyiron_atomistics import Project as ProjectAtom
pr = ProjectAtom(".")
print(isinstance(pr, ProjectBase))
```
The lines above return true for me.

**Comment by samwaseda** [comment]
Well but then my initial problem (use `move_to` to move the job to a new location) wouldn't be solved ... ?

**Comment by niklassiemer** [comment]
@jan-janssen All our `Project` classes should return `True` for `isinstance(pr, ProjectBase)` since `isinstance` also allows for derived classes.

**Comment by jan-janssen** [comment]
> Well but then my initial problem (use `move_to` to move the job to a new location) wouldn't be solved ... ?

For me:
```
job.move_to(pr_test)
```
works just fine, but only the HDF5 file is moved while the `*.tar.gz` archive is removed.

**Comment by samwaseda** [comment]
> > Well but then my initial problem (use `move_to` to move the job to a new location) wouldn't be solved ... ?
> 
> For me:
> 
> ```
> job.move_to(pr_test)
> ```
> 
> works just fine, but only the HDF5 file is moved while the `*.tar.gz` archive is removed.

Oh I just updated my branches and did the same and it worked... I don't think my branch was particularly old so I guess it was related to a recent change? Anyway I don't know how important the compressed files are, but since this serves my purpose I close this issue. Thank you very much for your replies!

**Comment by niklassiemer** [comment]
For me this worked as well, however, I am a bit confused by the Docstring `job.move_to.__doc__`:
```
        Move the content of the job including the HDF5 file to a new location

        Args:
            project (ProjectHDFio): project to move the job to

        Returns:
            JobCore: JobCore object pointing to the new location.
```
since we provide a normal `Project` here.

**Comment by samwaseda** [comment]
> For me this worked as well, however, I am a bit confused by the Docstring `job.move_to.__doc__`:
> 
> ```
>         Move the content of the job including the HDF5 file to a new location
> 
>         Args:
>             project (ProjectHDFio): project to move the job to
> 
>         Returns:
>             JobCore: JobCore object pointing to the new location.
> ```
> 
> since we provide a normal `Project` here.

I guess Docstrings are really not our strength so far. Whenever you see a problem, feel free to edit it.
