### ISSUE TITLE
error in `pyiron mv`

### ISSUE THREAD

**Issue by XzzX** [pyiron/pyiron_base#1614]
It seems like `from pyiron_base import Project` cannot move a project created with `pyiron_atomistics`. Is this intentional? Is there a way to make it generally working.

Reproducer, a projected created with:
```
from pyiron_atomistics import Project
pr = Project("src")
pr.remove_jobs(recursive=True, silently=True)
for i in range(10): 
    job = pr.create.job.Lammps("lmp_" + str(i))
    job.structure = pr.create.structure.ase.bulk("Al", cubic=True)
    job.potential = '2009--Mendelev-M-I--Al-Mg--LAMMPS--ipr1'
    job.server.run_mode.interactive = True 
    job.run()
    job.interactive_close()
```
cannot be moved with `pyiron mv src dst`.
Error:
```
pyiron_base/jobs/job/util.py", line 112, in _get_project_for_copy
    raise ValueError("Project should be JobCore/ProjectHDFio/Project/None")
```

**Comment by pmrv** [comment]
Is this with pyiron_base==0.10.0?  If so, likely connected to #1531, we are looking into a fix.  @jan-janssen Maybe it does make sense to yank the conda package for now?
