### ISSUE TITLE
ScriptJob example?

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_base#170]
I was hoping to show @vijjubhuva how to submit entire notebooks, but am having trouble finding documentation for this. Critically, when I try to load the `submit_job.ipynb` from our [mpie handbook page](https://github.com/pyiron/pyiron-meeting-mpie/tree/03a465ca112b8fed0436565bf4c38d2dd86b5c7a/handbook/6-file-and-job-management/6-6-submit-jupyter-notebook) I get an error loading the file. I'm not able to find an example of this elsewhere, am I simply missing it?

Would someone who is familiar with the operation of `ScriptJob` be willing to go into [its docstring](https://github.com/pyiron/pyiron_base/blob/fe177f23926d8405a00590d77a60b76cf54ddbf1/pyiron_base/job/script.py#L27) and give it some modernization, i.e. cleaning up/reformatting the attributes and providing one or two very simple examples of operation? @raynol-dsouza @samwaseda, have either of you or a student you work with got sufficient familiarity to make this task straightforward?

**Comment by raynol-dsouza** [comment]
I have a job submit script which looks like the following:

```
from pyiron.project import Project

pr = Project('.') 
pr.remove_jobs(recursive=True)

job = pr.create_job(pr.job_type.ScriptJob, 'qha')
job.script_path = 'qha.ipynb'
job.server.queue = 's_cmfe'
job.server.cores = 40
job.run()
```
which I think is the same as `submit_job.ipynb` with a few more inputs. My script was last executed in November 2019.

**Comment by liamhuber** [comment]
That sounds good. Could you convert that to a more generic example, double check that the example works, and add it to the docstring? It would probably also be good to show the contents of the submit script; this can be something simple and silly like calculating the numbers in the fibonacci sequence in a naive way.
