### ISSUE TITLE
Master job modal and child job interactive?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_base#19]
https://github.com/pyiron/pyiron_base/blob/514a521701709577999cc2d0f4bf332b40961c7d/pyiron_base/master/parallel.py#L668

I realized that it collapses when the master job is `modal` and the child job is `interactive`. Is there a particular reason that it shouldn't work?

**Comment by jan-janssen** [comment]
No I guess it should be the same as https://github.com/pyiron/pyiron_base/blob/master/pyiron_base/master/parallel.py#L691 Can you add it there? When you use `job.create_job()` it should automatically set the master to interactive as well. Still I have the feeling the interactive mode for masters is not really necessary so I agree the current implementation is a bit confusing.
