### ISSUE TITLE
Read-Only InputList

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_base#21]
I was just adding the `read_only` property to InputList also for feature parity, but I saw that for GenericParameters this will only cause a warning to be emitted.  I imagined it more to raise an Exception to avoid any kind of data-loss. Which way do we want to have?  I'm not partial either way and could build it both ways.

**Comment by jan-janssen** [comment]
The issue is that users might have multiple commands combines, like setting up `calc_md` and afterwards further fine tuning the Lammps parameters. In this case if the user executes the same notebook again to reload the job it complains when calling the `calc_md` part, but does not update the content. Therefore executing those notebooks works just fine.

**Comment by pmrv** [comment]
`GenericParameters` only raises the warning and then still allows to change the parameters, that's why I'm asking.

https://github.com/pyiron/pyiron_base/blob/28e26d394b96f26bea2e3a64eed64ed83a406b07/pyiron_base/generic/parameters.py#L283

I'm fine with keeping that behavior, just want to double-check.  Not breaking on just re-running the notebook is fair, but maybe it's possible to only raise the Exception/Warning if the new value being set is different from the old value.

**Comment by jan-janssen** [comment]
Yes, the issue are lines like:
```
        job_md.calc_md(temperature=temperature, pressure=[0.0, 0.0, 0.0], n_print=100, n_ionic_steps=100000)
        job_md.input.control["fix___ensemble"] = " ".join(job_md.input.control["fix___ensemble"].split()[0:6]) + " iso 0.0 0.0 1.0"
```
Used in https://github.com/jan-janssen/NiCr-pyiron-example/blob/master/phasediagram_from_md.ipynb
The second line potentially only works when the first like did the wrong modification.

**Comment by pmrv** [comment]
I see, I'll keep the current behavior then.
