### ISSUE TITLE
20 character limit for job type causing DB error

### ISSUE THREAD

**Issue by raynol-dsouza** [pyiron/pyiron_base#232]
All the protocol jobs started throwing a DB related error during job submission (on the head node) which looks like this:

```
During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-6-6cf202eba93f> in <module>
     39     # fts_job.format_whitelist()
     40 
---> 41     fts_job.run()

~/pyiron_repos/pyiron_contrib/pyiron_contrib/protocol/generic.py in run(self, delete_existing_job, repair, debug, run_mode, continue_run)
    650             self.status.created = True
    651         super(CompoundVertex, self).run(delete_existing_job=delete_existing_job, repair=repair, debug=debug,
--> 652                                         run_mode=run_mode)
    653 
    654     def collect_output(self):

~/pyiron_repos/pyiron_base/pyiron_base/generic/util.py in decorated(*args, **kwargs)
    211                         stacklevel=2
    212                     )
--> 213             return function(*args, **kwargs)
    214         return decorated
    215 

~/pyiron_repos/pyiron_base/pyiron_base/job/generic.py in run(self, delete_existing_job, repair, debug, run_mode, run_again)
    667                 self._run_if_repair()
    668             elif status == "initialized":
--> 669                 self._run_if_new(debug=debug)
    670             elif status == "created":
    671                 self._run_if_created()

~/pyiron_repos/pyiron_base/pyiron_base/job/generic.py in _run_if_new(self, debug)
   1327             print("job exists already and therefore was not created!")
   1328         else:
-> 1329             self.save()
   1330             self.run()
   1331 

~/pyiron_repos/pyiron_base/pyiron_base/job/generic.py in save(self)
   1174         """
   1175         self.to_hdf()
-> 1176         job_id = self.project.db.add_item_dict(self.db_entry())
   1177         self._job_id = job_id
   1178         self.refresh_job_status()

~/pyiron_repos/pyiron_base/pyiron_base/database/generic.py in add_item_dict(self, par_dict)
    411                 return result
    412             except Exception as except_msg:
--> 413                 raise ValueError("Error occurred: " + str(except_msg))
    414         else:
    415             raise PermissionError("Not avilable in viewer mode.")

ValueError: Error occurred: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(20)

[SQL: INSERT INTO jobs_cmmc (parentid, masterid, projectpath, project, job, subjob, status, hamilton, hamversion, username, computer, timestart) VALUES (%(parentid)s, %(masterid)s, %(projectpath)s, %(project)s, %(job)s, %(subjob)s, %(status)s, %(hamilton)s, %(hamversion)s, %(username)s, %(computer)s, %(timestart)s) RETURNING jobs_cmmc.id]
[parameters: {'parentid': None, 'masterid': None, 'projectpath': '/cmmc/u/', 'project': 'rads/PyIron_data/projects/tests/protocol_fts_test_3/relax/25_0/', 'job': 'fts_', 'subjob': '/fts_', 'status': 'initialized', 'hamilton': 'ProtocolFTSEvolutionParallel', 'hamversion': '0.4', 'username': 'rads', 'computer': 'rads@cmti001#1', 'timestart': datetime.datetime(2021, 3, 11, 12, 11, 43, 807672)}]
(Background on this error at: http://sqlalche.me/e/13/9h9h)
```

I ran `git bisect` and isolated the following commit which supposedly introduces this bug:

```
Author: Marvin Poul <ponder@creshal.de>
Date:   Thu Feb 25 12:14:54 2021 +0100

    Set job class name from type(self), so sub classes don't have to

 pyiron_base/job/generic.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

@pmrv, will it cause any issues if we roll back this commit?

**Comment by pmrv** [comment]
It seems the problem is that we only allow job names LEDs then twenty characters in DB, but the protocol names are longer. This also implies that the job name of the protocols in DB so far didn't match up with their actual ones, so that sounds like a latent bug to me.  I'm not opposed to rolling back for a quick fix, but we should either allow longer names in the DB or update the protocol names to fit.

@liamhuber @jan-janssen Any opinions?

**Comment by raynol-dsouza** [comment]
It might just be easier to rename the protocols so that they fit the character count. Like renaming `'ProtocolFTSEvolutionParallel'` to `'FTSEvoPar'` maybe?

**Comment by jan-janssen** [comment]
As @pmrv correctly pointed out the length of the job type in the database is limited to 20 characters https://github.com/pyiron/pyiron_base/blob/master/pyiron_base/database/generic.py#L118 we can change that to 50 but this would also require the database in Garching to be updated and I am not sure if we really need more than 20 characters to describe the type of a job. Maybe a name like `ProFTSEvoParallel` would also be fine.

**Comment by liamhuber** [comment]
@raynol-dsouza, how do the protocol types appear in `pr.job_table()`?

**Comment by raynol-dsouza** [comment]
@liamhuber before this commit the protocol type would appear as `'GenericJob'`. Presently, it appears as `'ProtocolFTSEvolutionParallel'`, which is consistent with the commit.

**Comment by liamhuber** [comment]
>  I am not sure if we really need more than 20 characters to describe the type of a job. 

Ok, once the potentials workshop is finished we need to sit and have a serious think about this. From my perspective we will 100% need more freedom in listing job names. Especially job names will probably start needing to contain paths, e.g. `atomistics.protocol.FTSEvo`.

Consider back to our last tech dev meeting -- Joerg wants all data objects fully pyironized. That means our already large number of "jobs" is going to balloon. In this context something like a 20-character limit becomes very silly. I don't have a perfect solution planned out or anything, but obviously we need to make some change from the current situation.

**Comment by liamhuber** [comment]
> @liamhuber before this commit the protocol type would appear as `'GenericJob'`. Presently, it appears as `'ProtocolFTSEvolutionParallel'`, which is consistent with the commit.

Riiiight, of course. Because we (*cough*I*cough*) were lazy and never overwrote the `.__name__` attribute or something like this, and now @pmrv made a patch to accommodate my (and others) laziness 😉 So now we discover that we're too verbose in this name.

Ideally I would like some combination of:
- Better database behaviour, i.e. no silly 20 character limit
- A bit less verbosity on our end. Better saying too much than too little, but I'm sure we can come up with something informative but shorter than `ProtocolFTSEvolutionParallel`.

**Comment by raynol-dsouza** [comment]
> A bit less verbosity on our end. Better saying too much than too little, but I'm sure we can come up with something informative but shorter than `ProtocolFTSEvolutionParallel`.

For the time being, how about removing the 'Protocol' part off of all protocol jobs? That way I believe all job types will have <= 20 characters. For ex. `'FTSEvolutionParallel'`. I'm not sure if the quotation marks also count in the 20 char limit, though.

**Comment by jan-janssen** [comment]
> * Better database behaviour, i.e. no silly 20 character limit

For SQL any column has a fixed length for performance reason. We could increase it to 50 if required.

**Comment by liamhuber** [comment]
I don't think we should arbitrarily increase it to something, I think we need to sit down and brainstorm use cases and figure out what a useful format is for this field and how long it's likely to wind up being once pyiron is used in multiple fields. 50 sounds like lots and I think it's probably enough, but let's stop and think about it so we don't get stuck changing course again in six months.

**Comment by max-hassani** [comment]
I have updated the character limit to 50 for both chemical formula and hamilton in the our database. I guess this issue would be solved with this update.
