### ISSUE TITLE
Broken Database

### ISSUE THREAD

**Issue by Leimeroth** [pyiron/pyiron_base#258]
After updating conda packages and pyiron versions this morning I get an error related to the database that prevents me from doing anything with pyiron (Can't run jobs, load old ones, etc.). I checked if this is caused by a corrupted db file, but it occurs on different machines, so this is not the root of this issue as far as I can tell.

## Error message:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-1-baa9ac1a27fb> in <module>
      3 job = pr.create_job("Lammps", "TestJob")
      4 job.structure = pr.create_ase_bulk("Cu", cubic=True)
----> 5 job.run()

~/git_projects/pyiron_base/pyiron_base/generic/util.py in decorated(*args, **kwargs)
    211                         stacklevel=2
    212                     )
--> 213             return function(*args, **kwargs)
    214         return decorated
    215 

~/git_projects/pyiron_base/pyiron_base/job/generic.py in run(self, delete_existing_job, repair, debug, run_mode, run_again)
    685                 self._run_if_finished(delete_existing_job=delete_existing_job)
    686         except Exception:
--> 687             self.drop_status_to_aborted()
    688             raise
    689         except KeyboardInterrupt:

~/git_projects/pyiron_base/pyiron_base/job/generic.py in drop_status_to_aborted(self)
   1293         Change the job status to aborted when the job was intercepted.
   1294         """
-> 1295         self.refresh_job_status()
   1296         if not (self.status.finished or self.status.suspended):
   1297             self.status.aborted = True

~/git_projects/pyiron_base/pyiron_base/job/generic.py in refresh_job_status(self)
    431         if self.job_id:
    432             self._status = JobStatus(
--> 433                 initial_status=self.project.db.get_job_status(self.job_id),
    434                 db=self.project.db,
    435                 job_id=self.job_id,

~/git_projects/pyiron_base/pyiron_base/database/generic.py in get_job_status(self, job_id)
    688     def get_job_status(self, job_id):
    689         try:
--> 690             return self.get_item_by_id(item_id=job_id)["status"]
    691         except KeyError:
    692             return None

~/git_projects/pyiron_base/pyiron_base/database/generic.py in get_item_by_id(self, item_id)
    560         if np.issubdtype(type(item_id), np.integer):
    561             try:
--> 562                 return self.__get_items("id", int(item_id))[-1]
    563             except TypeError as except_msg:
    564                 raise TypeError(

~/git_projects/pyiron_base/pyiron_base/database/generic.py in __get_items(self, col_name, var)
    463         if not self._keep_connection:
    464             self.conn.close()
--> 465         return [dict(zip(col.keys(), col._mapping.values())) for col in row]
    466 
    467     def item_update(self, par_dict, item_id):

~/git_projects/pyiron_base/pyiron_base/database/generic.py in <listcomp>(.0)
    463         if not self._keep_connection:
    464             self.conn.close()
--> 465         return [dict(zip(col.keys(), col._mapping.values())) for col in row]
    466 
    467     def item_update(self, par_dict, item_id):

AttributeError: Could not locate column in row for column '_mapping'
```

## Steps to reproduce:
Try running pr.job_table() or create a new job and try to run it.

**Comment by jan-janssen** [comment]
We recently switched to `sqlalchemy` 1.4.0 - so can you check which version of `sqlalchemy` you are using? 
```
conda list sqlalchemy
```
And update to >1.4.0 if you are still using an older version. 

https://github.com/pyiron/pyiron_base/pull/236
https://github.com/pyiron/pyiron_base/pull/250

**Comment by Leimeroth** [comment]
Manually updating sqlalchemy using
conda install -c conda-forge "sqlalchemy>=1.4.0" 
fixed it. Maybe there is an error with the dependencies, because conda update --all downgrades it back to 1.3 for me.

**Comment by jan-janssen** [comment]
That is strange as the `pyiron_base` package 0.2.6 requests `sqlalchemy >=1.4.2` https://github.com/conda-forge/pyiron_base-feedstock/blob/master/recipe/meta.yaml#L39

**Comment by Leimeroth** [comment]
Ok so the issues seems to be that my conda simply refuses to update any pyiron package, if I do not manually specifiy the version for some reason.

**Comment by jan-janssen** [comment]
Do you use any special pinning? https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#preventing-packages-from-updating-pinning

**Comment by Leimeroth** [comment]
No, I don't use any pinning. My current pyiron_base version is 0.2.2. If i run conda search pyiron_base it finds versions up to 0.2.6 and if I run conda update pyiron_base it simply stays on 0.2.2 and says all requested packages are installed.

**Comment by jan-janssen** [comment]
Did you change anything in your conda config? 
```
cat ~/.condarc 
```

**Comment by Leimeroth** [comment]
I added conda-forge to the channels on one system. But it didn't work on the other systems as well

**Comment by jan-janssen** [comment]
Can you post the output of ` conda info` ?

**Comment by Leimeroth** [comment]
```
     active environment : base
    active env location : /home/niklas/anaconda3
            shell level : 1
       user config file : /home/niklas/.condarc
 populated config files : /home/niklas/.condarc
          conda version : 4.9.2
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/niklas/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/niklas/anaconda3/pkgs
                          /home/niklas/.conda/pkgs
       envs directories : /home/niklas/anaconda3/envs
                          /home/niklas/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.8.8 Linux/5.8.0-45-generic ubuntu/20.04.2 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by Leimeroth** [comment]
I removed all conda pyiron packages now using
```
conda remove --force pyiron pyiron_base pyiron_atomistics pyiron-data
```
If i now run
```
conda install -c conda-forge pyiron
```
it still tries to install version 0.4.0 of pyiron

**Comment by jan-janssen** [comment]
And when you enforce the pyiron version `0.4.3` ? 
```
conda install -c conda-forge pyiron=0.4.3
```

**Comment by Leimeroth** [comment]
I got it fixed on 2 out of 3 machines but now from pyiron import  Project fails for one of them with
ImportError: cannot import name 'Structure' from 'pymatgen' (unknown location),
which is imported by aimsgb. On the other machine it works fine and the only difference I can find is the build number of aimsgb.
It seems to work with pyhd8ed1ab_1 and doesn't work with pyhd3deb0d_0

**Comment by Leimeroth** [comment]
> And when you enforce the pyiron version `0.4.3` ?
> 
> ```
> conda install -c conda-forge pyiron=0.4.3
> ```

This is still trying to resolve on the 3rd machine

**Comment by jan-janssen** [comment]
> It seems to work with pyhd8ed1ab_1 and doesn't work with pyhd3deb0d_0

Yes, there was an issue with pymatgen but I thought by default the installation should select the latest build: 
https://pymatgen.org/change_log.html#v2021-3-4-yanked
We updated `aimsgb` so the next version includes the fix:
https://github.com/ksyang2013/aimsgb/pull/2

**Comment by Leimeroth** [comment]
Since I couldn't get my environment fixed at home I decided to completely reinstall anaconda. Now if I want to install pyiron it defaults to installing version 0.3.8 again.

**Comment by jan-janssen** [comment]
Can you tell me which Anaconda version you downloaded and for which operation system? Sometimes it is necessary to first update Anaconda after the initial download for the installation to work.

**Comment by Leimeroth** [comment]
ubuntu 20.04 and anaconda2020.11 (should be latest)

**Comment by jan-janssen** [comment]
And if you try `conda update --all` right after the installation before you install pyiron what does it update anything?

**Comment by Leimeroth** [comment]
Yes it updated some packages and downgraded others

**Comment by jan-janssen** [comment]
And if you try to install pyiron afterwards, which version is installed?

**Comment by Leimeroth** [comment]
I now ran
```
conda install -c conda-forge pyiron pyiron_contrib pyiron_base pyiron_atomistics
```
and  get
```
pyiron             conda-forge/noarch::pyiron-0.4.3-pyhd8ed1ab_0
 pyiron-data        conda-forge/noarch::pyiron-data-0.0.13-hd8ed1ab_0
  pyiron_atomistics  conda-forge/noarch::pyiron_atomistics-0.2.8-pyhd8ed1ab_1
  pyiron_base        conda-forge/noarch::pyiron_base-0.2.7-pyhd8ed1ab_0
  pyiron_contrib     conda-forge/noarch::pyiron_contrib-0.0.8-pyhd8ed1ab_0
```

**Comment by jan-janssen** [comment]
Sounds good to me, then we only have to remember to update once after the fresh installation of anaconda.

**Comment by Leimeroth** [comment]
Or install all pyiron packages instead of just pyiron

**Comment by Leimeroth** [comment]
I think there must be some weird bug somewhere if a version control systems installs a very old version of a requested package

**Comment by Leimeroth** [comment]
Now pyiron versions seem up to date but I get 
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
if I try from pyiron import Project

**Comment by jan-janssen** [comment]
The issue is the switch between the official anaconda channels and the conda-forge channels. One way to solve this is using: 
https://github.com/conda-forge/miniforge which is basically a purely conda-forge based mini conda version. Or use https://github.com/pyiron/pyiron-installer but that is currently also a bit outdated.

**Comment by Leimeroth** [comment]
conda install --force-reinstall numpy fixed the numpy error.

**Comment by jan-janssen** [comment]
And in addition it is helpful to set conda-forge as default: 
```
conda config --add channels conda-forge 
conda config --set channel_priority strict 
```

**Comment by jan-janssen** [comment]
I just updated the installed, so for a fresh installation that is most likely the easiest solution - it basically contains a conda installation with pyiron. https://github.com/pyiron/pyiron-installer/releases/tag/0.4.3
