### ISSUE TITLE
Is there a way to delete some files of the job?

### ISSUE THREAD

**Issue by sravankumarkb** [pyiron/pyiron_base#279]
Hello,

Is there a way to delete some files of a job? I realized I have written some unnecessary files in some jobs. I want to delete those unnecessary files in pyiron while still not deleting the jobs. Can this be done easily? Thanks.

**Comment by sudarsan-surendralal** [comment]
@sravankumarkb  I honestly think there is no better way to do this than what Jan suggested above.

**Comment by sravankumarkb** [comment]
Thanks @jan-janssen 
This does remove the files from the zipped file.
But it does not decrease the size of the .h5 file. 

I tried deleting the files and imported the jobs back into pyiron. Then the .h5 file size has decreased.

Currently, the .h5 files are occupying too much space on my disk. Is there a better way to do this than importing the jobs? Thanks.

PS: On a separate note, the copy_to is not copying the working directory and the zipped file, it is only copying the .h5 file.

**Comment by sravankumarkb** [comment]
I think copying the files into a separate folder, deleting the files that are not required and importing them back into pyiron is the best possible solution right now. 

This allows to decrease both the zipped file and also the ".h5" file associated with the job.
I am closing this issue as of now.
