### ISSUE TITLE
Project directory creation relative vs absolute path inconsistency

### ISSUE THREAD

**Issue by Leimeroth** [pyiron/pyiron_base#304]
When creating a project using an absolute path directories are only created if all but the last directory already exist, while directories are created recursively when using a relative path.
Example:
path /home/pyiron/projects/one exists
jupyter lab running in /home/pyiron/projects
pr = Project("/home/pyiron/projects/one/two") will create directory two
pr = Project("/home/pyiron/projects/one/two/three") will not create the directories two and three
pr = Project("one/two/three") will create directories two and three.

Priority probably very low, but can be annoying when trying to run jobs in different directories results in a file not found error.

**Comment by pmrv** [comment]
Try with the linked PR, I haven't checked on my own.
