### ISSUE TITLE
How can jobs be transfered to another database?

### ISSUE THREAD

**Issue by Leimeroth** [pyiron/pyiron_base#341]
We are getting closer to a group wide pyiron installation so I am confronted with the problem of transferring jobs stored in an sqlite database to a postgresql one. I tried to do this using pgloader, but all ids are null afterwards leading to an unusable state and I doubt that this can restore the relationships between master and child jobs if multiple sqlite databases are added.
If you already have a solution for this or something like a list of things to be considered that would be of great help.

**Comment by pmrv** [comment]
Try with [pack](https://pyiron-base.readthedocs.io/en/latest/apidoc/pyiron_base.project.generic.html?highlight=Project#pyiron_base.project.generic.Project.pack) and [unpack](https://pyiron-base.readthedocs.io/en/latest/apidoc/pyiron_base.project.generic.html?highlight=Project#pyiron_base.project.generic.Project.unpack).  If that's not working it's a bug.

@devs this probably warrant a FAQ entry.

**Comment by Leimeroth** [comment]
If I understand their functionality correctly, they will  also transfer the whole project directory. While I will probably have to do that at some point right now I am only trying to switch the database backend without losing the information stored in the old database, but I don't need to (and don't want to, because it is probably a few hundred GB and our IO is terrible)  transfer any of the actual job data.

**Comment by pmrv** [comment]
Since pack/unpack save and reimport the job table anyways, I suppose it would be possible to hack up a version of them that just forgoes packing the data+directory structure.  I'm not yet convinced that this is a good idea, but I might misunderstand what exactly the problem is.  What's the benefit of having the job table when you can't access the jobs (which you couldn't since you'd be missing HDF)?  Or are you ok with transferring HDF, but not all the unparsed output from the jobs in the project folder?

EDIT: I looked up the source and found that only hdf5 files should be copied into the resulting archive.

**Comment by Leimeroth** [comment]
This works now with a small fix #342 that fails for some reason. I made a repo with a small example here https://github.com/Leimeroth/TransferJobsToOtherDB with a mybinder link, but I don't know how to use the git branch from the pull request for it and it also fails building jupyter without a helpful error message.

**Comment by jan-janssen** [comment]
I created an example here https://github.com/jan-janssen/pyiron-db-change 

To install a specific version of a pyiron package I use pip - after installing the package and all dependencies via conda:
https://github.com/jan-janssen/pyiron-db-change/blob/master/.binder/environment.yml#L8

In the example notebook the reloading of the pyiron job fails, as there is some link to the old SQL database remaining, but with a second notebook it is possible to reload the calculation: 
https://github.com/jan-janssen/pyiron-db-change/blob/master/reload.ipynb

**Comment by Leimeroth** [comment]
This works fine with the sqlite databases in the examples but I get an error when trying it with the postgres database. I think it is caused by the NaN value. In the sqlite databases the columns are floats, which seem to be able to store nan values, but they are explictily converted to integers in the archiving functions, so I would like to hear what you consider the best solution for this problem.
Some possible solutions for this are discussed here:
https://stackoverflow.com/questions/50413861/how-to-handle-nans-in-pandas-dataframe-integer-column-to-postgresql-database

The error:
DataError: (psycopg2.errors.NumericValueOutOfRange) integer out of range

[SQL: UPDATE jobs_pyiron SET parentid=%(parentid)s, masterid=%(masterid)s WHERE jobs_pyiron.id = %(id_1)s]
[parameters: {'parentid': nan, 'masterid': 1, 'id_1': 2}]
(Background on this error at: http://sqlalche.me/e/14/9h9h)

**Comment by jan-janssen** [comment]
@Leimeroth I guess Postgres is using Null rather than `np.nan`, can you try replacing the `np.nan` with `None` ?

**Comment by Leimeroth** [comment]
#352 fixes the problem with nan values.
Is there a reason why the masterids are stored as floats? Ids are integers in the id and parentid columns, so I think this could cause all kinds of weird bugs due to numerical accuracy and minimum/maximum storrable values.

**Comment by jan-janssen** [comment]
@Leimeroth I guess we can close this issue, right?

**Comment by Leimeroth** [comment]
Is there some way to archive this instead maybe? I think this could be interesting for others, so maybe it would be a good idea to store this somewhere

**Comment by liamhuber** [comment]
> Is there some way to archive this instead maybe? I think this could be interesting for others, so maybe it would be a good idea to store this somewhere

We can pin it, but only up to three issues can be pinned at a time. We could also make some sort of "posterity" tag so it's easier to search for useful tutorial-like issues.

**Comment by niklassiemer** [comment]
Would be a valid solution, however, I think if this is interesting for others we should leverage it to the documentation/FAQ to handle databases. Therefore, I would rather tag with "make_documentation" or find a volunteer to directly write the documentation.

**Comment by samwaseda** [comment]
This issue can be solved with `project.pack` and `project.unpack`.
