### ISSUE TITLE
Why are these functions defined in both `GenericJob` and `GenericMaster`?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_base#355]
https://github.com/pyiron/pyiron_base/blob/30aeb75325c6722242fbf42f867f8eed32c7db05/pyiron_base/master/generic.py#L387

There are quite a few functions e.g. `run_if_interactive`, `collect_output` etc. which are defined both in `GenericJob` and `GenericMaster`, even though `GenericMaster` is anyway derived from `GenericJob`. Some of them are `pass` in `GenericMaster` and `NotImplementedError` in `GenericJob`, others are exactly identical (`NotImplementedError` in both of them). Are there particular reasons that they are repeated?

**Comment by niklassiemer** [comment]
In the first case, a `NotImplementedError` is overwritten by a `pass`, i.e. it is now allowed to call that function, however, it does not do anything. That might be considered a code smell, but currently this is necessary (at least I assume it is). 
For the second case where both functions are exactly identical, I do not see any reason to repeat those!

**Comment by samwaseda** [comment]
I'm gonna remove all of them in the next PR and see what happens

**Comment by liamhuber** [comment]
> code smell

Yep.

> I'm gonna remove all of them in the next PR and see what happens

YOLO! 😉 but seriously, let's hope we have sufficient testing to catch if it breaks something... I would certainly be happy if it can be cleaned up a little.

**Comment by samwaseda** [comment]
One more question:

in `GenericMaster`:

```python
    def update_master(self):
        """
        After a job is finished it checks whether it is linked to any metajob - meaning the master ID is pointing to
        this jobs job ID. If this is the case and the master job is in status suspended - the child wakes up the master
        job, sets the status to refresh and execute run on the master job. During the execution the master job is set to
        status refresh. If another child calls update_master, while the master is in refresh the status of the master is
        set to busy and if the master is in status busy at the end of the update_master process another update is
        triggered.
        """
        master_id = self.master_id
        project = self.project
        self._logger.info("update master: {} {} {}".format(master_id, self.get_job_id(), self.server.run_mode))
        if master_id is not None:
            self._reload_update_master(
                project=project,
                master_id=master_id
            )
```

and in `GenericJob`

```python
    def update_master(self):
        """
        After a job is finished it checks whether it is linked to any metajob - meaning the master ID is pointing to
        this jobs job ID. If this is the case and the master job is in status suspended - the child wakes up the master
        job, sets the status to refresh and execute run on the master job. During the execution the master job is set to
        status refresh. If another child calls update_master, while the master is in refresh the status of the master is
        set to busy and if the master is in status busy at the end of the update_master process another update is
        triggered.
        """
        master_id = self.master_id
        project = self.project
        self._logger.info("update master: {} {} {}".format(master_id, self.get_job_id(), self.server.run_mode))
        if (
            master_id is not None
            and not self.server.run_mode.thread
            and not self.server.run_mode.modal
            and not self.server.run_mode.interactive
        ):
            self._reload_update_master(
                project=project,
                master_id=master_id
            )
```

They look identical and I don't really understand why the check for `server` is there (maybe except for `interactive`). Can any of you tell me if there's a reason that they differ slightly?

**Comment by jan-janssen** [comment]
> I'm gonna remove all of them in the next PR and see what happens

I hope the notebooks fail ... Overwriting the functions with pass is necessary to run the generic masters in a pipeline, where all jobs are assumed to be interactive. duplicate `NotImplemented` errors are unnecessary.

**Comment by jan-janssen** [comment]
> They look identical and I don't really understand why the check for `server` is there (maybe except for `interactive`). Can any of you tell me if there's a reason that they differ slightly?

The question is which process controls the calculation. When a murnaghan is submitted to the queue, then the murnaghan process controls the individual calculation, but when the murnaghan submits its children to the queue, then the murnaghan process is closed after submitting all children. If the murnaghan job is now the child of an structure list master, which calculates the energy volume curve for different phases we have to make sure that the murnaghan only updates the structure list master, when all child jobs are finished. In this case the structure list master can run in non modal, the murnaghan in modal and the reference job of the murnaghan on the queue. After the submission of the jobs the structure list master and the murnaghan are stopped and they are updated when one of the ref jobs finished to check if all ref jobs are finished. 

Short answer - based on the hierarchy of master jobs inside master jobs, they are different from generic jobs which can only be at the most bottom level of the hierarchy.
