### ISSUE TITLE
pyiron_base - 0.2.X

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron_base#36]
With the release of pyiron_base - 0.2.X we move away from the GenericParameters towards the InputList object. With the release of pyiron_base - 0.3.X the GenericParameters are going to be no longer available.

Work in progress: 

* @pmrv started working on this in https://github.com/pyiron/pyiron_base/pull/34

**Comment by liamhuber** [comment]
Nice! I'm actually converting `pyiron.atomistics.job.SQSJob` to use `InputList` right now :)
