### ISSUE TITLE
copy to bug

### ISSUE THREAD

**Issue by niklassiemer** [pyiron/pyiron_base#362]
If I did not miss something, the `file_project` is not defined here:
https://github.com/pyiron/pyiron_base/blob/5e69910af320fd06cf48d95558edb4ed76cc1d55/pyiron_base/master/generic.py#L272

**Comment by jan-janssen** [comment]
I guess we can just extend:
```
def _after_generic_copy_to(self, original, new_database_entry, reloaded):
```
to include the `file_project` as additional input. I am just wondering why this issue was not noted before.

**Comment by pmrv** [comment]
Good catch! I'll have a look in a bit.
