### ISSUE TITLE
Cancelled jobs due to time limit on cluster are not marked as crashed in pyiron

### ISSUE THREAD

**Issue by skatnagallu** [pyiron/pyiron_base#413]
Hello,

I have several SPHInX jobs which get canceled due to the time limit on the Cluster. But these are not marked as "not-converged" in pyiron job table and are shown as "running". I would like to use the structures from these unfinished calculations and restart my jobs with these structures, which I currently cannot do as the jobs are marked as "running".  Can anyone help me out?

**Comment by pmrv** [comment]
[Here](https://hpc-discourse.usc.edu/t/signalling-a-job-before-time-limit-is-reached/314) it is shown that we could catch this in principle, but it would need a bit more work on our side & the cluster submission scripts we use.

**Comment by jan-janssen** [comment]
> [Here](https://hpc-discourse.usc.edu/t/signalling-a-job-before-time-limit-is-reached/314) it is shown that we could catch this in principle, but it would need a bit more work on our side & the cluster submission scripts we use.

In general that is what we do already https://github.com/pyiron/pyiron_base/blob/master/pyiron_base/job/generic.py#L173 , and it seems to work on some HPC cluster. The question is how the queuing system is killing the jobs, e.g. which signal is send and if there is any grace period for the code to stop. Or is it code dependent? At least for LAMMPS it is working for me.

**Comment by pmrv** [comment]
As shown in the example we'd have to configure in the submission script the signal to send and the time it is sent before the job is killed.  I wasn't aware we do this for some signals already, but it actually seems like a small fix now.  Basically just adding the relevant lines from the example to the cluster config files [here](https://github.com/eisenforschung/pyiron-resources-mpie/tree/master/queues) and add `signal.SIGUSR1` [here](https://github.com/pyiron/pyiron_base/blob/eef00c25ee9bbe7c4914dd4a583ba7c98b5a3f44/pyiron_base/job/generic.py#L41).  Want to give it a shot @skatnagallu ?

**Comment by pmrv** [comment]
> The snippet below gives a work around
> 
> ```python
> for j in pr.iter_jobs(status='running', convert_to_object=False):
>     pr.refresh_job_status_based_on_job_id(j.id)
> ```
> 
> Basically the problem is that when a job is killed by the queuing system, pyiron has no way of marking this in the database (since it just got killed). To refresh the job status the method above has to be called, so that pyiron can compare in a new process which jobs are marked as running and actually are reported by the queuing system.
> 
> I do suppose we could add the snippet above to the `job_table` method so that whenever you call that in you notebook you end up with a proper job table.

Just in case you're unaware, this issue was fixed in https://github.com/pyiron/pyiron_base/pull/464, so you can just do `pr.refresh_job_status()` now, without giving the job id.

**Comment by freyso** [comment]
> In general that is what we do already https://github.com/pyiron/pyiron_base/blob/master/pyiron_base/job/generic.py#L173 , and it seems to work on some HPC cluster. The question is how the queuing system is killing the jobs, e.g. which signal is send and if there is any grace period for the code to stop. Or is it code dependent? At least for LAMMPS it is working for me.

Shyam brought this again to my attention, and I tried to understand the course of things, in particular why that would work for LAMMPS, but not for SPHInX.
To my understanding, the process hierarchy is like this:
script-submitted-to-slurm.sh -> python-wrapper to load and run job -> sphinx-wrapper-script -> sphinx executable

the python-wrapper is the one which should capture the TERM signal and modify the job status in the pyiron database

to my understanding, slurm sends a TERM signal to the script-submitted-to-slurm.sh process, then waits for 30 sec, and if the processes have not died by then, sends every process in the cgroup a KILL. My further understanding is that the script does not forward the TERM signal, so this should not work for LAMMPS jobs running in the queue either.

I also do see that the trapping of the signal is logged inside pyiron_base/generic.py . Is there any way to assess this logging for debugging the issue?

A possible way to do this would be to run the python-wrapper via exec, i.e., replace the one-line-script-submitted-to-slurm.sh process by the subsequent python process. In this way, slurm would send its TERM signal right away to python.

@jan-janssen could you please confirm that my process hierarchy understanding is correct, and if possible, explain how LAMMPS jobs capture the TERM signals (if they do)?

**Comment by SanderBorgmans** [comment]
Is there a reason why the job status of running jobs is not automatically refreshed when loading the job_table? This could be easily done by prepending a loop over all job_ids and checking refresh_job_status_based_on_job_id:

https://github.com/SanderBorgmans/pyiron/commit/d10e99ff96d41e5c49fdd6b2f58c21d40917d3f9

**Comment by freyso** [comment]
In my view, there are:
1. one would have to query the queuing system to check which jobs are still marked as running. To my understanding, you would have to do this either on a job-by-job basis (lots of queuing system requests), or getting all jobs in one row and then matching queue ids.
2. The idea of the pyiron database is that this is leight-weight source of info.
3. It conceptually makes most sense if jobs actively change their status on their own (inside-out, not outside-in). It works perfectly for everything, except for  job crashes, and a clean solution to solving this is not really difficult.

**Comment by pmrv** [comment]
Agree with @freyso the change I sketched above should cover most use cases.  I won't have time to work on this directly, but as I said it should be fairly minor and I'm happy to help anyone, who needs this urgently.

I can think of three cases right now where the normal "control flow" of a simulation is interrupted:
1. simulation code crashes hard or returns with error code while the compute node is still up -> pyiron checks the error code, updates the database and stops gracefully
2. simulation code exceeds runtime allocation and the whole node gets killed by the queuing system -> pyiron never runs and therefore never updates the database
3. pyiron itself crashes during setting up the simulation code or reading its output -> we never check for such a crash and therefore never update the database.

Case 1. is already handled, case 2. would be handled by hooking to the signal from SLURM and finally case 3. could either be handled by setting up a try/except around the job wrapper or just fixing the error and updating the code.  Since in the thermodynamic limit pyiron has no bugs, I expect the marginal utility of this last case to be small though. :P

**Comment by freyso** [comment]
@pmrv 
>  Since in the thermodynamic limit pyiron has no bugs, 

??? Bugs are similar to point defects. pyiron hopefully continues to be an ever-developing code, so there will be an equilibrium concentration of bugs as part of the inherent code entropy...
Only tex aims at developing towards a stable version for eternity (I think the target version is 3.141592.... .

**Comment by pmrv** [comment]
> @pmrv
> 
> > Since in the thermodynamic limit pyiron has no bugs,
> 
> ??? Bugs are similar to point defects. pyiron hopefully continues to be an ever-developing code, so there will be an equilibrium concentration of bugs as part of the inherent code entropy... Only tex aims at developing towards a stable version for eternity (I think the target version is 3.141592.... .

I stand corrected, let's put in on the road map then. ;)

**Comment by samwaseda** [comment]
Every now and then `project.refresh_job_status()` (or `project.job_table(auto_refresh_job_status = True)`) should be called, in order for the aborted jobs to be detected. In order to collect the dangling SPHInX output, you can call `job.collect_output`.
