### ISSUE TITLE
InputList asymmetry: instantiated vs loaded

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_base#42]
Accessing `InputList` elements functions differently if the input list is instantiated or loaded from HDF5. This is because saving to HDF5 wraps complex sub-elements also as `InputList` objects, and this wrapping isn't undone when we load from HDF5. 

This can create an asymmetry in how we access the data depending whether the input list is "fresh" or loaded, which is awkward.

- Is this wrapping before saving necessary?
- Can we unwrap in `from_hdf`?
  - If we do, how do we distinguish the case where the user is legitimately *trying* to nest `InputList` objects?
- I haven't dug into it yet, but I assume that the unique iterator behaviour of `InputList` is pretty important. However, I guess changing this behaviour would also be a potential place for resolving this compaint.

# Example

## Demonstrate behaviour

`InputList.to_hdf` wraps complex children as new `InputList`s.

```python
from pyiron_base import InputList, Project
pr = Project('scratch')
pr.remove_jobs_silently(recursive=True)

inputlist = InputList(table_name='inputlist')
inputlist.dict_ = [{'foo': [1], 'bar': 'baz'}, {'foo': [1, 2], 'bar': 'bazz'}]
inputlist.list_ = ['a', 'b', 'c']
inputlist.int_ = 42

hdf = pr.create_hdf(pr.open('inputlist_hdf5').path, 'inputlist')
inputlist.to_hdf(hdf=hdf)

loaded = InputList(table_name='inputlist')
loaded.from_hdf(hdf)

print(inputlist)
# list and dict children get wrapped as InputList!
print(loaded)

> InputList({'dict_': [{'foo': [1], 'bar': 'baz'}, {'foo': [1, 2], 'bar': 'bazz'}], 'list_': ['a', 'b', 'c'], 'int_': 42})
> InputList({'dict_': InputList([InputList({'foo': InputList([1]), 'bar': 'baz'}), InputList({'foo': InputList([1, 2]), 'bar': 'bazz'})]), 'list_': InputList(['a', 'b', 'c']), 'int_': 42})
```

## Problem case

If we want to access the data, we can't use the same operations on the loaded instance that we would naively use on the fresh instance.

```python
print([d['foo'] for d in inputlist['dict_']])

> [[1], [1, 2]]
```

```python
print([d['foo'] for d in loaded['dict_']])

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-91-7b45699c5ce0> in <module>
----> 1 print([d['foo'] for d in loaded['dict_']])

<ipython-input-91-7b45699c5ce0> in <listcomp>(.0)
----> 1 print([d['foo'] for d in loaded['dict_']])

TypeError: 'int' object is not subscriptable
```

## Cause

This stems from the unique iterator behaviour of `InputList`.

```python
print([i for i in inputlist['list_']])
print([i for i in loaded['list_']])

> ['a', 'b', 'c']
> [0, 1, 2]
```

**Comment by pmrv** [comment]
The root problem is a bit different, namely that when saving to HDF5 the whole nested structure is converted to dicts/lists to accomodate the current HDF5 saving code (c.f. `to_builtin`).  Once it is there the whole nested structure is wrapped in InputLists when read as we can no longer distinguish which elements were originally dict/list and which were only converted for saving.

I'm planning on changing the HDF5 structure of InputList in the future to explicitly map nested InputLists to HDF5 groups.  This would solve the problem and is needed for storage of generic members (any type that defines `to_hdf`/`from_hdf`) anyway.

The iterator behavior of InputList is the default one for mappings in python, compare e.g. with `list(iter({0: 42, 1: 24}))`.

**Comment by liamhuber** [comment]
> I'm planning on changing the HDF5 structure of InputList in the future to explicitly map nested InputLists to HDF5 groups. This would solve the problem and is needed for storage of generic members (any type that defines `to_hdf`/`from_hdf`) anyway.

Perfect! Yeah, I have no problem with the current iterator behaviour in and of itself, it's just when things are coming out differently than how I put them in ;)

As long as this is on the radar I'll close the issue and work around it for now :)
