### ISSUE TITLE
ValueError when group_name is None

### ISSUE THREAD

**Issue by raynol-dsouza** [pyiron/pyiron_base#443]
When trying to run the following job:

```
job1d_square = pr.create.job.TISE('tise1d_square', delete_existing_job=True)
job1d_square.input.potential = SquareWell(depth=10)
job1d_square.input.mesh = RectMesh(bounds=10, divisions=100)
job1d_square.input.n_states = 10
job1d_square.input.mass = 1
job1d_square.run()
```

I run into the following error:

```
~/pyiron/pyiron_continuum/pyiron_continuum/schroedinger/schroedinger.py in run_static(self)
    177         self.output.energy = eigenvalues
    178         self.output.psi = np.array([np.reshape(v, self.mesh.shape[1:]) for v in eigenvectors.T])
--> 179         self.to_hdf()
    180         self.status.finished = True
    181 

~/pyiron/pyiron_base/pyiron_base/job/template.py in to_hdf(self, hdf, group_name)
     37 
     38     def to_hdf(self, hdf=None, group_name=None):
---> 39         HasStorage.to_hdf(self, hdf=self.project_hdf5)
     40 
     41     def from_hdf(self, hdf=None, group_name=None):

~/pyiron/pyiron_base/pyiron_base/interfaces/has_hdf.py in to_hdf(self, hdf, group_name)
    175         with _WithHDF(hdf, group_name) as hdf:
    176             if len(hdf.list_dirs()) > 0 and group_name is None:
--> 177                 raise ValueError("HDF group must be empty when group_name is not set.")
    178             self._to_hdf(hdf)
    179             self._store_type_to_hdf(hdf)

ValueError: HDF group must be empty when group_name is not set.
```

This error message is raised since in the 2nd stack, group_name is None. It pops up from the change in line 176 in PR #434.

**Comment by liamhuber** [comment]
@raynol-dsouza your snippet runs fine on my machine. Do you also have the lastest master merged in? Master has [#442 ](https://github.com/pyiron/pyiron_base/pull/442) as well, which I think might resolve your issue.

**Comment by pmrv** [comment]
I missed this yesterday, but now the template job doesn't call `GenericJob.to_hdf` anymore, this can't work or not?

https://github.com/pyiron/pyiron_base/blob/5fb4a7fb6baa162ea63d5906c4b0b7bb58d4cffa/pyiron_base/job/template.py#L38

**Comment by raynol-dsouza** [comment]
@liamhuber I am on the latest merge on master. Up to #442 works fine.

**Comment by liamhuber** [comment]
> I missed this yesterday, but now the template job doesn't call GenericJob.to_hdf anymore, this can't work or not?

I'm all set up doing other base work so I'm not sure exactly where my HEAD is. Will have to dig deeper tomorrow or during the GA lunch break. It works OK in Schroedinger though.

**Comment by liamhuber** [comment]
Wait, 

> Up to #442 works fine.

Does this mean if you go further it stops working, or was my close OK?

**Comment by raynol-dsouza** [comment]
It does not work on the latest master, which has #434 merged. I think the close is not OK.

**Comment by raynol-dsouza** [comment]
My `git log` (on master) looks like this:

```
commit 5fb4a7fb6baa162ea63d5906c4b0b7bb58d4cffa (HEAD -> master, tag: pyiron_base-0.3.3, origin/master, origin/HEAD)
Author: Liam Huber <liam.huber@gmail.com>
Date:   Mon Sep 20 20:55:20 2021 +0200

    Smooth storage (#434)

    * Rebase HasStorage onto Has_HDF

    * resolve pycharm nits

    * Import from specific location not module head

    * Avoid name conflict with GenericJob._type_to_hdf

    Now that we have multiple inheritance AND old code (i.e. `GenericJob`) floating around, we have to watch our step.

    * Store type, etc at the base level of the hdf provided

    the 'storage' data container then sites beneath this.

    * Update template job based on new HasStorage abilities

    * Update pyiron_base/generic/object.py

    Co-authored-by: Marvin Poul <poul@mpie.de>

    Co-authored-by: Marvin Poul <poul@mpie.de>

commit 232a144847e0ba1223eacaa6d76ac17e153c7b61
```

**Comment by liamhuber** [comment]
Latest master should also have #442. It is [merged](https://github.com/pyiron/pyiron_base/pull/434/files). I don't know well enough how to read the git log to be sure, but it still looks to me like your master is stale

**Comment by raynol-dsouza** [comment]
I agree that #442 IS merged. From the commit trace, it seems 442 was committed BEFORE #434.

I did a `get fetch -> git pull` on my local `pyiron_base` repo about 5 minutes ago.

EDIT: doing `git branch --contains 232a144847e0ba1223eacaa6d76ac17e153c7b61` the large alphanumeric being the commit id of #442 also confirms that my local master branch has this commit merged.

**Comment by liamhuber** [comment]
Ok, then I'll need to dig into it later; wherever my branch is at right now, your snippet runs without error.

**Comment by raynol-dsouza** [comment]
Cool! I'd initially check by just not having #434 in master. In my case, if I am at #442 it works.

**Comment by liamhuber** [comment]
> I missed this yesterday, but now the template job doesn't call `GenericJob.to_hdf` anymore, this can't work or not?
> 
> https://github.com/pyiron/pyiron_base/blob/5fb4a7fb6baa162ea63d5906c4b0b7bb58d4cffa/pyiron_base/job/template.py#L38

This was a good fear.

I have a patch in #444 but I don't like how ugly and duplicated the HDF gets

**Comment by pmrv** [comment]
So the general issue is that `GenericJob` isn't yet a `HasHDF` itself, so there's two conflicting `to_hdf`'s that we need to make compatible.  Am playing around right now.

**Comment by liamhuber** [comment]
Yep, 100% agree on the diagnosis. As such I'm willing to accommodate a somewhat Jacky transient solution as we shift over, but if you can come up with something more elegant than I did that would be stellar!
