### ISSUE TITLE
DataContainer not saving collections

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_base#479]
I might be totally missing something, either with a stupid user mistake or by forgetting what actual capabilities were...but shouldn't I be able to trivially save collections (lists, dicts, etc.) in `DataContainer`? The following surprises me with an exception:

```python
from pyiron_base import Project, DataContainer
pr = Project('scratch')
pr.remove_jobs_silently(recursive=True)
dc = DataContainer(table_name='dc')
dc.dict_ = {'foo': 1, 2: 'bar'}
dc.to_hdf(hdf=pr.create_hdf(job_name='mydc', path='.'))
```

<details>
  <summary>Exception</summary>

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/zp/s_210n851_scfvdl1fkrg6540000gq/T/ipykernel_58390/3729404716.py in <module>
      1 dc = DataContainer(table_name='dc')
      2 dc.dict_ = {'foo': 1, 2: 'bar'}
----> 3 dc.to_hdf(hdf=pr.create_hdf(job_name='mydc', path='.'))

~/work/pyiron/pyiron_base/pyiron_base/interfaces/has_hdf.py in to_hdf(self, hdf, group_name)
    208             if len(hdf.list_dirs()) > 0 and group_name is None:
    209                 raise ValueError("HDF group must be empty when group_name is not set.")
--> 210             self._to_hdf(hdf)
    211             self._store_type_to_hdf(hdf)
    212 

~/work/pyiron/pyiron_base/pyiron_base/generic/datacontainer.py in _to_hdf(self, hdf)
    794                     hdf[k] = v
    795                 except TypeError:
--> 796                     raise TypeError("Error saving {} (key {}): DataContainer doesn't support saving elements "
    797                                     "of type \"{}\" to HDF!".format(v, k, type(v))) from None
    798 

TypeError: Error saving {'foo': 1, 2: 'bar'} (key dict___index_0): DataContainer doesn't support saving elements of type "<class 'dict'>" to HDF!
```
</details>

I'm on:
Module                                   pyiron_base
Git head    4e70a2d0b82ad9c2630cf7b459efd19a8416596b
Version                             0.3.7.post.dev10

I can work around this by just nesting in another `DataContainer` instead of something more primitive, but I am still a bit confused why it's balking to start with.

EDIT: adding the project instantiation lines so the MWE actually compiles

**Comment by pmrv** [comment]
Seems like a bug in `h5io`, since using this value
```
dc.dict_ = {'foo': 1, '2': 'bar'}
```
works.

**Comment by pmrv** [comment]
Under the hood we use `h5io.write_hdf5(..., use_json=True)`.  For `use_json=False` it gives an error message that it expects all keys in dictionaries to be `str`.  For the other case it just gives a weird error, which I guess is technically ok, since integer keys don't conform to the JSON spec, but I guess we need to work around that somehow.

**Comment by liamhuber** [comment]
Ok, thanks for tracking down where the issue is. I actually ran into it with lists too. I'll take another look once the kids are in bed

**Comment by liamhuber** [comment]
Alright so the list was my bad, I had it full of complex data types that have their own `to_hdf`. There the most straightforward solution is to intentionally use another `DataContainer` instead of a list.

For only accepting string keys... The stopping happens [here](https://github.com/h5io/h5io/blob/8dbd917be7c78737ffed04602ac7401c9486ef87/h5io/_h5io.py#L149). It seems super easy to force the non-string keys to strings, but I guess the real trouble is that then you need to add some identifier code so that you can know how to convert them back when reading, e.g. `'1'` ->  `'1'`, `1` ->  `'i1'`, `1.1` ->  `'f1_1'` etc (or similar). I don't feel passionately enough about it to implement all that and might still be overlooking other complications, so I will take the quick and easy path to the dark side and just code around it on my end.
