### ISSUE TITLE
Project wait_for_jobs( ) TypeError

### ISSUE THREAD

**Issue by Leimeroth** [pyiron/pyiron_base#482]
Since I update my pyiron installation today the Project wait_for_jobs method throws the following error message after successfully fetching the first job from our remote cluster. My guess is that some changes introduced in #336 cause this issue.

I think the FileTable job_table() is completely different compared to an sql database. At least the it takes completely different arguments than the job_table() of IsDatabase. The job_table() method is also used in the get_jobs() method of FileTable, so I assume it is also broken.
Maybe it woud be good to only use IsDatabase for SQL databases or have something like IsSQLDB and IsFileDB,
maybe this can be fixed by setting some default values for the arguments in _get_job_table(), but I don't know much about how these work internally, so this could be completely off. Would be great if you could have a look at this @pmrv 

```
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_4170575/3846198617.py in <module>
      1 pr = Project(".")
----> 2 pr.wait_for_jobs(max_iterations=1, interval_in_s=0)

~/git_projects/pyiron_base/pyiron_base/project/generic.py in wait_for_jobs(self, interval_in_s, max_iterations, recursive)
   1339             ValueError: max_iterations reached, but jobs still running
   1340         """
-> 1341         wait_for_jobs(
   1342             project=self,
   1343             interval_in_s=interval_in_s,

~/git_projects/pyiron_base/pyiron_base/server/queuestatus.py in wait_for_jobs(project, interval_in_s, max_iterations, recursive)
    220     finished = False
    221     for _ in range(max_iterations):
--> 222         project.update_from_remote(recursive=True)
    223         df = project.job_table(recursive=recursive)
    224         if all(df.status.isin(job_status_finished_lst)):

~/git_projects/pyiron_base/pyiron_base/project/generic.py in update_from_remote(self, recursive)
    608             recursive (bool): search subprojects [True/False] - default=True
    609         """
--> 610         update_from_remote(
    611             project=self,
    612             recursive=recursive

~/git_projects/pyiron_base/pyiron_base/server/queuestatus.py in update_from_remote(project, recursive)
    271                 if status_hdf5 in job_status_finished_lst:
    272                     job_object = job.to_object()
--> 273                     job_object.transfer_from_remote()
    274 
    275 

~/git_projects/pyiron_base/pyiron_base/job/generic.py in transfer_from_remote(self)
    782         else:
    783             ft = FileTable(project=self.project_hdf5.path + "_hdf5/")
--> 784             df = ft.job_table(all_columns=True)
    785             db_dict_lst = []
    786             for j, st, sj, p, h, hv, c, ts, tp, tc in zip(

TypeError: job_table() missing 3 required positional arguments: 'sql_query', 'user', and 'project_path'
```

**Comment by pmrv** [comment]
I'm looking at this right now.  @niklassiemer we should hold the next base release until this is fixed, @Leimeroth for now you should be able to go down to 0.3.8 and still continue to work.

**Comment by pmrv** [comment]
Right now `FileTable._get_job_table` silently ignores `user`, `sql_query` and `project_path`, so a hotfix is to just pass `None`, but I'll try to identify the underlying problem.
