### ISSUE TITLE
Allow custom 'successful' exit codes for executables run by custom job class

### ISSUE THREAD

**Issue by s4b7r** [pyiron/pyiron_base#496]
I wrote a small example wrapper for an external simulation tool I'm trying to integrate with pyiron based on [this example](https://github.com/materialdigital/PMD-workflow-workshop/blob/master/2_customized_job/2_1_custom_bash_job.ipynb).

This seems to work fine so far, however, the external tool returns non-zero exit codes in some cases. Those aren't failure states but useful return values. Therefore, I would like pyiron to not interpret those as errors.

**Comment by pmrv** [comment]
The simplest way to do it is write a little wrapper script for your external tool and set that script as the executable for that job.  It could be something like

```bash
#!/bin/bash
your_tool $@
ERR=$?
if (( $ERR == 0 || $ERR == 1 || $ERR == 2 )); then
  exit 0
else
  exit $?
fi
```

It's a bit annoying I guess to have to break out to a shell for this, but in practice (at least on our installation) most simulation code are wrapped in scripts like this anyway to e.g. start them with mpi or do any auxiliary configuration of say the cluster module system.

**Comment by s4b7r** [comment]
This pragmatic solution is fine for my current environment. In this regard the issue can be closed, if you'd like to.

Nevertheless, I think it could get especially annoying because a shell script introduces a new platform dependend layer. A built-in option in pyiron to set successfull exit codes would be platform independent (in itself - of course that would still depend on the external tool etc.). That could be less annoying for some use cases / users. However, I assume (or hope) that most software respects the convention to use 0 for successful exits.
