### ISSUE TITLE
Performance issue with h5io

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron_base#502]
From my perspective this comes from https://github.com/pyiron/pyiron_base/pull/233

**Comment by pmrv** [comment]
@JNmpi Notebook is [here](https://gist.github.com/pmrv/56a3363e4164d65889ca0f1a38f2ef20).

I've confirmed in the profiler most of the runtime is `h5io.write_hdf5`, because it converts the dtype=object array into lists.
