### ISSUE TITLE
remotely submitted job failed to fetch back the results

### ISSUE THREAD

**Issue by max-hassani** [pyiron/pyiron_base#509]
I tried to submit a simple lammps job from my laptop to the cluster. The job got submitted to a queue and run successfully. But I do not get back the results to my laptop and the status remains as submitted. Do I have to run another command to fetch back the results? As I looked at the methods available under job.server, I could not find such a command!
I checked on the cluster, I am able to load there the job and the outputs look fine.

**Comment by jan-janssen** [comment]
A introduction to remove jobs is available in the old pyiron meetings, but I agree this should be updated and added to the documentation: https://github.com/pyiron/pyiron-meeting/tree/master/2020-08-28/jan-janssen

**Comment by max-hassani** [comment]
thanks @jan-janssen. `pr.wait_for_job()` was something that I was not aware of. Maybe it is not a bad idea to update the relavant notebooks from our local handbook and add them to tutorials. Then these functionalities would be clear to new users or users who have not submitted any remote jobs to the cluster.

**Comment by max-hassani** [comment]
I have another question; in our documentation, it is mentioned that when a job is submitted remotely, the database has to be disabled on the login node of the HPC cluster. My question is how can we do this without modifying the `.pyiron` file on the login node. Can we simply pass this setting configuration as a dictionary via job? I remembered you mentioned a similar approach in one of pyiron meetings. Can you please explain it a bit?

**Comment by jan-janssen** [comment]
I always modified either the `.pyiron` config or set the environment variable, but there is currently no way to have a specific configuration for remote jobs.
