### ISSUE TITLE
copy_to ignores new job name if a new project is used

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_base#51]
Observed behaviour:

```python
from pyiron_base import Project
pr = Project('scratch')
pr.remove_jobs_silently(recursive=True)
ref_job = pr.create_job(pr.job_type.ScriptJob, 'ref')
parent_job = pr.create_job(pr.job_type.ScriptJob, 'parent')
new_name = ref_job.copy_template(project=parent_job._hdf5, new_job_name='parents_ref')
new_name._hdf5.path, new_name.job_name
> ('/Users/huber/Liam/pyiron/projects/tmp/scratch/parent/ref', 'ref')
```

Desired behaviour
```python
new_name._hdf5.path, new_name.job_name
> ('/Users/huber/Liam/pyiron/projects/tmp/scratch/parent/parents_ref', 'parents_ref')
```

I've been fighting for a large chunk of the day with HDF management over in the [contrib SQS elastic branch](https://github.com/pyiron/pyiron_contrib/blob/elastic_constants/pyiron_contrib/atomistic/atomistics/master/sqselastic.py). I realized this evening that `copy_to` was simply ignoring some of it's input. 

With at least part of the problem nailed down, I've been trying to correct the `pyiron_base/job/generic/GenericJob.copy_to` behaviour, but am clearly still missing some serious facts because all my attempts end with thrown exceptions.

**Comment by jan-janssen** [comment]
Inside the jobs please use the `append()` and `pop()` function:
https://github.com/pyiron/pyiron_base/blob/master/pyiron_base/master/generic.py#L182

But maybe it is easier to discuss the details tomorrow in the pyiron meeting. If you create a quick example inside a notebook which is using the ParallelMaster to calculate the SQS structures then I can show how to use the FlexibleMaster to connect the SQS Jobs and the list of structures like we do it in the Pipeline: 
https://github.com/pyiron/pyiron/blob/master/notebooks/bandstructure.ipynb
and with the band structure:
https://github.com/pyiron/pyiron-meeting/blob/master/2020-08-28/jan-janssen/band_structures_flexible.ipynb

From there we can discuss how to make it a single class. I just have the feeling we mix up two versions of copy() one which is used to store a child job of the HDF5 file of the master before it is executed and one which is used to copy finished jobs from one project to the next. I agree they are not clearly documented and the difference is not well explained, so do not hesitate to discuss these parts with me directly.

**Comment by liamhuber** [comment]
> Inside the jobs please use the `append()` and `pop()` function:
> https://github.com/pyiron/pyiron_base/blob/master/pyiron_base/master/generic.py#L182

I am aware of these, but I believe this doesn't work for my case. I need information about a job within a FlexibleMaster, but I don't actually want to execute that job; if I append to FlexibleMaster these jobs become part of the queue for running, so append/pop is not a universal solution.

My current code works perfectly fine if I save the jobs at an HDF-sibling level, I just thought it would cleaner and nicer to have them nested inside the job that is using them rather than crowding the project level directory.

> But maybe it is easier to discuss the details tomorrow in the pyiron meeting. If you create a quick example inside a notebook which is using the ParallelMaster to calculate the SQS structures then I can show how to use the FlexibleMaster to connect the SQS Jobs and the list of structures like we do it in the Pipeline:
> https://github.com/pyiron/pyiron/blob/master/notebooks/bandstructure.ipynb
> and with the band structure:
> https://github.com/pyiron/pyiron-meeting/blob/master/2020-08-28/jan-janssen/band_structures_flexible.ipynb
> From there we can discuss how to make it a single class.

As hinted above and shown in the [blob I linked in the op](https://github.com/pyiron/pyiron_contrib/blob/elastic_constants/pyiron_contrib/atomistic/atomistics/master/sqselastic.py), I **already have** a class that uses FlexibleMaster to couple SQSJob, ListMaster (with a calc_minimize) and ListMaster (with ElasticMatrixJob), and another one which takes all that and wraps it in ParallelMaster so you can do multiple SQS compositions at once. 

I am definitely open to suggestions of how best to manage the job and HDF data, and this is part of why I want to present it in the meeting today, but this is not the core of this Issue.

> I just have the feeling we mix up two versions of copy() one which is used to store a child job of the HDF5 file of the master before it is executed and one which is used to copy finished jobs from one project to the next. I agree they are not clearly documented and the difference is not well explained, so do not hesitate to discuss these parts with me directly.

We can certainly discuss this, and I agree that this subtlety is not super evident, but, again, this is really not my point.

My point is very simply this: `copy_to` does not follow through on its promised functionality, as stated in the issue title. There are four cases:

- Same name, same project: Raises an exception, exactly as it should.
- Same name, different project: Works fine.
- Different name, same project: Works fine.
- Different name, different project: **fails silently** by ignoring the fact I asked for a new name.

There are other things in this area that can be improved, but this is a clean and isolated bug by itself. The new name should never simply be ignored. I can't figure out how to fix this.

**Comment by jan-janssen** [comment]
The append and pop function have nothing to do with the execution, they basically store the job template inside the Master and get it back out for execution, that is exactly the copy functionality you need.

**Comment by liamhuber** [comment]
> The append and pop function have nothing to do with the execution, they basically store the job template inside the Master and get it back out for execution, that is exactly the copy functionality you need.

This is incorrect. For FlexibleMaster this is simply incorrect. 

- In [validate_ready_to_run](https://github.com/pyiron/pyiron_base/blob/af9a28af6cfc7a1c6ad28c7f00ba3e6801c714d0/pyiron_base/master/flexible.py#L137) FlexibleMaster
  - Checks if the job list and the function list hav the right relative length
  - Later, in run_static, it 
    - [loops over all the child ids](https://github.com/pyiron/pyiron_base/blob/af9a28af6cfc7a1c6ad28c7f00ba3e6801c714d0/pyiron_base/master/flexible.py#L169) 
    - [pops the appended jobs](https://github.com/pyiron/pyiron_base/blob/af9a28af6cfc7a1c6ad28c7f00ba3e6801c714d0/pyiron_base/master/flexible.py#L170) 
    - and [executes them](https://github.com/pyiron/pyiron_base/blob/af9a28af6cfc7a1c6ad28c7f00ba3e6801c714d0/pyiron_base/master/flexible.py#L178).
- FlexibleMaster populates its child job list by inheriting [append from GenericMaster](https://github.com/pyiron/pyiron_base/blob/af9a28af6cfc7a1c6ad28c7f00ba3e6801c714d0/pyiron_base/master/generic.py#L182)

I very much appreciate the speed of replies, but ping-pong replies of "Do X", "X doesn't work because Y", "No, definitely X" without digging into the matter a bit more deeply or attempting to uncover where the misunderstanding "Y" comes from are not helpful. (In this case, I am only more convinced that "Y=FlexibleMaster executes jobs appended to it" is a reasonable concern.

**Comment by jan-janssen** [comment]
@liamhuber Can you check if this is solved by https://github.com/pyiron/pyiron_base/pull/90 ?

**Comment by liamhuber** [comment]
Solved by #90

**Comment by jan-janssen** [comment]
Maybe it makes sense to add a quick test case, just to make sure we do not loose this functionality in future.

**Comment by liamhuber** [comment]
> Maybe it makes sense to add a quick test case, just to make sure we do not loose this functionality in future.

Will do. PR in a minute.
