### ISSUE TITLE
Data written to objects created from Project.create_hdf not visible.

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_base#53]
I'm trying to get a `ProjectHDFio` instance I can write some values to and read them again later.  Mostly for debugging the HDF5 code of `InputList`.  During this stumbled on this
```python
import pyiron_base
p = pyiron_base.Project('test')
h = p.create_hdf(p.path, 'subgroup')
h['asdf'] = 42
h['asdf']
> ValueError: Unknown item: asfd
```
Yet, when I afterwards look into the `test/` project folder the hdf5 file is correctly created and is also populated with the values I set.  It is just accessing those values via ProjectHDFio that is broken.

**Comment by niklassiemer** [comment]
Actually, this works as expected for me.

**Comment by pmrv** [comment]
Weird, works now here, too.

Thanks for reproducing!
