### ISSUE TITLE
dtype=object considered annoying or rewrite_hdf5 fails on Vasp jobs

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_base#532]
The update script right now fails on all Vasp calculations, because the numpy conversion to dtype=object

https://github.com/pyiron/pyiron_base/blob/15470a312df4f4a88de39391e9eb6e5bb387a0dd/pyiron_base/generic/hdfio.py#L230

fails, if the arrays in the list are of shape [(n, k), (n,), (n,),...] (this pattern of shapes comes up for the irreducible kpoints in Vasp calculations).  Why this doesn't work for this pattern of shapes, but for others is something only the numpy developers may divine.  In any case I'll try to find a solution without this conversion today, but before that there's no point in running the update script yet.

**Comment by niklassiemer** [comment]
But this also means that our read method is not working here... Maybe we should again restrict h5io to version 0.1.2 such that we get the numeric arrays after all? I will again look into what h5io did before and if we can adapt this in a different way to get numeric arrays in all cases...

**Comment by pmrv** [comment]
I think this due #503 changing the condition slightly.  In the previous case (I guess) the check (wanted to) ensures that only arrays are converted this way that have different first dimension only.  The bug there was that the check also included non-ragged arrays.  That means tough that reading the affected data with your code #530 should always be ok.

This bug now is that my code from #503 tries to convert all ragged arrays and not just those that share `shape[1:]`.

**Comment by sudarsan-surendralal** [comment]
To be honest, this need not be a problem with the update script. It's just that this particular quantity was previously parsed and stored in a bad way (see the fix https://github.com/pyiron/pyiron_atomistics/pull/423). In previous calculations  the node `irreductible_kpoints` was parsed  as a tuple (three different quantities) but stored as a list in the hdf5 file. 

https://github.com/pyiron/pyiron_base/blob/15470a312df4f4a88de39391e9eb6e5bb387a0dd/pyiron_base/generic/hdfio.py#L232-L233

**Comment by pmrv** [comment]
Ah, I was wondering how it works when running a new Vasp job (which doesn't crash).  The first time it's passed as a tuple, converted to a list, then written as a list and then during the rewrite read as a list, passed as a list, then recognized as a ragged array and conversion is attempted.

Even if new version of pyiron_atomistics don't write it like that anymore, I suppose the best way to deal with this is to change `_is_ragged_array` to check  that the other dimension match.
