### ISSUE TITLE
`project_check_enabled` is misleading

### ISSUE THREAD

**Issue by niklassiemer** [pyiron/pyiron_base#539]
In my opinion, our setting `project_check_enabled` is somewhat misleading or at least changing to much on the behavior side. 
Right now if I run 
```python
from pyiron_base import state, Project

state.settings.update({'project_paths': ['/mnt/c/Users/Siemer/pyiron/projects/'],
                      'project_check_enabled': True})
pr = Project('dummy')
print(pr.root_path, pr.project_path)
>>> /mnt/c/Users/Siemer/pyiron/projects/ dummy/

state.settings.update({'project_paths': ['/mnt/c/Users/Siemer/pyiron/projects/'],
                      'project_check_enabled': False})
pr = Project('dummy')
print(pr.root_path, pr.project_path)
>>> None /mnt/c/Users/Siemer/pyiron/projects/dummy/
```

However, I do not see a reason why the output of  `pr.root_path` and `pr.project_path` should change if `project_check_enabled` is changed! The behavior of restricting access to not known paths is the only expected change in my opinion.

**Comment by liamhuber** [comment]
I think we had even talked at some point about getting rid of this check entirely-- this was my motivation for setting the default to false a couple prs ago (had to hotfix that back). But indeed to get rid of it we'll first have to disentangle a bunch of other behavior. I am in favor though

**Comment by jan-janssen** [comment]
I am also in favor of removing it completely.

**Comment by liamhuber** [comment]
Super! With the three of us on the same page I imagine we have (or can build) consensus around that perspective. As Niklas showed, actually disentangling this value from the rest of the code base might be a bit trickier.

**Comment by niklassiemer** [comment]
As we discussed also in #541 we agreed on:
- setting `project_check_enable=False` as the default
- disentangling the `root_path`-`project_path` split from the `project_check_enable` setting.

I will give it s shot tonight :)
