### ISSUE TITLE
Create job name automatically

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_base#549]
It would be nice to replace `create_job` by:

```python
def create_job(name, *args, delete_existing_jobs=..., ...):
    return name + "_".join(map(some_sanitizer(args))
```

Function suggested by @pmrv  

`some_sanitizer` should do
- Replacement of special symbols (`+`, `.` etc.)
- Rounding up of floating points `5.00000000000000004`

So in total, it should be like

```python
job = pr.create.job.SomeJob('run', lattice_parameter, temperature, pressure, box_repeat, index)
```

**Comment by niklassiemer** [comment]
I would rather go into the direction
```python
job = pr.create.job.JobType('some_name', 1.2 , "big", delete_existing_job=..., ...)
print(job.name)
>>> some_name_1_2_big
```
EDIT: you already updated your post 😅 
I would then suggest to change the function name to `create_job_name` and then call this on all the `*args` provided to `create.job.JobType(...)`

**Comment by samwaseda** [comment]
Yeah @niklassiemer I guess we are on the same page.

**Comment by max-hassani** [comment]
Instead of `pr.create.job.JobType('some_name', 1.2 , "big", delete_existing_job=..., ...)`, I suggest to have:
```python
pr.create.job.JobType(job_name=['some_name', 1.2 , "big"], delete_existing_job=..., ...)
```
This way the docstring would be more clear, and the user knows what to pass in.

**Comment by liamhuber** [comment]
I took a stab at this by [subclassing off `str`](https://github.com/liamhuber/FeAl_solution/blob/51f9bf5ac69ef4fee26153c154dc6fad16a1d880/pyiron_feal/utils.py#L27). At the very least we really need to centralize our replacement of '.' and '-' either by a function call or casting input names as a class.

I also like Muhammad's idea of passing in a list. Parsing beyond filtering down floats/etc will be tricky though -- a lot of settings we loop over are probably not trivially supportable, e.g. I don't think we want to write a parser to automatically extract a name from an `Atoms` object. 

Also, some experience from going even a little ways down this route, I found that I quickly ran out of characters...

**Comment by samwaseda** [comment]
> I also like Muhammad's idea of passing in a list. Parsing beyond filtering down floats/etc will be tricky though -- a lot of settings we loop over are probably not trivially supportable, e.g. I don't think we want to write a parser to automatically extract a name from an `Atoms` object.

I might simply rely on whatever `def __str__` of the class returns. Maybe it's time for us to create one in the `Atoms` class. So in principle it could something like this behind the scenes:

```python
job_name_update = ('_'.join([str(item) for item in job_name])).replace('-', 'm').replace('+', 'p').replace('.', 'd')
```

Although I have to admit that rounding up of floating points could be slightly tricky.

Here, I simply put `replace` one after another, but I think ideally there should be a dictionary.
