### ISSUE TITLE
Creating a pyiron_base.Project before a pyiron.Project breaks job type completion

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_base#55]
Creating a `pyiron_base.Project` instantiates the `pyiron_base.JobTypeChoice` singleton.  At that point only the base job types are in `JOB_CLASS_DICT` and these job classes are then defined on the `JobTypeChoice` singleton during `__init__`.
https://github.com/pyiron/pyiron_base/blob/187811476dfb68156d1cf14e50f6c045df5de6d3/pyiron_base/job/jobtype.py#L51
When importing `pyiron` later and instantiating a `pyiron.Project`  the `JOB_CLASS_DICT` gets updated with the new classes, but they are never set on the `JobTypeChoice` singleton again.  This leads to the confusing situation where the new job classes are properly tab-completed, but not actually defined, giving an error as below.

```python
import pyiron_base
pb = pyiron_base.Project('asdf')
import pyiron
pr = pyiron.Project('foo')
pr.create_job(pr.job_type.ExampleJob, 'example')
> AttributeError: 'JobTypeChoice' object has no attribute 'ExampleJob'
```

**Comment by jan-janssen** [comment]
This was working before: 
https://github.com/pyiron/pyiron-meeting/blob/master/2020-05-15/jan-janssen/modular_jobtype.ipynb

**Comment by jan-janssen** [comment]
But: 
```
dir(pr.job_type)
```
still lists all.

**Comment by pmrv** [comment]
Yes, `dir(pr.job_type)` list all jobs, because it list all keys in `JOB_CLASS_DICT`
https://github.com/pyiron/pyiron_base/blob/187811476dfb68156d1cf14e50f6c045df5de6d3/pyiron_base/job/jobtype.py#L58
But if the dict was updated in between the `__init__` call and the `__dir__` call the new job classes are not set as attributes on the `JobTypeChoice` singleton.
