### ISSUE TITLE
Remove dtype=object warnings

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_base#553]
We have multiple location in the code that raise a numpy warning when converting arrays to `dtype=object` implicitely.  For now we often silence the warnings like in #551, but we should future-proof the code at some point.

**Comment by samwaseda** [comment]
python does not complain with the following code:
```python
import numpy as np

class Foo:
    bar = 42
    
f = np.array([1, 2, Foo(), Foo(), 5], dtype=object)
```

and `print(f.dtype)` return `'O'`
