### ISSUE TITLE
JobFactory should be callable

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_base#564]
The old interface for job creation allowed to provide custom classes to create, like
```python
j = pr.create_job(MyJob, 'my_job')
```
but because the new `JobFactory` is not callable this cannot be emulated in the new interface.  For feature parity this should be added.

**Comment by pmrv** [comment]
Ah, I didn't see that @liamhuber is already working on it :+1:

**Comment by liamhuber** [comment]
I'll link the or here on Monday and hopefully merge early next week

**Comment by liamhuber** [comment]
Oops, on my phone I didn't notice Niklas had already tagged it! Anyhow, the PR is open now.
