### ISSUE TITLE
Is there an option to have pyiron read and write all data (settings, database, ...) in the current working directory?

### ISSUE THREAD

**Issue by s4b7r** [pyiron/pyiron_base#589]
**Summary**

Is there an option to have pyiron read and write all data (settings, database, ...) in the current working directory instead of using the user's home or other absolute paths?

**Detailed Description**

For development and debugging it would be nice to configure pyiron in a way that pyiron.db and ~/.pyiron are not read or written in the user's home or any other absolut paths. I think, this should ideally be done via an API call, not using configuration files, environment variables, etc.

My goal would be to have all files pyiron touches in one directory. In the best case this could be specified in one API call and relative to cwd.

Furthermore, it is currently unclear to me whether pyiron uses other absolute paths to store settings, databases, etc. If that's the case, my suggestion would extend from pyrion.db and ~./pyiron to all other absolute paths used.

**Comment by s4b7r** [comment]
Sorry, I lost track of this issue. I can confirm that this works for me.

> One update here, with the new [`pyiron_base` version](https://github.com/pyiron/pyiron_base/releases/tag/pyiron_base-0.4.2) we make `project_check_enabled=False` the default. So it should be possible to just use:
> 
> ```python
> from pyiron import Project
> pr = Project(path='your_proj')
> pr.state.update({
>     'sql_file': './pyiron.db',
>     'sql_type': 'SQLite',
> })
> ```

**Comment by ligerzero-ai** [comment]
Actually, after playing around with the project-database configuration, I have found that it is somewhat unsatisfactory - 
```
from pyiron import Project
pr = Project(path='your_proj')
pr.state.update({
    'sql_file': './pyiron.db',
    'sql_type': 'SQLite',
})
```
calling pr.job_table() afterwards yields an empty job_table. What I find is that you must then re-instantiate the project with:
```
pr = Project(path='your_proj')
pr.job_table()
```
at which point it finally generates the proper expected behaviour. I would imagine that this would make life very inconvenient when you have custom-written functions which rely on calling jobtables for certain data (i.e. job_name list).

This strikes me as very unusual behaviour.
Does anyone know why this could be the case?

**Comment by liamhuber** [comment]
@ligerzero-ai what is "the proper expected behaviour" precisely here? I definitely agree there ought to be no need to reinstantiate the project. I think we can break this down a little though, as you can first check whether the state update is working correctly, and later check whether project is talking to the state correctly:

```python
from pyiron_base import state
config = state.settings.configuration.copy()
state.update({
    'sql_file': './my_other_database.db',
    'sql_type': 'SQLite',
})
# check if the database is the one you want
state.update(config)
# check to make sure it goes back to the original thing OK
```

`Project.db` just directly returns `state.database.database` and `Project.job_table` just directly references `self.db.job_table`, so I'm very suspicious the problem is with state itself and not with how project talks to it.

**Comment by ligerzero-ai** [comment]
Sorry, the intended behaviour is that there are actually entries in the job_table() of the project. (As I had imported some calcs into the new database).
```
from pyiron_base import state
config = state.settings.configuration.copy()
state.settings.configuration
```
yields
```
{'user': 'hmai',
 'resource_paths': ['/cmmc/u/hmai/pyiron-resources-cmmc',
  '/cmmc/u/system/SLES12/soft/pyiron/dev/anaconda3/share/pyiron'],
 'project_paths': ['/cmmc/u/'],
 'connection_timeout': 60,
 'sql_connection_string': None,
 'sql_table_name': 'jobs_cmmc',
 'sql_view_connection_string': None,
 'sql_view_table_name': 'jobs_cmmc_admin',
 'sql_view_user': 'cmmc_view',
 'sql_view_user_key': 'REPLACED',
 'sql_file': '/cmmc/u/hmai/pyiron.db',
 'sql_host': 'pyiron-db-cmmc.esc.rzg.mpg.de',
 'sql_type': 'Postgres',
 'sql_user_key': 'REPLACED',
 'sql_database': 'pyiron',
 'project_check_enabled': False,
 'disable_database': False,
 'credentials_file': None,
 'write_work_dir_warnings': True,
 'config_file_permissions_warning': True}
```
```
state.update({
    'sql_file': './my_other_database.db',
    'sql_type': 'SQLite',
})
state.settings.configuration
```
yields 
```
{'user': 'pyiron',
 'resource_paths': ['/cmmc/u/system/SLES12/soft/pyiron/dev/anaconda3/share/pyiron'],
 'project_paths': [],
 'connection_timeout': 60,
 'sql_connection_string': None,
 'sql_table_name': 'jobs_pyiron',
 'sql_view_connection_string': None,
 'sql_view_table_name': None,
 'sql_view_user': None,
 'sql_view_user_key': None,
 'sql_file': '/cmmc/u/hmai/project-NiGBs-New/mem_leak/my_other_database.db',
 'sql_host': None,
 'sql_type': 'SQLite',
 'sql_user_key': None,
 'sql_database': None,
 'project_check_enabled': False,
 'disable_database': False,
 'credentials_file': None,
 'write_work_dir_warnings': True,
 'config_file_permissions_warning': True}
```
and finally:
```
state.update(config)
state.settings.configuration
```
yields:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/xpython_10377/2112660919.py in <cell line: 1>()
----> 1 state.update(config)
      2 state.settings.configuration

/cmmc/u/hmai/github_dev_pyiron/pyiron_base/pyiron_base/state/__init__.py in update(self, config_dict)
     75                 the configuration from system environment xor configuration files.)
     76         """
---> 77         self.settings.update(user_dict=config_dict)
     78         _queue_adapters.update()
     79         self.database.update()

/cmmc/u/hmai/github_dev_pyiron/pyiron_base/pyiron_base/state/settings.py in update(self, user_dict)
    133         file_dict = self._get_config_from_file()
    134         if user_dict is not None:
--> 135             user_dict = self._add_credentials_from_file(user_dict)
    136             self._update_from_dict(user_dict)
    137         elif env_dict is not None:

/cmmc/u/hmai/github_dev_pyiron/pyiron_base/pyiron_base/state/settings.py in _add_credentials_from_file(self, config)
    384             credential_file = config["credentials_file"]
    385 
--> 386         if not os.path.isfile(credential_file):
    387             raise FileNotFoundError(credential_file)
    388         credentials = (

/cmmc/u/system/SLES12/soft/pyiron/dev/anaconda3/lib/python3.8/genericpath.py in isfile(path)
     28     """Test whether a path is a regular file"""
     29     try:
---> 30         st = os.stat(path)
     31     except (OSError, ValueError):
     32         return False

TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```
