### ISSUE TITLE
I want to contribute, open for suggestions

### ISSUE THREAD

**Issue by Ovakefali13** [pyiron/pyiron_base#590]
**Summary**

I want to contribute to pyiron as part of my studies at university. Do you have any suggestions on topics and/or features I might be able to contribute?

**Detailed Description**

Hi,
I'm currently enrolled in a Masters' Degree of Computer Science at the University of Stuttgart. For the course "Simulation Software Engineering" we are supposed to contribute to a open source software project and follow the steps. Therefore, I want to help. As a Computer Scientist I don't have any real Physics, Chemics, or Engineering (apart from Software Engineering and Social Engineering ;-) background, but I'm eager to learn. Since I don't want to randomly edit some files in order to fix some typos and stuff, but rather contribute something productive, I'm open to suggestions on what might be a good improvement to the pyiron project. 

**Further Information, Files, and Links**

I'm mostly working in a windows 10 environment, but have a Ubuntu VM installed. Windows subsystem 2 is installed, but I couldn't get pyiron running there (maybe creating an issue later, with the error I get executing the basic example), so I tried the VM and it worked there. As said, I'm no Simulation Scientist and quite new to the topic in general so I ran the few provided examples, got some nice graphs, but couldn't really interpret the results :)

**Comment by Ovakefali13** [comment]
@jan-janssen Thank you very much, this helped me a lot for my paper and for understanding how the packages get build and are distributed.

**Comment by jan-janssen** [comment]
Great - Maybe you can extend https://github.com/pyiron/pyiron_base/blob/master/CONTRIBUTING.rst#pyiron-releases to make everything more clear for new people who join the project.
