### ISSUE TITLE
Is JobCore.get_pandas really needed?

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_base#592]
This function 

https://github.com/pyiron/pyiron_base/blob/7003bd1c03d4e6632d56a336fd91e0951687ea2d/pyiron_base/job/core.py#L384

just delegates to `job.project_hdf5.get_pandas` and does nothing else. I've also never seen it used anywhere.

Since it's on `JobCore` almost every object in pyiron has that method, so it takes up a good amount of tab-complete real estate and is sometimes even actively confusing, e.g. on pyiron tables.  There you need to call `get_dataframe` instead, but `get_pandas` also pops up, so users need to double check with the docstring to get the correct one.

**Comment by jan-janssen** [comment]
I guess it is one of the loose ends from an rather old pyiron version so I am fine with removing it.
