### ISSUE TITLE
Outdated Link in CONTRIBUTING.rst

### ISSUE THREAD

**Issue by Ovakefali13** [pyiron/pyiron_base#599]
In the [CONTRIBUTIN.rst](https://github.com/pyiron/pyiron_base/blob/master/CONTRIBUTING.rst#pyiron-releases) the link [https://github.com/pyiron/pyiron_base/blob/master/.travis.yml](https://github.com/pyiron/pyiron_base/blob/master/.travis.yml) seems to be outdated.

**Comment by jan-janssen** [comment]
Oh ok - Can you update it? We are now using GitHub Actions - they are defined in https://github.com/pyiron/pyiron_base/tree/master/.github/workflows and we should definitely be more explicit in discussing the different GitHub Actions we defined. So maybe you can take a look and try to understand what these actions are doing and how they are different and I and also @niklassiemer can give feedback about the details. Finally the corresponding links to the status of the GitHub Actions is already included in the README 
https://github.com/pyiron/pyiron_base#readme

**Comment by Ovakefali13** [comment]
I will take a look and will create a PR, but due to holidays this might take some time ;-)
