### ISSUE TITLE
Why is the conversion of `.` -> `_` done only when the job is loaded?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_base#616]
https://github.com/pyiron/pyiron_base/blob/adb7b978ea1636b76701e5c464d070aa27847ae4/pyiron_base/database/jobtable.py#L138

I don't understand why this conversion is done only when the job is loaded. Is it meant to be applied on the job name that the user gives, or something that pyiron appends internally?

**Comment by samwaseda** [comment]
@jan-janssen

**Comment by jan-janssen** [comment]
I guess we can remove it - just like you did in the pull request.
