### ISSUE TITLE
Is there a way to see (disk space) size of project?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_base#630]
It sometimes depends on the size of a project (or its jobs) whether I launch new calculations while keeping the old ones or by erasing them, it would be super helpful to know it inside pyiron. Is there a way to do so?

**Comment by jan-janssen** [comment]
You can use `os.path.getsize()` for example: 
```
import os
folder = "/Users/jan/pyiron/projects/2022"

size_in_mb = sum([
    sum([
        os.path.getsize(os.path.join(path, f)) 
        for f in files
    ]) 
    for path, dirs, files in os.walk(folder)
]) / 1024 / 1024 
print(size_in_mb)
```

**Comment by samwaseda** [comment]
Ok if this is the only one solution it's easier for me to go the terminal solution. Shouldn't this be implemented in pyiron?

**Comment by liamhuber** [comment]
@niklassiemer how will this interact with an s3 storage backend? Will we be able to implement something similar so we have cross-storage reading? Should we consider parsing the output as "local" and "remote" storage already?

**Comment by niklassiemer** [comment]
So far, we do not have an S3 project. Indeed, I assume S3 will rather function as Archive solution/ intermediate storage than as fast access storage to receive data to analyze. However, it should be possible to get a similar call implemented for S3. 
If we abstract `Project` this far that we have different storage locations, we would need to rethink Project.size in general, again. Just consider storing a few jobs on a storage in Aachen, some on the normal file system, and some on another HPC... 

Thus, I would go for an easy solution now and add functionality and categories once we need them.
