### ISSUE TITLE
Behavior for remotely executed jobs

### ISSUE THREAD

**Issue by niklassiemer** [pyiron/pyiron_base#64]
First of all, I was finally able to set up a remote cluster for computations. 
Maybe we should emphasis, that in the configuration ist is not possible to use any hostname defined in .ssh/config but one has to give the actual hostname and username. Since I am using port forwarding this looks like 
ssh_host: localhost
ssh_port: 2101
of which the second option was not documented.
For someone, who worked with compute clusters and queueing systems quite a while, I miss the transparency of the remote execution. 
First I was stuck, since I did not find a way to get my results back. Commands like `job.refresh_job_status()` do not refresh the job status from the remote cluster, which was somehow the behavior I expected.
Finally, re-executing of the notebook helped, since `job.run()` uses in this case `job._run_if_submitted` and finally loaded the results.
While my job was submitted, I also tried to get information on the job status from the queuing system. I tried to use
`project.queue_table()`, however, I always got an '_' as result. Maybe the actual computation was already done, or am I using this command in the wrong context?

**Comment by jan-janssen** [comment]
I agree the commands are currently a bit confusing as commands like `refresh_job_status()` are commonly only used internally to get the job status from the database. The commands which support remote access are:

- `pr.wait_for_jobs()`
- `pr.wait_for_job(job)`
- `pr.iter_jobs()`

https://github.com/pyiron/pyiron-meeting/blob/master/2020-08-28/jan-janssen/different_remote_usecases.ipynb

**Comment by jan-janssen** [comment]
In the end it comes back to the issue that we have three level of access: 

- Access within one class to functions of this class in python these functions can be hidden using `_function_name()`
- Access from one class to the functions of another class, python recommends these functions to be public. 
- Access from the pyiron user to a function of a pyiron object. 

Currently I see two ways to address this, either we write wrapper classes around each object, but this makes it more complicated to debug or we use hidden functions for object to object interactions but that is contrary to the python recommendations.

**Comment by niklassiemer** [comment]
Well hiding internal functions for the most important objects, i.e. job and project only such that only the functions for the user are shown would be also helpful to avoid thinks like https://github.com/pyiron/pyiron/issues/1097 .
I think, in principle I was looking for `pr.update_from_remote()` to download my finished results as I tried `refresh_job_status()`

**Comment by niklassiemer** [comment]
Since my question is essentially answered, I will close this now.
