### ISSUE TITLE
Mpi4py enable flag does not work as expected

### ISSUE THREAD

**Issue by niklassiemer** [pyiron/pyiron_base#712]
Looking at the code, I just recognized:
```
from pyiron_base import Project
pr = Project('.')
job = pr.create.job.ScriptJob('name')
job.script_path= './script.py'
job.enable_mpi4py()
job.server.cores = 10
job.executable
>>>['mpirun', '-np', '1', 'python', '/mnt/c/Users/Siemer/pyiron/projects/name_hdf5/name/script.py']
```
Thus, how many cores are used depends on the order of execution!

**Comment by jan-janssen** [comment]
The number of cores should be updated when the run command is called, is not it? You should be able to check it by setting the run mode to manual and then validate the executable afterwards - **OK it does not work**
