### ISSUE TITLE
What's the difference between `pop` and `__getitem__`? 

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_base#752]
https://github.com/pyiron/pyiron_base/blob/beb94956c1fec341d38ead191bb1dd61c3180dca/pyiron_base/master/generic.py#L221

Now I realised that [this PR](https://github.com/pyiron/pyiron_atomistics/pull/588) is failing because `pop` does something that `__getitem__` doesn't do. In this particular case, `ref_job_initialize()`, which is used in `SxExtOpt`, performs `pop`, which breaks the tests, while the same tests do just fine with `__getitem__`, which is used when `ref_job` is `None`. I would have expected that `pop` is just `__getitem__` + `del`, but in `generic.py` these two functions look fairly different. Can someone explain why we need to use `pop` in `ref_job_initialize` of `interactivewrapper.py` and not `__getitem__`?

**Comment by jan-janssen** [comment]
If I remember correctly the `pop` is used to initialize the instance of the child job for execution, while `__getitem__` just reloads the child job.

**Comment by samwaseda** [comment]
Ok but I still struggle to understand what these lines inside `pop` do:

```python
job_to_return.project_hdf5.remove_group()
job_to_return.project_hdf5 = self.project_hdf5.__class__(
    self.project, job_to_return.job_name, h5_path="/" + job_to_return.job_name
)
if isinstance(job_to_return, GenericMaster):
    for sub_job in job_to_return._job_object_dict.values():
        self._child_job_update_hdf(parent_job=job_to_return, child_job=sub_job)
```

I'm asking this mainly because these guys are apparently the ones that are causing problems [in this PR](https://github.com/pyiron/pyiron_atomistics/pull/588).
