### ISSUE TITLE
Would it be theoretically possible to create one storage variable?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_base#754]
We've been asking people to write their own `from_hdf` and `to_hdf` whenever they create a new class, in which the stuff always looks like this:

```python
def from_hdf(self, hdf, group_name):
    self.input.from_hdf(hdf=hdf, group_name=group_name)
    self.output.from_hdf(hdf=hdf, group_name=group_name)
```

Here, not only I don't really see what it's doing, but I find it also really redundant, because we do almost the same things everywhere. Instead, we started offering with the `TemplateJob` [on our website](https://pyiron.org) the possibility to hide these ones for input and output. I was wondering whether we could totally hide `to_hdf` and `from_hdf` by default everywhere, by doing something like:

```python
class GenericJob(JobCore):
    def __init__(self, project, job_name):
        blablabla
        self._storage = DataContainer()
        self._storage.create_group('input')
        self._storage.create_group('output')
        blablabla

    @property
    def input(self):
        return self._storage.input

    @input.setter
    def input(self, v):
        raise ValueError('input cannot be overwritten')

    @property
    def output(self):
        return self._storage.output

    @output.setter
    def output(self, v):
        raise ValueError('output cannot be overwritten')

    def to_hdf(self, hdf, group_name):
        self._storage.to_hdf(hdf=hdf, group_name=group_name)

    def from_hdf(self, hdf, group_name):
        self._storage.from_hdf(hdf=hdf, group_name=group_name)

```

and we put everything in `self._storage`. Then the example on the website will look like this:

```python
from pyiron_base import GenericJob

class ToyJob(GenericJob):  # Create a custom job class
    def __init__(self, project, job_name):
        super().__init__(project, job_name)
        self.input.energy = 100  # Define default input

    def run_static(self):  # Call a python function and store stuff in the output
        self.output.double = self.input.energy * 2
        self.status.finished = True

job = pr.create_job(job_type=ToyJob, job_name="toy")  # Create job instance
job.run()  # Execute Custom job class
```

And not only input and output, I'd like to store **everything** inside `self._storage`, so that to and from hdf will be essentially only storing and recovering `self._storage`. This would allow us to get rid of all the to and from hdf that we've written in the child classes.

Of course, I understand that it's not only not incompatible with `GenericParameters` (at least I guess it's not) but also it will break a lot of backward compatibility, but I think this would be the first step to make pyiron more meaningful as a simulation framework.

Let me know if you see a problem in principle. If it should be possible, I'll take care of it as soon as I start working on MatDig.

**Comment by pmrv** [comment]
This is the vision for `HasStorage`, which @liamhuber wrote and I've been pushing on new (job) classes.  Imo the plan should be to derive `TemplateJob` from it, move all jobs over to it and then rename it to `GenericJob`.

**Comment by samwaseda** [comment]
> This is the vision for `HasStorage`, which @liamhuber wrote and I've been pushing on new (job) classes. Imo the plan should be to derive `TemplateJob` from it, move all jobs over to it and then rename it to `GenericJob`.

Yeah we had a discussion on this yesterday, and I should have more emphasised that I want to put **everything** inside `self._storage`, meaning there shouldn't be any other communication between pyiron and hdf. It looks like there's nothing preventing us from doing so, so I'll start working on it as soon as my new contract starts.
