### ISSUE TITLE
run() does not raise an error when called on an aborted job.

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_base#770]
Instead it just silently returns.

**Comment by jan-janssen** [comment]
Is not this expected?

**Comment by pmrv** [comment]
I just find it annoying when that happens, e.g. you have the job declaration and the input specification in two different cells.  While developing the workflow you change the input, but forget to run both cells.  As a result nothing happens, but there is also no indication of this.  Conversely if a job ran successfully you do get a warning that the job was not re-run.  So a warning or error is more consistent in my opinion.
