### ISSUE TITLE
`run_job.py` does not exist in `job.server.run_mode.manual = True`

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_base#777]
```python
vasp = pr.create.job.Vasp('test')
vasp.structure = pr.create.structure.bulk('Al')
vasp.server.run_mode.manual = True
vasp.run()
```

This code gives the message:

*The job test was saved and received the ID: XXX*
*You have selected to start the job manually. To run it, go into the working directory working_directory/test_hdf5/test and call 'python run_job.py'*

But I cannot find `run_job.py` in the directory. Where is it?

**Comment by pmrv** [comment]
The correct way to do it is given by
`"python -m pyiron_base.cli wrapper -p {}".format(abs_working) + " -j {}".format(self.job_id)`
as was printed prior to #762.  I'm guessing something went wrong there copying things around.

**Comment by niklassiemer** [comment]
Yes, we have two functions on the `GenericJob`, 
https://github.com/pyiron/pyiron_base/blob/d4f57c36affa9d69efc9ea121f582f3da247bc1c/pyiron_base/job/generic.py#L1232-L1239
and 
https://github.com/pyiron/pyiron_base/blob/d4f57c36affa9d69efc9ea121f582f3da247bc1c/pyiron_base/job/generic.py#L875-L883
of which only the second one seems to be used at all. However, the print statement was copied from the first function...
