### ISSUE TITLE
`job.status` is set to aborted if `validate_ready_to_run()` fails

### ISSUE THREAD

**Issue by niklassiemer** [pyiron/pyiron_base#782]
Currently, the `job.status` is set to `aborted` since `validate_ready_to_run()` raises a `ValueError`.

**Comment by samwaseda** [comment]
Is it a problem?

**Comment by niklassiemer** [comment]
Well, I think it is very inconvenient if one sets up a calculation, tries to `run` and the only thing which changes is the `job.status`. I would like to just `job.set_missing_thing()` and `job.run()`?

**Comment by samwaseda** [comment]
but `job.run()` raises an error with a clear message, right? Can you post a specific example?

**Comment by niklassiemer** [comment]
To be clear, `validate_ready_to_run()` should raise a `ValueError` in the current case!

**Comment by samwaseda** [comment]
Hm there's something I'm not understanding... Are you saying there are cases where `validate_ready_to_run()` does not raise `ValueError`?

**Comment by niklassiemer** [comment]
The `validate_ready_to_run()` raises an `ValueError` or `pass`es. However, with #770 it is quite odd since
```python
from pyiron_atomistics import Project

pr = Project('ToBeRemoved')
job = pr.create.job.Lammps('lmp')
job.run()
>>> ValueError: This job does not contain a valid structure: lmp
```
and afterwards
```python
job.structure =  pr.create.structure.bulk('Al')
job.run(delete_existing_job=True)
```
does only `return None`.

**Comment by niklassiemer** [comment]
As discussed, the issue is that `delete_existing_job` only works when there is a `job_id` - Fix coming
