### ISSUE TITLE
Is load_from_jobstring_path necessary?

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_base#821]
https://github.com/pyiron/pyiron_base/blob/9970503c12f4b5389c284c44cb22f04a32648790/pyiron_base/project/generic.py#L1222

I did a quick grep through our repositories and cannot find it being used.  Given our discussion on last Monday I'm inclined to remove it.  I'll do it later this week if no one speaks up.

**Comment by jan-janssen** [comment]
I agree that it is currently not used, but I really like the functionality. Basically I want to be able to load any pyiron object by just specifying the path where it is stored on the file system without the need to check the database. In particular for high performance application where potentially hundreds of jobs are started at the same time, it is helpful to load the job directly without looking it up in the file table. I though I used it in the worker job at some point but this seems to be no longer the case - or those changes were never merged.

**Comment by pmrv** [comment]
Ok, I'll try to keep it as an extra constructor around then.
