### ISSUE TITLE
ProjectData should be lazy by default

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_base#835]
It's probably enough to set the lazy flag in the overridden `__init__` and add some tests.

https://github.com/pyiron/pyiron_base/blob/master/pyiron_base/project/data.py

**Comment by yasser-sulaiman** [comment]
Hello, I am new to pyiron and contribution to open source projects and I want to work on this

**Comment by jan-janssen** [comment]
Hi @yasser-sulaiman, 

Welcome to the pyiron project, we are always happy to have new contributors join the project. So if we need anything from our side to help you get started, do not hesitate to ask. 

Best, 

Jan

**Comment by yasser-sulaiman** [comment]
Making ProjectData lazy by default can be achieved by two ways:
* Changing the default value of lazy from False to True in DataContainer Class but that would change the default behavior of other classes that might inherit from this class. or
* Overriding the lazy flag in the ProjectData class which won't effect other classes.

should I create a pull request with one of these?
