### ISSUE TITLE
Status is not updated when job hits walltime

### ISSUE THREAD

**Issue by ligerzero-ai** [pyiron/pyiron_base#857]
Jobs currently do not have their status updated to become "aborted" when they hit walltime:

Proposed fix: add a call to pr.refresh_job_status() in the job table which can be turned on or off in the pr.job_table()

**Comment by ligerzero-ai** [comment]
"Fixed" with pull #858 

To avoid this problem, we call:
pr.job_table(auto_refresh_job_status = True)

**Comment by jan-janssen** [comment]
@ligerzero-ai Can you check if https://github.com/pyiron/pyiron_base/pull/1341 helps to solve this issue? Now the job status should be automatically set to `aborted` when the wall time limit is reached, as we catch the signal which kills the job.
