### ISSUE TITLE
Question about pyiron table

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_base#874]
So far I have never used pyiron table for real applications. Now I started looking more into details and realized that there's either `delete_existing_job=True`, in which case I run the whole process from the beginning, or otherwise the job is fixed and there's nothing I can do (just like the normal jobs). I always thought table job can append new jobs without running it for the already evaluated ones if there are more data available on the database, as for example new jobs finish or so. That's actually not the case?

**Comment by pmrv** [comment]
It's supposed to be the case, but broken.  I think @Leimeroth has an issue somewhere.  We simply never got around to it.

**Comment by samwaseda** [comment]
aha, I see it [here](https://github.com/pyiron/pyiron_base/issues/768), but there it's about adding a new function. Are we supposed to be able to add new data point (i.e. more jobs) as well?

**Comment by pmrv** [comment]
Both would be good to have without recalculating what is already there.  I seem to remember that there is some logic already there.
