### ISSUE TITLE
`collect_output` defined in `SerialMaster` while not in `ParallelMaster`

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_base#891]
https://github.com/pyiron/pyiron_base/blob/cb3884c1ab1a353f63ce3442bef5d2f33c432e81/pyiron_base/jobs/master/serial.py#L252-L271

In `SerialMaster`, there's `collect_output` that collects the generic output, while in `ParallelMaster` it's `NotImplementedError`. I'm fine with both but we should agree on one of them.

**Comment by niklassiemer** [comment]
I am fine with collecting the most generic output already on that level. That way we can actually start calling `super` in subclasses.

**Comment by samwaseda** [comment]
I decided to do it directly in [this PR](https://github.com/pyiron/pyiron_base/pull/870)
