### ISSUE TITLE
Does distinction between `ParallelMaster` and `SerialMaster` matter?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_base#896]
From the conceptual point of view, the only one difference is whether the input of the subsequent job depends on the current job, right? Shouldn't it be up to the job generator to determine it?

**Comment by jan-janssen** [comment]
No, in the parallelMaster all child jobs can be executed in parallel, while in the serialmaster the calculation depend on each other, so they have to be run in serial. So to me these are fundamental differences.

**Comment by samwaseda** [comment]
> No, in the parallelMaster all child jobs can be executed in parallel, while in the serialmaster the calculation depend on each other, so they have to be run in serial. So to me these are fundamental differences.

I don't see how this argument makes them **fundamentally** different. In the one case the jobs have to wait for each other, in the other case not. Especially in the interactive mode there's no difference at all. So I would have claimed there should be maybe only a few lines of code that should differ in the two cases.

**Comment by samwaseda** [comment]
Maybe I'm gonna put it in a different way: I don't see how to justify the differences below:

Input:
- `ParallelMaster`: `job.input`
- `SerialMaster`: `job._input`

Child job:
- `ParallelMaster`: `job.ref_job`
- `SerialMaster`: `job.start_job`

Output:
- `ParallelMaster`: `NotImplementedError`
- `SerialMaster`: Collects generic output of all child jobs

Interactive:
- `ParallelMaster`: Implemented - launches jobs serially
- `SerialMaster`: Not implemented

Function to generate jobs:
- `ParallelMaster`: `job._job_generator.modify_job`
- `SerialMaster`: `job._convergence_goal`

Job generator setter:
- `ParallelMaster`: By using `ParallelMaster` as template (or by setting `job._job_generator`)
- `SerialMaster`: Via `job.set_goal`

Job generator:
- `ParallelMaster`: Class (`JobGenerator`)
- `SerialMaster`: Function (`job._convergence_goal`)

Creation of the next job:
- `ParallelMaster`: Combination of `job_name` and `next` inside `JobGenerator` and `job.create_child_job`
- `SerialMaster`: `job.create_next`

`__len__`:
- `ParallelMaster`: `len(self.child_ids)`
- `SerialMaster`: `len(self.child_ids + self._job_name_lst)`

`job.ref_job`:
- `ParallelMaster`: Spawn first job in the list
- `SerialMaster`: Spawn last job in the list

Numerous other functions that exist in one class but not in the other (which can from my point of view exist in both classes or not at all):
- `ParallelMaster`: `convergence_check`, `number_jobs_total`, `output_to_pandas`, `show_hdf`
- `SerialMaster`: `get_initial_child_name`, `show`

Numerous other functions that do exactly or nearly the same in both classes, but are defined separately:
- `collect_logfiles`, `__getitem__`, `ref_job`, `set_input_to_read_only`, `to_hdf`, `from_hdf`, `write_input`, `_init_child_job`, `iter_jobs`


I listed the items that came to my mind - there are certainly more of them that I didn't even notice. Most importantly, some differences are directly connected to user experience (like the job generator definition), which makes the switching between `ParallelMaster` and `SerialMaster` very difficult. Moreover, as I pointed out above, we are wrong to claim that the jobs run in parallel in `ParallelMaster`, because they run serially in the interactive mode, so we don't even follow the basic principle of the two classes.

**Comment by samwaseda** [comment]
Following yesterday's discussion, we decided to create a new Master class, which will combine all the existing master classes, so I close this issue.
