### ISSUE TITLE
sending sqs jobs to queue

### ISSUE THREAD

**Issue by sinazadeh** [pyiron/pyiron_base#897]
I am trying to submit SQS jobs to the queue and I was wondering if this is the correct format for doing this. For VASP, I created a .sh file in the resources folder, should I do the same thing here?
```#!/bin/bash

##NECESSARY JOB SPECIFICATIONS
#SBATCH --job-name=jbname       
#SBATCH --time=01:30:00              
#SBATCH --ntasks=48                  
#SBATCH --mem=360G                  
#SBATCH --output=jbOut0.%j      

module purge
module load Anaconda3/2022.05
conda activate prnenvnew

{{command}}
```
```
structure_lattice = pr.create_ase_bulk(name="Al", cubic=True)
structure_lattice.set_repeat(3)
job_sqs = pr.create_job(pr.job_type.SQSJob, job_name="sqs")
job_sqs.structure = structure_lattice
job_sqs.input.mole_fractions = {"Al": 0.5, "Ni": 0.5}
job_sqs.server.queue = job.server.list_queues()[3]
job_sqs.run()
```

**Comment by pmrv** [comment]
The sqs jobs are run from within pyiron and therefore don't need additional bash scripts to run.  Anyways doing sending to the queue shouldn't be handled by the individual job scripts, but by the script to configure with `pysqa`.  It also comes with an example configuration for [SLURM](https://github.com/pyiron/pysqa/tree/master/tests/config/slurm).
