### ISSUE TITLE
What's FlexibleMaster?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_base#902]
Its doc string says:

> The FlexibleMaster uses a list of functions to connect multiple jobs in a series.

And it doesn't say anything about the actual functions (what kind of functions, how to set them etc.). By looking at the code, I got the feeling that it's nearly the same as `SerialMaster` - is there a particular reason that a separate file exists?

**Comment by liamhuber** [comment]
As far as I recall, the thing with `FlexibleMaster` was that you could do *any* sequence of `JOBS` and intermediate `function` calls, e.g. `AaBbCcDdEeFf`, whereas serial master just did the same thing repeatedly with some termination condition, i.e. `AaAaAaAaAa`. Let me see if I can dig up a place I used `FlexibleMaster` as an example. I have a strong memory of really liking it compared to `SerialMaster` though.

**Comment by liamhuber** [comment]
@samwaseda in #798 I show how this can be used to instantiate two totally different jobs and do math on their output to get something physically meaningful. I don't think this can be done with `SerialMaster`, but it's been forever since I looked at either so maybe I'm wrong about that.

**Comment by jan-janssen** [comment]
It is also used in the pipelines https://github.com/pyiron/pyiron_atomistics/blob/master/pyiron_atomistics/atomistics/master/parallel.py#L171 . An example of the pipeline job is available here https://github.com/pyiron/pyiron_atomistics/blob/master/notebooks/pipeline.ipynb

**Comment by liamhuber** [comment]
After a five minute peek at the source for each, it looks like my above comment is more or less correct. `SerialMaster` has the advantage of automatically producing new (very similar) jobs based on the "convergence" condition, while `FlexibleMaster` looks like it goes through a rigidly pre-defined set of steps (but those steps/jobs can all be different).

**Comment by samwaseda** [comment]
Ok that means the difference between `ParallelMaster`, `SerialMaster` and `FlexibleMaster` is:

- `ParallelMaster`: Run jobs for a set of parameters
- `SerialMaster`: Run jobs based on updates of one function
- `FlexibleMaster`: Run jobs based on updates of multiple functions

Based on this, can we think of making all masters in the way, that the user has to write a class like:

```python
class JobGenerator:
    def generate_job(self, job_to_return, counter):
        ....
        return job_to_return

    def to_hdf(self, **args):
        self.input.to_hdf(**args)
```

where `job_to_return` is generated internally by pyiron by:

`SerialMaster` and `FlexibleMaster`:

```python
counter = int(last_job.job_name.split('_')[-1])
job_to_return = last_job.restart(job_name='_'.join(last_job.job_name.split('_')[:-1] + [str(counter)])
```

`ParallelMaster`:

```python
job_to_return = ref_job.restart(job_name=ref_job.job_name + '_' + str(counter))
```

- The class must have `generate_job` and maybe optionally `to_hdf` and `from_hdf`?
- The parameters/functions are stored inside `JobGenerator` and not inside `XYZMaster`, although the jobs are stored inside `XYZMaster`
- `JobGenerator` is to be stored in `master.input.job_generator`?
- `generate_job` returns anything other than `GenericJob` (which means it can also be `GenericMaster`), e.g. `None` when the convergence is reached or all the parameters are set.

If we can unify this interface, I guess we can mostly unify the three classes (which means we can probably erase a lot of lines).

**Comment by jan-janssen** [comment]
The parallel master runs jobs in parallel (executing multiple calculation at the same time), while both the serial master as well as the flexible master execute jobs in serial. The difference between the later two is that the serial master has a convergence goal function to generate the following job based on the previous job. In contrast to this the flexible master is more flexible, it can even execute jobs of different types - like in the example of the pipeline, while the parallel master and the serial master can only execute child jobs of the same type.

**Comment by samwaseda** [comment]
> The parallel master runs jobs in parallel (executing multiple calculation at the same time), while both the serial master as well as the flexible master execute jobs in serial.

Yes, so `ParallelMaster` will continue existing, probably consisting of a few lines (just like `SerialMaster`).

> In contrast to this the flexible master is more flexible, it can even execute jobs of different types - like in the example of the pipeline, while the parallel master and the serial master can only execute child jobs of the same type.

Can you post the function? I don't see which part creates the jobs with different types.

**Comment by jan-janssen** [comment]
Can you post the function? I don't see which part creates the jobs with different types.

> It is also used in the pipelines https://github.com/pyiron/pyiron_atomistics/blob/master/pyiron_atomistics/atomistics/master/parallel.py#L171 . An example of the pipeline job is available here https://github.com/pyiron/pyiron_atomistics/blob/master/notebooks/pipeline.ipynb

**Comment by samwaseda** [comment]
> Can you post the function? I don't see which part creates the jobs with different types.
> 
> > It is also used in the pipelines https://github.com/pyiron/pyiron_atomistics/blob/master/pyiron_atomistics/atomistics/master/parallel.py#L171 . An example of the pipeline job is available here https://github.com/pyiron/pyiron_atomistics/blob/master/notebooks/pipeline.ipynb

???

**Comment by samwaseda** [comment]
If you are reposting it because it must be clear in the notebook, I'm sorry I don't see where it is, so please post the specific place where it's happening.

**Comment by samwaseda** [comment]
And to be honest calling a notebook "example" which has no explanation for how it works and what it does makes it only more confusing. I guess either it shouldn't exist or we should do something about it.

**Comment by liamhuber** [comment]
> If you are reposting it because it must be clear in the notebook, I'm sorry I don't see where it is, so please post the specific place where it's happening.

In #798 you can see where I take turns appending jobs to `self` and functions to `self.function_lst`, and the jobs are different -- in this case I just call methods that are instantiating jobs, and as far as `FlexibleMaster` is concerned such jobs can be of arbitrary type.

Edit: specifically in `_create_pipeline`, which is just a custom method I made for this subclass that gets called during `verify_ready_to_run`.

**Comment by samwaseda** [comment]
Do I see it correctly that in `FlexibleMaster` the jobs must be created beforehand, and not on the fly like in `ParallelMaster` and `SerialMaster`? Indeed my class idea above wouldn't work in that case. But at the same time, if we are anyway modifying the job on the fly, can't we do the whole process (including job creation) on the fly as well? So the example that you sent me following my example would have `generate_job` instead of `_create_pipeline`:

```python
class Solvation(FlexibleMaster):
    ....
    def generate_job(self, job_to_return, counter):
        if counter == 0: 
            return self._instantiate_ref()
        elif counter == 1:
            return _copy_positions_and_cell(self._instantiate_solute())
    ....
```

(ok it's not exactly the same because `_copy_positions_and_cell` modifies the new jobs based on the old job, but that's a small difference that can be easily implemented)

**Comment by jan-janssen** [comment]
The general idea behind the pyiron master classes is that the calculations which are executed by the master job are configured in the same way like individual calculations are configured. For example when I want to set the energy cut off for an energy volume curve calculation, then you would do it like this (pseudo code): 
```
job_template = pr.create.job.Vasp("test")
job_template.structure = structure 
job_template.set_encut(encut)

for strain in strain_lst: 
    job = job_template.copy_to(job_name="strain_" + str(strain)) 
    job.run()
```

Now the syntax for using a `Murnaghan` job is very similar: 
```
job_template = pr.create.job.Vasp("test")
job_template.structure = structure 
job_template.set_encut(encut)

murn = job_template.create.job.Murnaghan("murn")
murn.run()
```

The same advantage is also discussed in the virtual pyiron course: 
https://pyiron.org/phasediagram-workshop-2020/DensityFunctionalTheory.html
https://pyiron.org/phasediagram-workshop-2020/Exercise3.html

**Comment by samwaseda** [comment]
Following yesterday's discussion, we decided to create a new Master class, which will combine all the existing master classes, so I close this issue.
