### ISSUE TITLE
refresh_job_status doesn't actually update statuses when jobs have the statuses updated internally

### ISSUE THREAD

**Issue by ligerzero-ai** [pyiron/pyiron_base#906]
Found this when investigating https://github.com/pyiron/pyiron_base/pull/875

https://github.com/pyiron/pyiron_base/pull/875#issuecomment-1323535407

More for the developers;

When updating statuses manually for jobs in the internal code, it is not sufficient to update only the status through the internal job._status attribute.

e.g.
```
job._status = 'initialized'
```
or
```
job.status = 'aborted'
```
You also have to include an additional line:
```
self.project.db.item_update({"status": "aborted"}, self._job_id)
```
So that the database actually recognises your job with the new status.

You can verify this by calling `pr.job_table()` and verify that `refresh_job_status` doesn't actually update the status of the job.

So actually the `pr.refresh_job_status` functionality is leaky/buggy and does not hard-refresh all job_statuses based on jobs that have their statuses updated internally by methods.

I am not sure if this is intentional, but this means that there are certain places in the code where job statuses are not actually properly updated in the database. e.g.

https://github.com/pyiron/pyiron_base/blob/c7157b63e0710a6e5d3ab61b94a2f22e28371e21/pyiron_base/jobs/job/core.py#L778

**Comment by jan-janssen** [comment]
`job.status = 'aborted'` works when a database is connected.

**Comment by ligerzero-ai** [comment]
Yeah, but I am more talking about setting stuff internally - see the [comment](https://github.com/pyiron/pyiron_base/pull/875#issuecomment-1323535407) it lays out the steps necessary to reproduce the behaviour that I'm talking about here.

**Comment by ligerzero-ai** [comment]
It's fixed now in that branch because it has a "manual" database update, but just comment out the database update line 
```
                    self.project.db.item_update({"status": "aborted"}, self._job_id)
```
in the kill function in #875 and you will see that the database doesn't update when job.kill() is called.

**Comment by jan-janssen** [comment]
> Yeah, but I am more talking about setting stuff internally - see the [comment](https://github.com/pyiron/pyiron_base/pull/875#issuecomment-1323535407) it lays out the steps necessary to reproduce the behaviour that I'm talking about here.

Do you use the central Postgres database or do you use pyiron without a database?
