### ISSUE TITLE
Several issues with unpacked projects

### ISSUE THREAD

**Issue by ligerzero-ai** [pyiron/pyiron_base#931]
Consider:

I have a compressed `unconverged_tests.tar.gz` file from another project:
```
pr = Project("test")
pr.unpack(origin_path="unconverged_tests")
```
Now I want to create a copy of a job using `copy_to`:
```
job = pr.load("P")
job.copy_to("P_experiment")
```

Note that this is a completely different project. So in fact, the behaviour in #830 is probably more general overall.
`pr.job_table()` yields:
<html>
<body>

  | id | status | chemicalformula | job | subjob | projectpath | project | timestart | timestop | totalcputime | computer | hamilton | hamversion | parentid | masterid
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
18429415 | aborted | Ni107P | P | /P | /cmmc/u/ | hmai/tests_for_dev_pyiron/test_pyiron_job_recovery/unconverged_tests/ | 2022-11-30 23:57:14.265835 | None | None | hmai@cmti001#120#cm | Vasp | 5.4.4_mpi_AutoReconverge | None | None
18429416 | aborted | CrNi107 | Cr | /Cr | /cmmc/u/ | hmai/tests_for_dev_pyiron/test_pyiron_job_recovery/unconverged_tests/ | 2022-12-01 00:21:05.799453 | None | None | hmai@cmti001#120#cm | Vasp | 5.4.4_mpi_AutoReconverge | None | None
18429417 | aborted | Ni107Sr | Sr | /Sr | /cmmc/u/ | hmai/tests_for_dev_pyiron/test_pyiron_job_recovery/unconverged_tests/ | 2022-12-01 00:37:21.992183 | None | None | hmai@cmti001#120#cm | Vasp | 5.4.4_mpi_AutoReconverge | None | None
18429418 | not_converged | InNi107 | In | /In | /cmmc/u/ | hmai/tests_for_dev_pyiron/test_pyiron_job_recovery/unconverged_tests/ | 2022-12-01 00:49:52.897924 | None | None | hmai@cmti001#120#cm | Vasp | 5.4.4_mpi_AutoReconverge | None | None
18429419 | aborted | Ni107Te | Te | /Te | /cmmc/u/ | hmai/tests_for_dev_pyiron/test_pyiron_job_recovery/unconverged_tests/ | 2022-12-01 00:51:35.392024 | None | None | hmai@cmti001#120#cm | Vasp | 5.4.4_mpi_AutoReconverge | None | None
18429420 | aborted | Ni107Pt | Pt | /Pt | /cmmc/u/ | hmai/tests_for_dev_pyiron/test_pyiron_job_recovery/unconverged_tests/ | 2022-12-01 01:05:20.626637 | None | None | hmai@cmti001#120#cm | Vasp | 5.4.4_mpi_AutoReconverge | None | None
18429421 | aborted | Ni107Tl | Tl | /Tl | /cmmc/u/ | hmai/tests_for_dev_pyiron/test_pyiron_job_recovery/unconverged_tests/ | 2022-12-01 01:11:22.213982 | None | None | hmai@cmti001#120#cm | Vasp | 5.4.4_mpi_AutoReconverge | None | None
18429422 | not_converged | BiNi107 | Bi | /Bi | /cmmc/u/ | hmai/tests_for_dev_pyiron/test_pyiron_job_recovery/unconverged_tests/ | 2022-12-01 01:12:24.082848 | None | None | hmai@cmti001#120#cm | Vasp | 5.4.4_mpi_AutoReconverge | None | None
18429423 | aborted | Ni107Po | Po | /Po | /cmmc/u/ | hmai/tests_for_dev_pyiron/test_pyiron_job_recovery/unconverged_tests/ | 2022-12-01 01:14:26.187415 | None | None | hmai@cmti001#120#cm | Vasp | 5.4.4_mpi_AutoReconverge | None | None
18442532 | aborted | Ni107P | P | /P_experiment | /cmmc/u/ | hmai/tests_for_dev_pyiron/test_pyiron_job_recovery/ | 2022-11-30 23:57:14.265835 | None | None | hmai@cmti001#120#cm | Vasp | 5.4.4_mpi_AutoReconverge | None | None

</body>
</html>

Now, let us attempt to load the newly created `P_experiment` job:
`pr.load("P_experiment")`
`2022-12-02 13:36:38,969 - pyiron_log - WARNING - Job 'P_experiment' does not exist and cannot be loaded`

**So you cannot load a job that has been created with the `job.copy_to()` functionality! I am not sure if this has to do with the unconverged status of the job.**

At this point the folder structure looks like this:
```
hmai@cmti001:~/tests_for_dev_pyiron/test> ls
Bi.h5  Bi_hdf5  Cr.h5  Cr_hdf5  In.h5  In_hdf5  P.h5  P_hdf5  Po.h5  Po_hdf5  Pt.h5  Pt_hdf5  Sr.h5  Sr_hdf5  Te.h5  Te_hdf5  Tl.h5  Tl_hdf5  unconverged_tests
```
Notice the `unconverged_tests` folder.

Now let us remove the project.
`pr.remove(enable=True)`
This appears to run fine, but it doesn't. Calling `ls` yields:
```
hmai@cmti001:/cmmc/u/hmai/tests_for_dev_pyiron/test> ls
Bi_hdf5  Cr_hdf5  In_hdf5  P_hdf5  Po_hdf5  Pt_hdf5  Sr_hdf5  Te_hdf5  Tl_hdf5
```
So, it removes the `unconverged_tests` sub dir but doesn't remove the parent folder, `test`.

This may have to do with #930.

**Comment by liamhuber** [comment]
Should be addressed over in #886
