### ISSUE TITLE
Bug in ProjectPath tests?

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_base#953]
Shouldn't [this line](https://github.com/pyiron/pyiron_base/blob/685fa919d25c5e844e4b29548b6291892482f8fe/tests/project/test_projectPath.py#L78) be `root_paths = state.settings.configuration["project_paths"]`?

In `setUpClass` we have `cls.settings_configuration = state.settings.configuration.copy()`, then in `setUp` we have `state.settings.configuration["project_paths"] = [self.current_dir]; state.settings.configuration["project_check_enabled"] = True`, and finally in the test we're setting `root_paths = self.settings_configuration["project_paths"]` and expecting it to be non-empty. Now, this passes on the remote CI, but in `pyironconfig.py` we're explicitly setting `TOP_LEVEL_DIRS` (i.e. `project_paths`), so maybe that allows it to get by even though it's comparing to the wrong thing? On my local machine, where `project_paths = []` and `project_check_enabled = False`, this test fails, exactly because `root_paths == []`.

I get the exact same failure in `test_root_path` for [exactly the same (suspected) reason](https://github.com/pyiron/pyiron_base/blob/685fa919d25c5e844e4b29548b6291892482f8fe/tests/project/test_projectPath.py#L70)

**Comment by niklassiemer** [comment]
I cannot check in detail right now. However, one common issue is that we have _different_ names for the same thing in our config and at the project level. I.e. we have `pr.root_path` being in the `config['project_paths']` list...

And I tried in many cases to be independent of the `.pyiron` configuration file, i.e. to change the configuration before and restore it after the tests.

**Comment by liamhuber** [comment]
> I cannot check in detail right now.

Yep, no worries! (a) it's almost Christmas, and (b) you're on leave. I expect to work it out myself, I just want to make sure I keep you in the loop 😄 

> And I tried in many cases to be independent of the .pyiron configuration file, i.e. to change the configuration before and restore it after the tests.

Yes, this part is working beautifully. The problem as I see it is that the tests are then relying on a variable defined _prior_ to these updates. Because of our CI setup it so happens that these prior values still make the test work, but on my local machine (and any machine without `root_path`/`config['project_paths']`/ENV `TOP_LEVEL_DIRS`/etc defined, they fail. If the tests rely on paths _after_ your config update, I expect them to work.

**Comment by niklassiemer** [comment]
What I meant is, that I would like to set something like a test default for our configuration. I.e. first set  config to the test default, then change the things and test - expecting the test defaults, and finally restoring the original definition.
