### ISSUE TITLE
What does the time of hdf access depend on?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_base#978]
Some time ago I realized that especially for large jobs the hdf access time becomes extremely long. Here, I'm not talking about the job loading time, but the access time to the output values, i.e.

```python
# Not this line
job = pr.load('job_name')
# But this line
job['output/generic/energy_pot']
```

So far, I tried to erase a few entries inside the HDF file (not very consistently though), but I don't have the feeling that the access time improved a lot.

As I already said above, it tends to become slower for long calculations. For example in my case I'm talking about SPHInX calculations for Fe-Mn, which requires days to converge.

I'd be already glad to know what it depends on. And if there's someone with a specific solution that could be even better.

**Comment by pmrv** [comment]
In theory `job['output/generic/energy_pot']` should results in a single file access and not incur a lot of overhead on our side, so I would think that reading from HDF itself is slow if the file is large, but it's difficult to tell without a profile.  Have you tried repacking the HDF5 file (`h5repack` on the command line or `job.project_hdf5.rewrite_hdf5`)?

**Comment by samwaseda** [comment]
> Have you tried repacking the HDF5 file (`h5repack` on the command line or `job.project_hdf5.rewrite_hdf5`)?

Ah that's a brilliant idea. I'm gonna give it a try.

**Comment by jan-janssen** [comment]
@samwaseda As this issue has been inactive for more than six month I am going to close it and assume that the `rewrite_hdf5()` function @pmrv suggested solved the issue.
