### ISSUE TITLE
submit jobs fail with run times less than 1 min

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_base#98]
I need preface this by saying pyiron_base might be totally the wrong place to put this! It's just a best guess on the cause, and the offending line is in `GenericJob` so I put it here... Also, I'm labelling it as both a bug and an enhancement, because we need to enhance the code by covering this corner-case bug. Basically I'm just trying to make the most provocative and annoying issue as I can 😉 

The behaviour is that when you run a queue-side job with too short of a run time, pyiron throws an error. What I don't like is that the stack trace is incredibly unhelpful, ending with `ValueError: run_queue.sh crashed`, which is about as vague as you can get. 

When I dug into what was actually called, it quickly runs into pysqa. Since the job fails for `job.server.run_time=59` but passes for `60`, I guess somewhere we're converting into minutes, but then taking the floor or somesuch so the run time gets sent to zero. Not sure where this is happening though. Does anyone with pysqa familiarity want to take a quick look?

MWE:

```python
from pyiron import Project
pr = Project('scratch')
job = pr.create_job(pr.job_type.Lammps, 'job', delete_existing_job=True)
job.structure = pr.create_ase_bulk('Al', cubic=True)
job.potential = job.list_potentials()[0]
job.server.queue = 'cm'
job.server.run_time = 59   # Fails for anything < 60, even 59.99.
job.run()
```

<details><summary>Resulting stack trace</summary>
<p>
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-5c6780fc6f4c> in <module>
      6 job.server.queue = 'cm'
      7 job.server.run_time = 59.99
----> 8 job.run()

~/pyiron_repos/pyiron_base/pyiron_base/job/generic.py in run(self, delete_existing_job, repair, debug, run_mode, run_again)
    666                 status = "created"
    667             if status == "initialized":
--> 668                 self._run_if_new(debug=debug)
    669             elif status == "created":
    670                 que_id = self._run_if_created()

~/pyiron_repos/pyiron_base/pyiron_base/job/generic.py in _run_if_new(self, debug)
   1337         else:
   1338             self.save()
-> 1339             self.run()
   1340 
   1341     def _run_if_created(self):

~/pyiron_repos/pyiron_base/pyiron_base/job/generic.py in run(self, delete_existing_job, repair, debug, run_mode, run_again)
    668                 self._run_if_new(debug=debug)
    669             elif status == "created":
--> 670                 que_id = self._run_if_created()
    671                 if que_id:
    672                     self._logger.info(

~/pyiron_repos/pyiron_base/pyiron_base/job/generic.py in _run_if_created(self)
   1358             self.run_if_non_modal()
   1359         elif self.server.run_mode.queue:
-> 1360             return self.run_if_scheduler()
   1361         elif self.server.run_mode.interactive:
   1362             self.run_if_interactive()

~/pyiron_repos/pyiron_base/pyiron_base/job/generic.py in run_if_scheduler(self)
    962             self._logger.warning("Job aborted")
    963             self.status.aborted = True
--> 964             raise ValueError("run_queue.sh crashed")
    965         s.logger.debug("submitted %s", self.job_name)
    966         self._logger.debug("job status: %s", self.status)

ValueError: run_queue.sh crashed
```
</p>
</details>

**Comment by jan-janssen** [comment]
https://github.com/pyiron/pysqa/blob/master/tests/config/slurm/slurm.sh#L8

**Comment by pmrv** [comment]
I guess we should change that to `max(1, run_time_max//60)`.  Does Jinja support that?

(My bad btw.).

**Comment by pmrv** [comment]
It seems you can.  I'll go ahead and make a PR.

**Comment by liamhuber** [comment]
No idea about the support, but I'm 100% behind the solution
